### ISSUE TITLE
Error when loading facebook SDK

### ISSUE THREAD

**Issue by fredleput** [KingSora/OverlayScrollbars#10]
hi, i'm back
I'm sorry about that but when i load the facebook javascript SDK i get errors from OverlayScrollbar.js.

`Uncaught DOMException: Blocked a frame with origin "http://www.cc-paimpol-goelo.com" from accessing a cross-origin frame.
    at http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:10504
    at x.each (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:8725)
    at v.each (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:8853)
    at v.on (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:10476)
    at http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:16359
    at new c (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:16828)
    at l (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:13656)
    at e.(anonymous function) (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/OverlayScrollbars.min.js:14:53145)
    at HTMLDocument.<anonymous> (http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/wp-content/themes/gp3a/js/init-accueil.js:96:29)
    at l (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js?ver=3.3.1:2:29375)`

error in my script init-accueil at line 96 correspond to the creation of my scrollbar instance.

If i don't load facebook sdk all is alwright.

Last thing, error occurs in chrome, IE but not in Firefox (i don't remember if i add a security exception..)

Thx for help,

Fred, Brittany - France.

**Comment by KingSora** [comment]
At first sight it appears you are trying to initialize the plugin into a iframe of facebook. This won't work due to a cross-origin exception (the same thing which is happening now). 

Please upload a small codesample of the facebook SDK on [https://jsfiddle.net/](https://jsfiddle.net/), so I can get a deeper understanding of the problem.

**Comment by fredleput** [comment]
Thx, here's my code (i don't use any iframe...) :

https://jsfiddle.net/fredleput/cpzjq61u/

**Comment by KingSora** [comment]
[https://jsfiddle.net/cpzjq61u/3/](https://jsfiddle.net/cpzjq61u/3/)

This script creates a div with the id `#fb-root` but I don't see any facebook content or anything?... To fix your problem, I have to see how the content which is loaded by the SDK really looks like. Please offer a version where the SDK is fully loaded and the content actually appears. Ignore the initialization of my plugin completely.

**Comment by fredleput** [comment]
you can see it in action here :
https://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/

**Comment by KingSora** [comment]
Well the scrollbar is loaded correctly on the element with the id `#actualites-resumes-liste`.
Am I overlooking something?
- Tested with Firefox, Chrome, Edge and IE

**Comment by fredleput** [comment]
With the same content here's a screenshot of chrome's console with error message :
![screenshot](https://user-images.githubusercontent.com/3998154/35973352-62ab4356-0cd5-11e8-868b-7db537016cb2.jpg)

**Comment by KingSora** [comment]
I am unable to reproduce this error... [Screenshot](https://i.imgur.com/NscdMHQ.png)
Maybe [this](https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame) article can help you?

I am sorry, but it seems like this error occurs because of your browser. Try to load jQuery not from a CDN but localy from your server.

**Comment by fredleput** [comment]
Thx i'll test that soon.

**Comment by KingSora** [comment]
Well I've another ideas:
Try to load the Facebook SDK after the plugin was initialized, or try to load it in a capsulated div and not direct into the body.

**Comment by fredleput** [comment]
Hi,

My problem is solved but i don't know why. I load jquery from my server but i still add the same issue. It's only when i initialize the plugin via jquery instead of the default way that the problem disappeared.

**Comment by KingSora** [comment]
I'm glad your problem has been solved!
I've checked your code and I've noticed you are using v1.0.0 of the plugin. Please try to use the current version (v1.2.3) and report me if your website runs fine with it too.

Thanks!

**Comment by fredleput** [comment]
No problem with version 1.2.3 in my news module but i try to use it also in my customs overlays (fixed positioned div with content) and i don't succeed. 

I initialize the plugin like this :

`jQuery(overlayMainContent).overlayScrollbars({
                    overflowBehavior : {
                        x: 'h',
                        y: 'v-s'
                    },
                    scrollbars: {
                        visibility: 'v'
                    },
                    callbacks : {
                        onInitialized : function() {
                            console.log('initialized');
                            console.dir(this);
                        }
                    }
                });`
Initilization seems working (i have log in console) but scrollbars aren't created. I send you a screenshot. You can see it in action here :
http://www.cc-paimpol-goelo.com/maquettes_cyber/gp3a-2/

just choose a news and click on 'En savoir plus'

screenshot-1 : we can see that classes are added to the container
screenshot-2 : log i call in the onInitialized callback

Thx very much for your help, ireally appreciate !

![screenshot-1](https://user-images.githubusercontent.com/3998154/36198657-7725ee3e-1177-11e8-8456-5aacc798d90d.jpg)
![screenshot-2](https://user-images.githubusercontent.com/3998154/36198658-773f87a4-1177-11e8-8b41-3d265e4bdaf4.jpg)

**Comment by KingSora** [comment]
Well, the mistake is, that you are loading different content into your div. This content is overwriting the DOM structure of the plugin.
To fix this you have two possibilites: 
1. Use a wrapper and initialize the plugin to the wrapper. Here is a demo: https://jsfiddle.net/Lesway8u/6/
2. You have to initialize the plugin each time your window gets opened and destroy it each time it gets closed.

I recommend the first solution since its more performent and more "elegant".

**Comment by fredleput** [comment]
Of course, i didn't thought to that ! It works great now. Many thx, you're the best !

**Comment by eagle-design** [comment]
i have the same issue with google ads and overlayscrollars

**Comment by KingSora** [comment]
@eagle-design Please open a new issue with your problem. Don't forget to provide or create a small example on https://jsfiddle.net so I can better understand your issue.

**Comment by eagle-design** [comment]
i had fixed it by enabling cords
