### ISSUE TITLE
scrollbars does not work with scrollTop Javascript...

### ISSUE THREAD

**Issue by KINETIK-DEV** [KingSora/OverlayScrollbars#100]
Hey there,

I remove the scrollbars lib and everything works fine again:

document.body.scrollTop = document.documentElement.scrollTop = 0;

but with it .. nope  it does not work..

Super important when it comes to navigation with huge long page ....

**Comment by KingSora** [comment]
Good day! 

If you use the plugin, scrolling via javascript works differently. It's actually more simple and you can use cool features such as animations and many more.

Please try the following after you've initialized the plugin:

```javascript
//get the plugin instance of the element you initialized the plugin to
var osInstance = OverlayScrollbars(document.body);
//perform the scroll action
osInstance.scroll({ top : 0 });
```

For more information about scrolling you can read the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll) or check the [scroll demo](https://kingsora.github.io/OverlayScrollbars/#!demos/scroll) page.

**Comment by KINETIK-DEV** [comment]
Hello ScrollbarMaster,

Thank you for your time : ) and effort you put into this one. I was too tired at 5am after long session of coding. I need to read the documention first lol. 

> `onScroll : function(eventArgs) { }`

 that also one i need.
and actually I did not know that OsBar changed html file a little bit so i was confused but after read some line of codes I understand what happens there.

**Comment by sujkh85** [comment]
I did this and it worked.

overlayRef.current?.osInstance().elements().viewport.scroll({ top: 0 })
