### ISSUE TITLE
Possibility of adding support for flex-direction: column-reverse;

### ISSUE THREAD

**Issue by WildEgo** [KingSora/OverlayScrollbars#101]
Hi Rene!

I was working on something and decided implementing ur library would be a good for my website and faced myself with a problem and when I use flex-direction: column-reverse; the scroll bar doesn't want to move I suppose it's because it's calculating from up to down and doesn't have anything to accept down to up calculation, any chance this would be added/fixed since I don't know if it's working as intended or not?

Kind Regards,
Luis Bizarro

**Comment by KingSora** [comment]
Good day!

To which element did you add the `flex-direction` css rule? Basically this should be already possible, because the plugin doesn't care about its content (I've designed the plugin that way, otherwise the plugin would need many many adjustments which wouldn't be very ideal).

**Comment by WildEgo** [comment]
I know this sounds incredibly stupid and it probably is but I had to add it into `.os-content` because I need to have the bar and the content always on the bottom, I think that makes sense but if there's any way around it I'd really appreciate it if u could explain me, it might be a really easy fix and I'm just over complicating stuff

**Comment by KingSora** [comment]
`.os-content` is the correct element. Please also add the rule `display: flex` if you haven't already, because else it shouldn't really work. Is it possible for you to create a demo on jsfiddle for me, so I can check where the problem lies? That would be really great and it would speed up the process of solving your issue.

**Comment by WildEgo** [comment]
`min-height: 100%;
display: flex;
flex-direction: column-reverse;
overflow: hidden;`

I'll send you the link of my current demo to your email if you don't mind

**Comment by KingSora** [comment]
Alright! I've got your example.

After a quite long investigation I've found out the following: it's a browser bug. It's sad, but thats indeed the case. To prove this, I've created a fiddle for you [here](https://jsfiddle.net/twg6k8pe/). As you can see, even the native scrollbar is disappearing if you switch to `flex-direction: column-reverse`, it has nothing to do with the plugin.

But I've also taken the time to try to fix this with a workaround. For this I've also created a fiddle [here](https://jsfiddle.net/k3zh7Lsb/). 
To use this workaround please change the CSS of `.os-content` to the following:

```CSS
{
    min-height: 100%; 
    display: flex; 
    flex-direction: column-reverse;
    height: auto !important;
}
```

The `height: auto !important` is the workaround to this bug, please also never apply a `overflow` rule to this element, as the plugin is managing this property by itself. This workaround comes also with some drawbacks, but they aren't affecting your layout so they doesn't matter. Just don't apply this to every `.os-content` element, apply this only to the affected one.

**Comment by WildEgo** [comment]
Thank you a lot I really appreciated I should've realized it sooner!

**Comment by KingSora** [comment]
I'm sorry but I don't understand your new problem, what is the new goal?

**Comment by WildEgo** [comment]
I'm sorry for my wording I wanted to scroll the bar to 100% on every "onContentSizeChanged" it's probably simple but my brain not working to the best of it's capacities lately

**Comment by KingSora** [comment]
In this case the code should be something like this:

```javascript
$('your-element').overlayScrollbars({
    callbacks : {
        onContentSizeChanged : function() { 
            this.scroll({ y : '100%' });
        }
    }
});
```

**Comment by KingSora** [comment]
Is your problem solved? - Small feedback please, so I know whether I can close this issue.

**Comment by WildEgo** [comment]
YEs should be perfect thank you I'm sorry I didn't check my email too much lately!
