### ISSUE TITLE
Trigger `onScroll()` on initialize

### ISSUE THREAD

**Issue by DRSDavidSoft** [KingSora/OverlayScrollbars#104]
I might have not found this in the documentation, but is there a way to call the `onScroll` callback when the object is initialized?

Currently I have to manually call it like this:
```javascript
onInitialized: function() {
	this.options("callbacks.onScroll").call(this);
},
```

The reason I want to do this is to display navigation buttons when appropriate:
```javascript
onScroll: function() {
	const offset = this.scroll(), tolerance = 8,
		prevVisible = offset.position.x > tolerance,
		nextVisible = offset.max.x - offset.position.x > tolerance;
	// ...
}
```

So OSB has to fire the `onScroll()` callback at least once after it has been initialized, so my logic can display the previous/next buttons where it is necessary.

Is there a missing option or something to set?

**Comment by KingSora** [comment]
Good day!

The `onScroll` callback is just called if the `viewport` element does some scrolling and that wont change because the event argument is the native `scroll-event-object`. This callback isn't intended to be called right after initialization.

**Comment by DRSDavidSoft** [comment]
Thanks for getting back to me so quickly!

So, what I'm doing is the logical approach here?

**Comment by KingSora** [comment]
Yes, indeed. But I wouldn't call callbacks just like you did, I would create a separate function and call the function instead. Its essentially the same, but I think its "cleaner" that way:

```javascript
function myFunction() {
	const offset = this.scroll(), tolerance = 8,
	prevVisible = offset.position.x > tolerance,
	nextVisible = offset.max.x - offset.position.x > tolerance;
	//...
}
var osInstance = OverlayScrollbars(document.getElementById('myElm', {
	onInitialized: function() {
		myFunction.call(this);
	},
	onScroll: function() {
		myFunction.call(this);
	}
});
```

**Comment by DRSDavidSoft** [comment]
@KingSora Your suggestion is surely better than my approach, thanks!
