### ISSUE TITLE
Fire event when we reach end of scroll

### ISSUE THREAD

**Issue by hsharma89** [KingSora/OverlayScrollbars#105]
Hi,

I am using overlay scrollbar with one of my div. I need to fire function when i reach at the end of the scroll. 

For scroll i run the following function.

 $('#my-element').overlayScrollbars({

callbacks:
  {
        onScroll: funtion(e){
                              console.log('scrolling');
                       }
   }
});

This is working fine. Now i need to fire this event when we reach at end of scroll. How can i achieve this.

Thanks

**Comment by KingSora** [comment]
Good day!

I believe the code you are searching for is:
```javascript
$('#my-element').overlayScrollbars({
  callbacks: {
    onScroll: funtion() {
      var scrollInfo = this.scroll();
      if(scrollInfo.ratio.y === 1) {
        console.log('I am on the bottom!');
      }
    }
  }
});
```

**Comment by hsharma89** [comment]
hello,
         Yes, perfect. Worked like a charm.

Thanks
Himanshu Sharma

**Comment by KingSora** [comment]
Glad I could hep!

**Comment by two3d** [comment]
Hello, this callback doesn't work any more in Version: 2.9.2?
> ```js
> OverlayScrollbars(document.querySelector('#my-element'), {
>   callbacks: {
>     onScroll: function() {
>       var scrollInfo = this.scroll();
>       if(scrollInfo.ratio.y === 1) {
>         console.log('I am on the bottom!');
>       }
>     }
>   }
> });
> ```
