### ISSUE TITLE
jquery version of the OverlayScrollbars doesn't support scroll method.

### ISSUE THREAD

**Issue by danatinxeption** [KingSora/OverlayScrollbars#106]
I am using the jquery.overlayscrollbars.js on my site and initialized the code like such:
`
var customScroll = $('selector').overlayscrollbars({});
customScroll.scroll({y: '0%'}, 150);
`
It doesn't do anything, but if I use the overlayscrollbars.js, it works just fine when calling the scroll method.

**Comment by KingSora** [comment]
Good day!

This looks like a similar issue as #37, please.check out my [answer](https://github.com/KingSora/OverlayScrollbars/issues/37#issuecomment-387164128) there, and tell me if it solved your problem.

**Comment by danatinxeption** [comment]
Thanks for getting back so fast.

The solution I used is to just use the non jquery library and use jquery select method in the code instead of using document.querySelectAll() to keep the code consistent. Thanks.

`var customScroll = OverlayScrollbars($('selector')[0], {})`
