### ISSUE TITLE
How do I get it to work?

### ISSUE THREAD

**Issue by Tarang74** [KingSora/OverlayScrollbars#109]
I've added the 

```
<script type="application/javascript">
    var instance = OverlayScrollbars(document.getElementById(id), {});
</script>
```

I am very new to this, what else do I need?
Pls help
(the CSS and JS are linked already)

**Comment by KingSora** [comment]
Good day!

The first parameter, where you passed `document.getElementById(id)` has to correspond to the element to which you want to apply the plugin to. So for example for the body element it has to be:
```javascript
var instance = OverlayScrollbars(document.body, { });
```
I suspect you havent specified the `id` variable, which is necessary for the example you posted.

**Comment by KingSora** [comment]
@Tarang74 I'll close this issue for now. 
If you have any further questions or if my answer didn't solve your problem, please feel free to reach out to me in this issue again.
