### ISSUE TITLE
instance.scroll({ y: "100%" }) probelm

### ISSUE THREAD

**Issue by amirhoseinsalehi** [KingSora/OverlayScrollbars#110]
I've used "overlayscrollbars" without jquery in react & webpack project, initial phase of plugin was ok but when I want to scroll to bottom, this error is write on my page:

`ReferenceError: $ is not defined` 

![Screen Shot 2019-05-21 at 3 16 13 PM](https://user-images.githubusercontent.com/32030546/58089986-6c81a200-7bdb-11e9-8aef-83a5489bb063.png)

this is my code: `instance.scroll({ y: "100%" });`

it's funny because I've used version without jquery but plugin is based on jquery.
please fix this issue.
tnx

**Comment by KingSora** [comment]
Good day!

Oh boy, thats a tiny and embarrassing mistake... Thanks!

**Comment by amirhoseinsalehi** [comment]
tnx a lot..
when you fix it? :)

**Comment by KingSora** [comment]
As fast as possible, I'll update the NPM & Github repo today or tomorrow depending on my time.

**Comment by KingSora** [comment]
The problem should be fixed in [v1.7.1](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.7.1), please confirm it!

**Comment by KingSora** [comment]
I'll close this issue since it should be fixed... If it's not the case and you still have this bug with version `1.7.1` please don't hesitate comment here
