### ISSUE TITLE
Simple testing

### ISSUE THREAD

**Issue by netvillage** [KingSora/OverlayScrollbars#111]
Just trying to get a demo to work. running locally. My code looks like this. but nothing happens.

<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Scroller Testing</title>
<link type="text/css" href="OverlayScrollbars-master/css/OverlayScrollbars.css" rel="stylesheet">	
<script  src="https://code.jquery.com/jquery-1.12.4.min.js"  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="  crossorigin="anonymous"></script>
<script type="text/javascript" src="OverlayScrollbars-master/js/jquery.overlayScrollbars.js"></script>
</head>
<body>
<main id="main" role="main">
	<h1>Test scroller</h1>
	
	<p><button id="add">Add Content</button></p>
	<script>
	$("#add").click(function(){ 
		$("<p>Pellentesque habitant morbi tristique senectus et netus et malestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>").appendTo("#scrollarea");
	});
	</script>
	
	<div id="scrollarea">
		<div><p>asdasdsad asdasdsad asdasdsad asdasdsad asdasdsad </p></div>
		<div><p>asdasdsad asdasdsad asdasdsad asdasdsad asdasdsad </p></div>
		<div><p>asdasdsad asdasdsad asdasdsad asdasdsad asdasdsad </p></div>
		<div><p>asdasdsad asdasdsad asdasdsad asdasdsad asdasdsad </p></div>
		<div><p>asdasdsad asdasdsad asdasdsad asdasdsad asdasdsad </p></div>
		<div><p>asdasdsad asdasdsad asdasdsad asdasdsad asdasdsad </p></div>
	</div>
	
</main>
<textarea id="txtbox" cols="50" rows="5">
This is where the user can enter text. If there's too much text, the textbox can develop scrollbars to accommodate the extra text...
</textarea>
	
<script>
	$(function() {
		// $("body").overlayScrollbars({ }); // works
		
		$("#scrollarea").overlayScrollbars({ });  // fails

		// var instance = OverlayScrollbars(document.getElementById("scrollarea"), {});  // fails 
		
		// FAILS - well it looses formating and don't see bars until too much text
		// $("#txtbox").overlayScrollbars({ 
		// 	scrollbars: { visibility: "auto" } 
		// });
	});
</script>

</body>
</html>

None of these works. Thoughts?

I do notice when I start I get this error in the console, not sure if relevant
"[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by KingSora** [comment]
Good day!

I don't know where your code exactly fails, but I've uploaded a `test.html` for you which uses your code above as base. I've added comments to code parts which are different from your code, where I also explain them.

I also do not get the chrome warning you're getting. In case you're getting it also in the uploaded html, is it possible for you to give me the line-number / eventname which is causing this?

If you have any further questions, please do not hestitate to ask them!

[test.zip](https://github.com/KingSora/OverlayScrollbars/files/3213775/test.zip)

**Comment by netvillage** [comment]
dude you are awesome. I will try this cool demo. 
I wonder if the error maybe the result of me running it as file:/// rather than http. I will check and report back

**Comment by netvillage** [comment]
works good. This line was especially useful

//if scrollarea has OverlayScrollbars instance add it to the generated content element, else to the scrollarea directtly
contentToAdd.appendTo(scrollarea.overlayScrollbars() instanceof OverlayScrollbars ? osInstanceScrollarea.getElements().content : scrollarea);


BTW, the 
"[Violation] Added non-passive event listener to a scroll-blocking event. Consider marking event handler as 'passive' to make the page more responsive"
is still there, but things work great. Maybe it will become and issue in the future.
I did notice it did not appear in IE or firefox, just chrome

**Comment by KingSora** [comment]
Thanks for the feedback! May I know your Chrome version? Since it's not appearing on my end this may be the reason for it.

**Comment by netvillage** [comment]
Version 74.0.3729.157 (Official Build) (64-bit)
