### ISSUE TITLE
Page gets weird dimensions after initializing OverlayScrollbars

### ISSUE THREAD

**Issue by Nosskirneh** [KingSora/OverlayScrollbars#112]
Good day!

I just started playing around with OverlayScrollbars and it looks really neat, so thank you for the hard work you have put in!

However, I'm having a weird issue: after initializing OverlayScrollbars on any textarea, the page size is increasing to extremes. It seems to be the `os-resize-observer-item-final` elements that get their width and height style set to a large number.

This is ran after the page has finished loaded:           `$('[name="SärskildaFörkunskaperAndraVillkorMotivering"]').overlayScrollbars(OverlayScrollbars.defaultOptions());`

which results in:
![image](https://user-images.githubusercontent.com/16581727/58467304-aef73180-813b-11e9-8b1b-2c4b8795475d.png)

Do you have any idea why this happens?
Thanks!

**Comment by Nosskirneh** [comment]
So apparently the same thing happens on the textarea demo of yours, but the page doesn't become extremely long and wide because of it. I'm confused 🤔

**Comment by KingSora** [comment]
Good day!

To me it seems like you've forgotten to reference the plugins CSS into your page, since I cant see the styles in the Style-Rules Tab... Please check this out, if this isn't the cause I'll look into that further.

**Comment by Nosskirneh** [comment]
That was it, now I feel real stupid hah. Thank you for helping out!

**Comment by KingSora** [comment]
Hey, everybody makes mistakes ;)
Glad I could help!
