### ISSUE TITLE
limit to scroll size area?

### ISSUE THREAD

**Issue by netvillage** [KingSora/OverlayScrollbars#113]
I'm wondering how big the scroll area can get before it goes wacky?
I was thinking of removing older entries when it reached a certain limit. Something like
if (++lineCount > maxScrollbackLines) {
      osInstanceScrollarea.getElements().content.removeChild(osInstanceScrollarea.getElements().content.firstChild);
        --lineCount;
 }
But not sure it that is the best way

**Comment by KingSora** [comment]
I'm sorry but I don't understand the potential problem (or is this just a hypothetical question?)
My understanding is the following: If the content has too many items or the size gets too big, you want to remove the items on the beginning to reduce the size again. And your question is now whats the best way to achieve this, is this correct?

**Comment by netvillage** [comment]
well I think it may be a potential problem. Like I have a text adventure game, and the data will keep on coming, perhaps for hours. I'm just seeing it may get crazy after a bit. Just trying to head off trouble.

**Comment by KingSora** [comment]
Alright, I'll give you some insight and a few numbers... Basically OverlayScrollbars doesn't care about its content, in the code it's never touched or anything. The code will run always in the same time, regardless if there are 5 or 5Million items. (Rendering is a different thing, but thats browser specific)

OverlayScrollbars uses a `ResizeObserver` on Browsers which supports it (Chrome & other Webkit based Browsers), in this case OverlayScrollbars doesn't really care how long its content is or how many elements there are. On Browsers which doesn't support the `ResizeObserver` API the plugin uses a self written polyfill based on the resize sensor of [CSS Element Queries](https://github.com/marcj/css-element-queries), just with a few tweaks, improvements and other stuff. This implementation requires fixed sizes which defines a upper bound to which size the observer will work. OverlayScrollbars uses a max size of `3333333px`. If your content is bigger than that and your Browser isn't able to use the `ResizeObserver` API the polyfill won't work 100% correctly anymore. - But that only counts if your DOM meets special conditions and has `auto`-size. (height: `auto` etc.)

I think the best way to control this behavior is to check the `scrollHeight` /- `Width` of the `os-content` element and if this number is too big (you can decide this bound as you like, but I would go with 1-3Million pixels) I would remove some amount of elements on the beginning to have a buffer for items which will be added in the future. This cicle can continue pretty much forever.

**Comment by netvillage** [comment]
wow. that is fantastic info. You are the master.

**Comment by KingSora** [comment]
Glad I could help you! I'll close the issue for now. In case you've further questions about this topic feel free to ask them here.
