### ISSUE TITLE
Resize Observer Host Issue

### ISSUE THREAD

**Issue by azaidi4** [KingSora/OverlayScrollbars#114]
I am working on a chatbot based app. The screen is split vertically into two components, both of which have their own scrollbar. 

<img width="720" alt="Screen Shot 2019-05-31 at 1 45 29 AM" src="https://user-images.githubusercontent.com/26014477/58686927-d0c40480-8345-11e9-83f1-32e919ece766.png">

I also have a fullscreen feature which hides hides the ChatPanel and only displays the DisplayPanel (the chevron in the right-middle). On clicking it, I set the visibility of ChatPanel to none. The issue I run into is after I disable fullscreen. My chat bubbles end up like this: 

<img width="719" alt="Screen Shot 2019-05-31 at 1 49 19 AM" src="https://user-images.githubusercontent.com/26014477/58687110-58aa0e80-8346-11e9-84c1-e8dd96b41191.png">

On inspecting, I observe that Resize Observer changes it's dimensions, leading to the text shifting to the left. Initially, it's the dimensions of the ChatPanel. On enabling fullscreen it has dimensions `<full_viewport_height> x 0`, on disabling fullscreen it changes dimension to `<full_viewport_height> x <full_viewport_width>`.

This is a react application. I've initialized as follows: 
```javascript
import 'overlayscrollbars/css/OverlayScrollbars.css'
import OverlayScrollbars from 'overlayscrollbars'
...
componentDidMount = () => {
    this.scrollInstance =  OverlayScrollbars(document.querySelectorAll(".ChatPanel"), {
      sizeAutoCapable : false,
      scrollbars: {
        clickScrolling: true
      }
    });
}
```
I've tried setting `sizeAutoCapable: True` and run into the same issue. Some help would be appreciated. Thanks!

**Comment by KingSora** [comment]
Good day!

Could you upload your application somewhere, or create a small example of this issue on [Codesandbox](https://codesandbox.io)? I'm sorry but without a example I can't identify the issue even though your description is very clear.

**Comment by azaidi4** [comment]
@KingSora I got around this issue by wrapping the element in a div and setting `height: 100%, width:100%`. Might have been a display grid issue. You can close this issue

**Comment by KingSora** [comment]
@azaidi4 Thanks for sharing your solution!

**Comment by ivanabovin** [comment]
my solution

```js
setInterval(() => {
  const state = os.state()
  const root = document.documentElement
  const scroll = root.clientHeight < root.scrollHeight
  const y = scroll ? 'scroll' : 'hidden'
  if (state.overflowStyle.y !== y) os.update(true)
}, 100)
```
