### ISSUE TITLE
IE 11 - content inside is not visibe unless we give explicit height

### ISSUE THREAD

**Issue by Saranyanr30** [KingSora/OverlayScrollbars#115]
Thank you for your OverlayScrollbars plugin which supports all browsers and also provides customised styles.

Its working perfect in chrome, firefox and Edge, but I have small issue in IE 11

Content is not visible, unless I give explicit height, but i don't have fixed height for that container, what should i do?  please help...

**Comment by KingSora** [comment]
Good day!

Could you provide a small demo of your layout somewhere? - You can use sites like [jsfiddle](https://jsfiddle.net/) for that purpose. It's pretty hard to identify the issue without any example.

**Comment by Saranyanr30** [comment]
Ok.. I used jQuery UI dialog, in that I had that issue..
Later I tried outside, I had same issue..

In IE 11, the element in which I add custom scroll is not visible unless the element has fixed height...

I will try to replicate that issue in jsfiddle

**Comment by KingSora** [comment]
Whats also important to mention for auto sized content, set the option `sizeAutoCapable` to `true` (it is also  by default `true`).

**Comment by Saranyanr30** [comment]
Hi, I am sorry, thats not the issue in your plugin, I checked now seperately, its working perfect..
But I am facing the issue in my project, there they have used c# razor, before 5 years they started that application, may be I will check jquery version and they have used xml, they havent used DOCTYPE html,
because of that, I already faced many issue, window height in jquery was not working, may be this issue also because of that
Thank you so much
Tomorrow, in Office I will check the issue, I dont have access to the application now.. I will reach out to you if I need help, Thank you..

**Comment by Saranyanr30** [comment]
Hi, I used flex to the element which i added scroll, now in IE 11, its visible.. Thank you..
but Above issue is because of application I am working on, some of jquery methods not working properly, since they have used both html and xml, they havent included doctype html, because of that , if i use window.height() - it gives document height instead, so found fix for that using window.innerHeight

But there is small issue in plugin, if i add vertical padding to element inside custom scroll wrap, even when max height is not reached, there is vertical scroll in IE11 and Edge - because of that vertical padding used for elements inside custom scroll, so i removed vertical padding, thats just a list, so I gave space between list elements by adding line height.. now it works perfect..

**Comment by Saranyanr30** [comment]
Thank you for your custom scroll plugin, Its Awesome....

**Comment by KingSora** [comment]
@Saranyanr30 I'm glad this issue is solved for you. The vertical padding issue you mentioned could be happening because you're using a flexbox layout. - The plugin struggels a bit with flexbox. I've created a guide which could solve your flexbox issues [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/flexbox).
