### ISSUE TITLE
Scrollbar not overlaying content in Firefox

### ISSUE THREAD

**Issue by Devstackr8** [KingSora/OverlayScrollbars#117]
In Firefox, there seems to be some padding added to the right such that the scrollbar isn't overlaying the content like it does in Chrome and Edge. I was wondering if there is a way to prevent this.

![Screenshot](https://user-images.githubusercontent.com/42569312/59048793-87604180-887e-11e9-8483-0e6db320f86e.png)

I can see from the Inspector (in Firefox) that there is a 30px transparent border on the os-content div.
`border-right: 30px solid transparent;`

Many thanks in advance.

**Comment by Devstackr8** [comment]
Just worked out what the issue was, I am using angular and was running `OverlayScrollbars(document.querySelectorAll('.sidebar-items'), {});` in ngOnInit(). I put it within a setTimeout() and now the scrollbar is properly positioned.

Here is my final code:
```
setTimeout(() => {
      OverlayScrollbars(document.querySelectorAll('.sidebar-items'), {})
    }, 1);
```

**Comment by KingSora** [comment]
@Devstackr8  Good day!

Even if you solved your issue already, please consider initializing OverlayScrollbars in angular like I described it in #107 (in the `ngAfterViewInit` function).

**Comment by Devstackr8** [comment]
@KingSora Ah ok, will do! Thanks :)
