### ISSUE TITLE
Overlay Scrollbars for Bootstrap Modals??

### ISSUE THREAD

**Issue by krystyna93** [KingSora/OverlayScrollbars#118]
I tried to implement the Overlay Scrollbars on the Bootstrap modal, but the default scrollbar is still present and functions, but the Overlay Scrollbar is visible but is non-functioning.

Can we use it on Bootstrapmodals?

Unfortunately, it really sux we cant have it work on selects, now I have to go and use the malihu scrollbar package instead...

**Comment by KingSora** [comment]
Good day! 

Its possible to use OverlayScrollbars on Bootstrap Modals and Bootstrap Dropdowns (Selects). If you could show me a example code on a site like [jsfiddle](https://jsfiddle.net/) I could help you more.

**Comment by krystyna93** [comment]
Please see this question, and please explain whether we can or not, because
it didn't work for me either on a bootstrap-select select:
https://github.com/KingSora/OverlayScrollbars/issues/93

**Comment by KingSora** [comment]
@krystyna93 
I've already linked two examples in #93 but to summarize this topic I'll post my complete answer here.
**Bootstrap Modal:**
- Bootstrap Modal with native Scrollbar: https://jsfiddle.net/p2965dfw/
- Bootstrap Modal with OverlayScrollbars: https://jsfiddle.net/p2965dfw/1

**Bootstrap Dropdown:**
- Bootstrap Dropdown with native Scrollbar: https://jsfiddle.net/2z6x17mh/
- Bootstrap Dropdown with OverlayScrollbars: https://jsfiddle.net/2z6x17mh/1/

**Comment by krystyna93** [comment]
Ah your the best, Rene!
Thanks for the examples

**Comment by krystyna93** [comment]
Hi Rene,

I specifically meant a select, not a dropdown.
Specifically, a select from the Bootstrap-select
<https://developer.snapappointments.com/bootstrap-select/> package.

You stated that OverlayScrollbar doesn't support it??

**Comment by KingSora** [comment]
The disciussion about the select / dropdown was carried out in #93, in case you have more questions about it, please also write them in #93. In case you have any other questions about `Bootstrap Modals` write them here.
