### ISSUE TITLE
"main" field in package.json should point to unminifie code.

### ISSUE THREAD

**Issue by ashubham** [KingSora/OverlayScrollbars#12]
Currently the `main` field in `package.json` points  to `js/OverlayScrollbars.min.js`. I think it will be better if it points to `js/OverlayScrollbars.js`. it will have the following benefits:

- During dev, one needs an unminified view of the libs, so that one may debug deeper.
- Most apps, will have their own minification/packaging. Unminified code plugs in better with that
  workflow, including better compression ratios.

**Comment by KingSora** [comment]
Alright, in the next release (which will be pretty soon) I'll change that!

**Comment by KingSora** [comment]
The new version is here: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.3.0
If you have any other enhancements, please let me know!
