### ISSUE TITLE
OverlayScrollbars not working in Firefox 60

### ISSUE THREAD

**Issue by Sachien** [KingSora/OverlayScrollbars#122]
**No demo works on Firefox.**

**URL:** https://kingsora.github.io/OverlayScrollbars/#!demos/basic
**Version:** Firefox 60.7.1esr (32-bit)

**Error in console:** 
NS_ERROR_NOT_AVAILABLE:

**Error Stack:**
jquery.overlayScrollbars.js:616
OverlayScrollbarsGlobals/<.nativeScrollbarStyling<
https://kingsora.github.io/_framework/js/jquery.overlayScrollbars.js:616:106

OverlayScrollbarsGlobals
https://kingsora.github.io/_framework/js/jquery.overlayScrollbars.js:608:47

initOverlayScrollbarsStatics
https://kingsora.github.io/_framework/js/jquery.overlayScrollbars.js:572:39

PLUGIN</window[PLUGINNAME]
https://kingsora.github.io/_framework/js/jquery.overlayScrollbars.js:5225:17

JQUERY.fn.overlayScrollbars/<
https://kingsora.github.io/_framework/js/jquery.overlayScrollbars.js:5327:57

each
https://kingsora.github.io/_framework/plugins/js/jquery.min.js:2:2879

JQUERY.fn.overlayScrollbars
https://kingsora.github.io/_framework/js/jquery.overlayScrollbars.js:5327:21

<anonymous>
https://kingsora.github.io/_framework/js/framework.js:52:27

i
https://kingsora.github.io/_framework/plugins/js/jquery.min.js:2:27444

fireWith
https://kingsora.github.io/_framework/plugins/js/jquery.min.js:2:28213

ready
https://kingsora.github.io/_framework/plugins/js/jquery.min.js:2:30004

K
https://kingsora.github.io/_framework/plugins/js/jquery.min.js:2:30366

**Comment by KingSora** [comment]
Thanks for the report!

It will be fixed in the next version which will come as fast as possible. Thats a pretty weird bug though, since the code doesn't do anything super special.

**Comment by Sachien** [comment]
Thanks @KingSora for quick response,

Getting little bit confidence from your words "the code doesn't do anything super special". I modified below code

`return scrollbarDummyElement.css('scrollbar-width') === 'none' || (getCptStyle ? getCptStyle(scrollbarDummyElement0, '::-webkit-scrollbar').getPropertyValue('display') === 'none' : false);`

to
`return false; // scrollbarDummyElement.css('scrollbar-width') === 'none' || (getCptStyle ? getCptStyle(scrollbarDummyElement0, '::-webkit-scrollbar').getPropertyValue('display') === 'none' : false);`

And works fine in Firefox for now without breaking in IE and Chrome 👯‍♂

Looking for next fix version :)

**Comment by KingSora** [comment]
This should be fixed in [v1.8.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.8.0). Please test and confirm it, so I can close the issue.

**Comment by KingSora** [comment]
@Sachien I'll close this issue for now, as I've tested it on the reported FF version and everything is working (again). In case I've missed something and the bug still persists, please don't hesitate to write it here so I can review it once again and fix it for good.
