### ISSUE TITLE
Lighthouse warning : Passive listeners

### ISSUE THREAD

**Issue by tag9724** [KingSora/OverlayScrollbars#124]
Hi there, I just wanted to report a minor "bug", 
when passing a lighthouse audit OverlayScrollbars is flagged as not respecting best practices.

![2019-06-28_21-26-17_710](https://user-images.githubusercontent.com/1997780/60366385-acfae980-99eb-11e9-8ac7-6bc78972ce57.png)

Apparently it's related to touch and wheel events that doesn't use passive option, it's not really a big problem through but just wanted to let you know.

Sorry to have bothered you and thanks.

**Comment by KingSora** [comment]
Good day!

Well, the funny thing is, that OverlayScrollbars is indeed using `passive` events as you can see [here](https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L4426). As you can see it's only using them if they're supported. There might be a bug in the detection, could you give me the output of the `OverlayScrollbars.globals()` function, as the returning object contains this information.

It could also be useful if you check the `non-minified` version for this warning, as your tool is also reporting the location / line.

Thanks for the report!

**Comment by tag9724** [comment]
Here we go for the `globals()` result : 

```json
{
  "defaultOptions": {
    "className": "os-theme-dark",
    "resize": "none",
    "sizeAutoCapable": true,
    "clipAlways": true,
    "normalizeRTL": true,
    "paddingAbsolute": false,
    "autoUpdate": null,
    "autoUpdateInterval": 33,
    "nativeScrollbarsOverlaid": {
      "showNativeScrollbars": false,
      "initialize": true
    },
    "overflowBehavior": { "x": "scroll", "y": "scroll" },
    "scrollbars": {
      "visibility": "auto",
      "autoHide": "never",
      "autoHideDelay": 800,
      "dragScrolling": true,
      "clickScrolling": false,
      "touchSupport": true,
      "snapHandle": false
    },
    "textarea": {
      "dynWidth": false,
      "dynHeight": false,
      "inheritedAttrs": ["style", "class"]
    },
    "callbacks": {
      "onInitialized": null,
      "onInitializationWithdrawn": null,
      "onDestroyed": null,
      "onScrollStart": null,
      "onScroll": null,
      "onScrollStop": null,
      "onOverflowChanged": null,
      "onOverflowAmountChanged": null,
      "onDirectionChanged": null,
      "onContentSizeChanged": null,
      "onHostSizeChanged": null,
      "onUpdated": null
    }
  },
  "autoUpdateLoop": false,
  "autoUpdateRecommended": false,
  "nativeScrollbarSize": { "x": 17, "y": 17 },
  "nativeScrollbarIsOverlaid": { "x": false, "y": false },
  "nativeScrollbarStyling": true,
  "overlayScrollbarDummySize": { "x": 30, "y": 30 },
  "cssCalc": "calc",
  "restrictedMeasuring": false,
  "rtlScrollBehavior": { "i": true, "n": false },
  "supportTransform": true,
  "supportTransition": true,
  "supportPassiveEvents": true,
  "supportResizeObserver": true,
  "supportMutationObserver": true
}
```

And when tested in Lighthouse with the non-minified version I get the line 931

![2019-06-29_00-11-22_368](https://user-images.githubusercontent.com/1997780/60373972-7aa8b680-9a02-11e9-8a82-64a24bafdbcb.png)

I have already try quickly to manually add a {passive: true} here but since `preventDefault` is used on these listeners it does not work well.

https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L932

If you need anything else feel free to ask, and thanks for the quick reply.

**Comment by KingSora** [comment]
Thanks for you help mate, I'll investigate into this.

**Comment by KingSora** [comment]
Alright, I've figured out that lighthouse will report this warning on any non-passive touchevent, regardless if you call `preventDefault()` or not. The [documentation ](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners) of lighthouse says it will filter handlers which call `preventDefault()` inside out, but that doesn't happen. So I've filed a [bug](https://github.com/GoogleChrome/lighthouse/issues/9315) and it turns out, that the documentation needs a update. So lighthouse will warn on any non-passive touchevent. 

The only way to prevent this warning is to pass `passive : false` to the event. I'm not sure how I'll implement this into the code of `OverlayScrollbars`, since this isn't really affecting performance or anything, it just triggers this warning in lighthouse.

**Comment by tag9724** [comment]
Yes you're right if they are no problems on your side you have nothing to fix, nice job and thank you for the feedback.

**Comment by KingSora** [comment]
I've improved the behavior of the plugin in [v1.8.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.8.0) so this warning won't appear anymore. Please test it and give some feedback!

**Comment by tag9724** [comment]
Lighthouse is perfectly fine with it now

![2019-07-09_00-43-28_364](https://user-images.githubusercontent.com/1997780/60847347-aab23f80-a1e2-11e9-8f2a-ac808fb1cd28.png)

Thank you very much.

**Comment by ankitgehlot123** [comment]
![Capture](https://user-images.githubusercontent.com/11869963/62460356-6a24f200-b79f-11e9-8231-84fbe03da1ff.PNG)
this bug appeared again in v1.9.1 on line 932 when tested in Lighthouse with the non-minified.
