### ISSUE TITLE
When is the VUE version of the plugin coming out?

### ISSUE THREAD

**Issue by bigWillow** [KingSora/OverlayScrollbars#126]

**Comment by KingSora** [comment]
Good day!

All updates concerning any framework `wrapper` will be posted in #54.

**Comment by KingSora** [comment]
@bigWillow I've pushed the `vue` component to the repo. Please read my post (here)[https://github.com/KingSora/OverlayScrollbars/issues/54#issuecomment-516618253] for further info.
