### ISSUE TITLE
Scrolling with mouse wheel when hover on os-scrollbar-handle

### ISSUE THREAD

**Issue by Shakhmurat** [KingSora/OverlayScrollbars#128]
Good day.
You can check this on the plugin page.
And thanks for plugin.

**Comment by KingSora** [comment]
Hi,

yes, this is quite normal, as you are hovering over regular `div` elements, and they wont propagate the `scroll` command since they aren't children of the `viewport`. 
There is still the possibility to implement a custom scroll behavior by yourself.

**Comment by Shakhmurat** [comment]
Ok, It will be cool to see this in the next version.

**Comment by KingSora** [comment]
Unfortunately during testing came out that the current solution is only working in `chrome` / `webkit`... I'll try to come up with a solution for other browsers too, but I can't promise it.

**Comment by scrollbardeveloper** [comment]
If the scrollbar is wider than default then it's a bigger issue.

In my use case I only need it for Webkit. Could you please share the solution?

**Comment by KingSora** [comment]
This should be fixed in `v2` which released today :)
