### ISSUE TITLE
autoHide mousemove

### ISSUE THREAD

**Issue by KoalaBear84** [KingSora/OverlayScrollbars#13]
Library (and documentation) looks really great!

I would like an extra option for autoHide / show. If you have it on 'scroll' for example, I would like to also be able to see the scrollbar when I move my mouse on the page, and also hide it after X miliseconds.

P.s. I made an issue on cdnjs to get it 'hosted' over there:
https://github.com/cdnjs/cdnjs/issues/12562

**Comment by KingSora** [comment]
Greetings, I am glad you like my library!

I've created a small demo for you, please tell me if this is the behavior you expect: https://jsfiddle.net/t7rda5xd/8/embedded/result/

The scrollbars gets **shown** after:
- You moved your mouse
- You start scrolling

The scrollbars gets **hidden** after:
- You stopped move you mouse
- You stopped scrolling

P.S.: Thank you for the ticket, it would be awesome if they add my library to their CDN. :)

**Comment by KoalaBear84** [comment]
Wow, that is exactly what I mean! Would be great to have this option :)

**Comment by KingSora** [comment]
Alright pal, since this is a new feature I'll implement it in `version 1.4.0`. If I have enough time, I'll release it until the end of the week. 

The option will look like this:
```javascript
{
    scrollbars : {
        autoHide : "move",
    }
}
```
The shorthand will be the letter `m`.

Thank you for your suggestion, please let me know, If you have any other improvements for the library!

**Comment by KoalaBear84** [comment]
That's great. Take care!

**Comment by KingSora** [comment]
The release is here: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.4.0
I've updated the documentation too: https://kingsora.github.io/OverlayScrollbars/#!documentation/options

Thank you! :)

**Comment by KoalaBear84** [comment]
Great, works as expected. Thanks!

**Comment by KoalaBear84** [comment]
Just want to say that the ticket mentioned in the opening post is now closed.

OverlayScrollbars is now live on CDNJS:
https://cdnjs.com/libraries/overlayscrollbars

So people can use it though a CDN, and when using ASP.NET can use it with Libman: 
https://blogs.msdn.microsoft.com/webdev/2018/04/17/library-manager-client-side-content-manager-for-web-apps/

**Comment by KingSora** [comment]
@KoalaBear84 
Once again thank you for the CDNJS issue, I really appreciate your help! 
I'll update the README and the documentation page as soon as possible.
