### ISSUE TITLE
Is auto scroll on content change possible?

### ISSUE THREAD

**Issue by ilongley** [KingSora/OverlayScrollbars#130]
Hi

I'd like a scroll container to automatically scroll to the bottom when new content is added - for example logging output.

Is there a callback when the overflow changes or something similar?

**Comment by KingSora** [comment]
Good day!

Yes, according to the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/options) you have two possibilities: `onOverflowChanged` or / and  `onOverflowAmountChanged` callback. They both pass arguments with which you have more control and insight about what exactly happened to the overflow.

**Comment by ilongley** [comment]
Thank you very much for linking me to the correct place in the documentation. I knew I’d read about it a couple of months ago but I couldn’t for the life of me find it when I was looking through it this morning!!

Thanks again, this is a brilliant library btw ;)

**Comment by KingSora** [comment]
@ilongley glad I could help! - And thanks for your kind words :)
