### ISSUE TITLE
Consider making touch and wheel event passive(ref issue #124)

### ISSUE THREAD

**Issue by ankitgehlot123** [KingSora/OverlayScrollbars#131]
![Capture](https://user-images.githubusercontent.com/11869963/62460356-6a24f200-b79f-11e9-8231-84fbe03da1ff.PNG)
this bug appeared again in v1.9.1 on line 932 when tested in Lighthouse with the non-minified.

_Originally posted by @ankitgehlot123 in https://github.com/KingSora/OverlayScrollbars/issues/124#issuecomment-518192382_

**Comment by KingSora** [comment]
Good day!

Thanks, can you please also post your initialization code? - The problem isn't that listeners aren't passive, because they are. The problem is, that listeners which are calling `preventDefault()` inside and therefore can't be passive aren't added with `{ passive: false }`.

**Comment by ankitgehlot123** [comment]
Thanks for the Quick Response 
here it is-
 `OverlayScrollbars(document.body,{
             paddingAbsolute      : false,
             scrollbars : {
                    visibility       : 'auto',
                    autoHide         : 'scroll',
                    autoHideDelay    : 800,
                    dragScrolling    : true,
                    clickScrolling   : false,
                    touchSupport     : true,
                    snapHandle       : false
                  }});`
this is how i initialised overlayscrollbar..

**Comment by KingSora** [comment]
Alright, thanks for the code, I've pinpointed the problematic code and will fix this in the next version.
