### ISSUE TITLE
scrollbars unusable  when used in a sidebar div with display flex

### ISSUE THREAD

**Issue by pitz143** [KingSora/OverlayScrollbars#135]
I am initializing os scrollbar for a div which is a sidebar and overlayscrollbar is not seen.
1. I checked the loading order of css , overlayscrollbar.css is loaded first.
2. content is greater than div height
3. css is loaded properly, I can see from inspect element.
under what other cases can the scrollbar become unusable  ??

**Comment by KingSora** [comment]
Good day!

Since `flexbox` layout is special (and I recommend to use a wrapper `div` if possible) it can be due to many things. Please read and try the instructions given [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/flexbox) and give some feedback.

**Comment by KingSora** [comment]
@pitz143 any news on this issue?

**Comment by KingSora** [comment]
I'll close this issue due to inactivity. Feel free to reopen it if your issue still exists.
