### ISSUE TITLE
How can I switch the scroll direction?

### ISSUE THREAD

**Issue by starkovsky** [KingSora/OverlayScrollbars#136]
I need to change the scroll wheel of the mouse from vertical to horizontal.
How can i do this?

**Comment by KingSora** [comment]
Good day!

The plugin doesn't provide such a feature like this, so you'd have to do it by yourself. In the past I've created a example on [jsfiddle](https://jsfiddle.net/2sfaryb1/). Its done with jQuery and kind of sloppy, but you can use it as a guide. Maybe I'll write a `extension` for this usecase in the future.

**Comment by starkovsky** [comment]
@KingSora Thx for jsfiddle. I hope you can add this feature in the future.
