### ISSUE TITLE
Scrollbar is not visible when using angular 8.x

### ISSUE THREAD

**Issue by nirpan** [KingSora/OverlayScrollbars#137]
I am trying to create a very basic scrollbar using angular 8.x but I must be making some basic errors that I can't seem to find to initialise the scrollbar. I have created a [stackblitz link](https://stackblitz.com/edit/angular-s5xqwq). Is this a bug or something basic I have missed?

**Comment by KingSora** [comment]
Good day!

Currently the `height` of your `overlay-scrollbars` element is `auto` which means, that the element will grow with your content, and so a `overflow` will never happen. If you set a fixed `height` e.g. `height: 100%` or `height: 500px`, then a overflow will happen if the content is greater than that. 

I've created a a sample for you [here](https://stackblitz.com/edit/angular-pjjhnw?file=src/app/app.component.html), please note, that I've also made adjustments to the `styles.css`.

**Comment by nirpan** [comment]
Thank you very much. I didn't realise the overflow had to happen for the scrollbars to show but it completely makes sense. I am trying to integrate it within an Ionic4 App which I am hoping since it is already an angular module shouldn't be an issue.

**Comment by KingSora** [comment]
Glad I could help! :)
