### ISSUE TITLE
Wrong import style of OverlayScrollbars in overlayscrollbars.component.d.ts

### ISSUE THREAD

**Issue by 5te1n** [KingSora/OverlayScrollbars#138]
I get this Error, then importing the OverlayscrollbarsModule:

`ERROR in node_modules/overlayscrollbars-ngx/dist/types/overlayscrollbars.component.d.ts(2,8): error TS1192: Module '"..../Frontend/node_modules/@types/overlayscrollbars/index"' has no default export.`

The OverlyScrollbars namespace is imported like this in overlayscrollbars.component.d.ts(2,8):
`import OverlayScrollbars from 'overlayscrollbars';`

But it has to be imported like this:
`import * as OverlayScrollbars from 'overlayscrollbars';`

Versions: 
    "@types/overlayscrollbars": "1.9.0"
    "overlayscrollbars-ngx": "0.1.1"
    "overlayscrollbars": "1.9.1"

**Comment by KingSora** [comment]
Good day!

This issue is might related to your **tsconfig.json**, please set the recommended settings described [here](https://github.com/KingSora/OverlayScrollbars#typescript).

**Comment by 5te1n** [comment]
Thank You.
`"allowSyntheticDefaultImports": true,` did the trick.

**Comment by KingSora** [comment]
Glad I could help!
