### ISSUE TITLE
Typecheck fails when using with Angular and Ivy enabled

### ISSUE THREAD

**Issue by vdjurdjevic** [KingSora/OverlayScrollbars#141]
Angular wrapper library breaks build when Ivy renderer is enabled. Just enable Ivy to reproduce the issue. 

Here is error message:

 ERROR in __ng_typecheck__.ts(18,66): error TS2344: Type '"_options" | "_extensions"' does not satisfy the constraint '"ngOnDestroy" | "osInstance" | "osTarget" | "ngAfterViewInit" | "ngOnChanges"'.
  Type '"_options"' is not assignable to type '"ngOnDestroy" | "osInstance" | "osTarget" | "ngAfterViewInit" | "ngOnChanges"'.

**Comment by KingSora** [comment]
Good day!

Thanks, I'll look into this as soon as I have time.

**Comment by vladimirdjurdjevic** [comment]
@KingSora Hey, any news on this? If you don't have time to deal with this now, maybe I could get my hands on it this on Saturday, and file a PR?

**Comment by KingSora** [comment]
Hey, unfortunately I got injured last week and I don't really have the head for this right now. If you have time and can test it with Angular 7 and 8, I would be really happy to accept your PR.

**Comment by andriyor** [comment]
I just published my own version of a package that supports angular 9 with ivy. You can test it and report bugs. I can make PR if you want
https://www.npmjs.com/package/ngx-overlayscrollbars

**Comment by KingSora** [comment]
@andriyor cool, nice job! May I ask what you change to make it compatible with Angular 9? Or did you setup a whole new project and just pasted the component code?

**Comment by andriyor** [comment]
I followed this guide  https://angular.io/guide/creating-libraries to set up a whole new project and paste the component code
And I use "aot" https://github.com/andriyor/ngx-overlayscrollbars/blob/master/angular.json#L14
and also i use  use TypeScript path mapping for peer dependency
https://angular.io/guide/creating-libraries#use-typescript-path-mapping-for-peer-dependencies
https://github.com/andriyor/ngx-overlayscrollbars/blob/master/tsconfig.json#L36

**Comment by KingSora** [comment]
@andriyor @vdjurdjevic  I believe this bug should be fixed in the new `overlayscrollbars-ngx` version `v0.2.2`. Can you confirm it?

**Comment by andriyor** [comment]
Thank you Your project is awesome!
