### ISSUE TITLE
Make it work with DRAGSCROLL

### ISSUE THREAD

**Issue by buckelieg** [KingSora/OverlayScrollbars#142]
Make it work with [dragscroll](https://github.com/asvd/dragscroll) component. Or integrate it into this library. Would blow up the things!!

**Comment by KingSora** [comment]
Good day!

It's already possible to make it work with the `dragscroll` library. I've created a small demo for you [here](https://jsfiddle.net/3mey9dvo/) and [here](https://jsfiddle.net/3mey9dvo/1/) with grabbing mouse styles.

**Comment by buckelieg** [comment]
Thanks a lot!
