### ISSUE TITLE
IE11 Compatibility issue with vue scrollbars

### ISSUE THREAD

**Issue by whoisme555** [KingSora/OverlayScrollbars#143]
Hi! This scrollbar is working perfectly for my vue solution in chrome and firefox, but when testing in IE I'm running into an issue that I'm not sure is caused by my webpack/babel-loader configuration or by something else.

When removing the scoll bar component, the page loads okay, but with the scroll bar component I'm getting "Unable to set property 'render' of undefined or null reference" in normalize-component.js.

Without the scroll bar component, all my other components load fine, but with it, the whole vue page isn't rendering in IE11.

Any ideas?

**Comment by KingSora** [comment]
Good day!

I might have an idea, but I'm not sure. I'll release a new version soon, in which I'll also update the `vue` and any other wrapper. Maybe then your issue will be fixed. If not, well, I don't really know.

It could also be possible to be a `vue` issue with IE11, since it's only happening there. I can only request you to wait for the new version. Also sorry for the late reply, I injured myself last week and couldn't really find time to answer your issue.

**Comment by whoisme555** [comment]
I did a little additional digging using the live preview and it looks like the syntax error points to line 4 of overlayscrollbars-vue.esm.js - is it possible that OverlayScrollbarsComponent is missing an export?

**Comment by KingSora** [comment]
@whoisme555 alright, thanks to you I now know what the problem is! Vue is using the `esm` version of the plugin, but IE11 doesn't support `es6` syntax. To fix this, you have to tell Vue to use the normal `es5` (or `umd`) version. I didn't figure out how I can tell Vue to do that, but instead you can tell Vue to `transpile` the `es6` version.
To do that, you have to add this to your `vue.config.js` which should be located in the root folder of your project:

```js
module.exports = {
    transpileDependencies: ['overlayscrollbars-vue']
}
```

The `transpileDependencies` property should hopefully fix your problem, it fixed it at least on my end.

**Comment by whoisme555** [comment]
Maybe I'm reading this wrong, but since you're saying vue.config.js I assume you're using vue cli for this, my solution is currently using webpack cli and don't have a vue.config.js.  Any idea if webpack with babel supports this?  I can't seem to find info on a transpiledependencies option for my webpack config

**Comment by KingSora** [comment]
Yeah I used the vue cli for my setup. Well, thats unfortunate, but since you know the problem, maybe google can help you out. If not, please upload a small sample of your setup here or create a repo here on github. I'll then try to solve it.

**Comment by whoisme555** [comment]
You're legitimately a super hero!  Turns out you can just include/exclude certain paths with babel loader in the webpack config.  I'm including part of my webpack config for anyone interested that will follow your instructions to transpile the vue version for IE compatibility - 

```
module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules\/(?!(overlayscrollbars-vue)\/).*/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: [
                                "@babel/preset-env"
                            ],
                            plugins: [
                                "@babel/plugin-syntax-dynamic-import"

                            ]
                        }
                    }
                ]
            }
        ]
    }
```

**Comment by KingSora** [comment]
Very nice!! Thanks for sharing your solution :)

**Comment by nuria-gs** [comment]
@whoisme555 you just saved my day!!! I had the same issue with the overlayscrollbars-react and your solutions works perfectly. 

Thanks @KingSora & @whoisme555!!

**Comment by whoisme555** [comment]
> @whoisme555 you just saved my day!!! I had the same issue with the overlayscrollbars-react and your solutions works perfectly.
> 
> @KingSora Probably something to add on the documentation so it's easier to know how to make it work with webpack + babel as it's a quite common config.
> 
> Thanks @KingSora & @whoisme555!!

Glad we could help. Heads up though, last Friday I was running into some issues after adding babel transform runtime. Found out my slashes were backwards and it was transpiling the whole node_modules folder.  Change the regex to this so it's more system independent:

```
exclude: /node_modules[\\/](?!(overlayscrollbars-vue)[\\/]).*/,
```

After doing this my webpack.config became a little longer because I found other packages needed to be transpiled for IE and I had to add them individually

```
{
                test: /\.js$/,
                exclude: /node_modules[\\/](?!(overlayscrollbars-vue|bootstrap-vue|vue-context)[\\/]).*/,

                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            sourceType: "unambiguous",

                            presets: [
                                "@babel/preset-env"
                            ],
                            plugins: [
                                "@babel/plugin-syntax-dynamic-import",
                                "@babel/plugin-transform-runtime",
                                "@babel/plugin-transform-object-assign"
                            ]
                        }
                    }
                ]
            },
```

Note that everything worked fine (even with bootstrap-vue and vue-context) when I was using babel-polyfill. It only broke when I added transform-runtime, so only take what you need from this after updating the regex
