### ISSUE TITLE
How can I lock scrolling temporarily?

### ISSUE THREAD

**Issue by idtareq10** [KingSora/OverlayScrollbars#144]
is there a way to lock or disable scrolling temporarily?

**Comment by KingSora** [comment]
Good day!

Yes, you can change the `overflowBehavior` option in the needed axis to `hidden`:
```js
overflowBehavior : {
    x: 'hidden',
    y: 'hidden'
}
```

In case you need a example, let me know.

**Comment by KingSora** [comment]
I had some time left and created a example for you: https://jsfiddle.net/49hqp2fx/
