### ISSUE TITLE
Outline removed from textareas

### ISSUE THREAD

**Issue by Media-Evil** [KingSora/OverlayScrollbars#147]
```
outline: 0px none transparent !important;
```
Removing an outline with !important flag makes it more difficult to work around this.
Why not to leave this up to users discretion?

**Comment by KingSora** [comment]
Good day!

Thats competely intended. The correct way to style your textarea is to style the generated `.os-host-textarea` element in which the textarea is wrapped and **not** the textarea itself. I've written more about it [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/supportedelements)

**Comment by Media-Evil** [comment]
Yeah. It seemed ok at the first glance, before I decided to scroll it.
