### ISSUE TITLE
Autoscroll content with VUE component

### ISSUE THREAD

**Issue by x0xa** [KingSora/OverlayScrollbars#151]
Hello, how i can enable autoscrolling to the bottom while add new content in chat window?
It's possible with standart options?

```
<overlay-scrollbars
             class="scroll-chat"
             :options="{ 
                   scrollbars: { autoHide: 'never' }, 
                  autoUpdate: true, overflowBehavior:{x : 'scroll', y: 'scroll' } }"
            ref="scrollBar">
          <div class="row-chat" v-for="message in messages">
                <strong class="chat-nickname">
                     <a href="#">{{ message.username }}:</a>
                 </strong>
                 <span class="chat-message">{{ message.text }}</span>
                 <span class="chat-time">
                            {{ message.date.getHours() }}:{{ message.date.getMinutes() }}
                </span>
           </div>
           <div ref="endChat"></div>
</overlay-scrollbars>
```

Now i try scroll on message event:

`this.$refs.endChat.scrollIntoView()`

but it's not working for me

**Comment by KingSora** [comment]
Good day!

It's definitely possible, as there were related qestions in the past: #20 and #4. You have to get the `OverlayScrollbars Instance` from the VUE component, how this works you can read in the [documentation](https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-vue#instance). After that you can use the scroll method on any event like this: 
```
osInstance.scroll({ y : '100%' });
``` 
This will always scroll to the bottom. You can also check the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll) for the scroll method for more advanced scrolling effects, or [this example](https://jsfiddle.net/rq4xq5jf/6/) (it's not VUE but it does what you want in vanilla JS).

**Comment by KingSora** [comment]
@x0xa Did my answer work for you?
