### ISSUE TITLE
Multiple callbacks for specific events

### ISSUE THREAD

**Issue by poradz** [KingSora/OverlayScrollbars#154]
Hi, is it possible to listen to an event of one instance from many components? Right now it seems that there could be only one callback function, which one can overwrite.

For example: 
```
//scrollbar init
window.scrollbar = $('body').overlayScrollbars(mergedOptions).overlayScrollbars()
//one component
window.scrollbar.options({ callbacks: { onScroll: oneMethod } });
//another component
window.scrollbar.options({ callbacks: { onScroll: anotherMethod } });
```

PS Great project! 🎉

**Comment by KingSora** [comment]
Good day!

Well, the problem is that the callback is ment to be one function per instance. I may change / upgrade this in `version 2.0.0` (not sure though) but for now this will stay like that.

You could do something like this:
```js
//init
window.scrollbarOnScrollArray = [ ];
window.scrollbar = $('body').overlayScrollbars({
  callbacks: {
    onScroll : function(e) { 
      for(var i = 0; i < window.scrollbarOnScrollArray.length; i++)
        window.scrollbarOnScrollArray[i].call(this, e);
    }
  }
}).overlayScrollbars();
//one component
window.scrollbarOnScrollArray.push(oneMethod);
//another component
window.scrollbarOnScrollArray.push(anotherMethod);
```

**Comment by poradz** [comment]
Thanks, is solved my issue! 🎉

But emitting 'scroll' event still would be usefull, especially when other library is listening to it, for example lazy loading utilities as:

http://jquery.eisbehr.de/lazy/

Unfortunetally, currently overlay scrollbars can't work with them (as far as I know).

**Comment by KingSora** [comment]
Well, for this kind of stuff you can use the `viewport` element itself. OverlayScrollbars works with such libraries: http://jsfiddle.net/petu68ba/

Hopefully I helped you out :)

**Comment by poradz** [comment]
Since viewport element emits native events it solved all my problems. Thank you! 🎉🎉🎉

PS
It could be usefull to add more explicit information about native events, especially for developers implementing your library on existing projects or migrating from another library. Once more thanks!
