### ISSUE TITLE
Smooth scrolling to anchor-link

### ISSUE THREAD

**Issue by sass-ai** [KingSora/OverlayScrollbars#160]
Please tell me how through Your plugin you can make Smooth scrolling to anchor-link?

Before the plugin I used https://github.com/cferdinandi/smooth-scroll

But after installing Your plugin, the smoothness is gone because in the plugin
smooth-scroll is written: <body> element has been assigned height 100% or overflow: hidden, Smooth Scroll will not be able to correctly calculate the distance to the pages and will not scroll to the right place. 

I need to implement a smooth scrolling to the anchor link with an indentation on the top as I have a fixed header/nav on the site.

With that plugin, you can indent, now I do not understand how to do it, because I'm an Amateur in this field, if you can please write an example.

**Comment by KingSora** [comment]
Good day!

I've looked into your issue and unfortunately the mentioned library only supports the `window` element (e.g. `body` or/and `html` element) as its scrolling (viewport) element. If the author would provide a option to change that, `OverlayScrollbars` would work fine with the library. Maybe you could open a feature request on the project and they would implement it as this feature shouldn't be such a big deal in my opinion.

**Comment by KingSora** [comment]
I'll close this issue. In case you've related questions please don't hesitate to ask them!
