### ISSUE TITLE
Hi, author, does the plugin allow the same scrolling position to be retained when the page is returned as with the native scroll bar?

### ISSUE THREAD

**Issue by HellowWord123** [KingSora/OverlayScrollbars#161]
Hi, author, does the plugin allow the same scrolling position to be retained when the page is returned as with the native scroll bar?

**Comment by KingSora** [comment]
Hi!

I think that should be possible. Do you have a concrete example for me?

**Comment by KingSora** [comment]
I'll close this issue due to inactivity. I believe issue #29 is exactly what you need and you can find all information needed there. If you have questions or updates related to your issue please don't hestiate to write them!
