### ISSUE TITLE
Using the plugin on (or in) a positined element

### ISSUE THREAD

**Issue by carpben** [KingSora/OverlayScrollbars#162]
I tried embedding the scrollbar in a positioned fixed modal/popup, but it didn't work. In the "Flexbox" documentation it says: 

> The plugin was built to be used on "normal" elements,

Does it mean it won't work if one of the parents is positioned (position is not static)? 
Is there any way to solve this?

**Comment by KingSora** [comment]
Good day,

could you please create a small demo on jsfiddle or any other platform for me?
Thanks!

**Comment by KingSora** [comment]
@carpben Any update on this?

**Comment by KingSora** [comment]
@carpben I'll close this issue for now because of inactivity. In case you have any updates on this, please don't hesitate to reopen this issue.
