### ISSUE TITLE
Can you share the source of this demo? 

### ISSUE THREAD

**Issue by fzxa** [KingSora/OverlayScrollbars#163]
https://kingsora.github.io/OverlayScrollbars/#!demos/content

thx :)

**Comment by KingSora** [comment]
Good day!

Of course, you can find the source of this and all other demos here: https://github.com/KingSora/KingSora.github.io/blob/master/OverlayScrollbars/js/demos.js#L937-L1139

**Comment by fzxa** [comment]
> Good day!
> 
> Of course, you can find the source of this and all other demos here: https://github.com/KingSora/KingSora.github.io/blob/master/OverlayScrollbars/js/demos.js#L937-L1139

cool!
