### ISSUE TITLE
https://kingsora.github.io/OverlayScrollbars/#!documentation/options --> layout is broken in Chrome (newest version)

### ISSUE THREAD

**Issue by Legends** [KingSora/OverlayScrollbars#164]
![image](https://user-images.githubusercontent.com/966368/70528914-9c7c9c80-1b4f-11ea-9d66-6764fd728c9a.png)

**Comment by Legends** [comment]
Works fine in Edge.

**Comment by KingSora** [comment]
Good day!

I can't reproduce it on my end. Could you tell me your chrome version? Please also check you zoom level and tell me wether its 100%. Disabled all chrome plugins / add-ons in case you have some installed.

**Comment by Legends** [comment]
Yes, I just turned off Adguard and now it works. Didn't analyze what's the problem, because it doesn't block anything on your site.
