### ISSUE TITLE
Cannot seem to get the OverlayScrollbars working in RB4.0

### ISSUE THREAD

**Issue by michaelcuneo** [KingSora/OverlayScrollbars#165]
I have a React-Boilerplate project.

I've added  the OverlayScrollBarsComponent properly...

app.js

`import 'overlayscrollbars/css/OverlayScrollbars.css';`

index.js

```
import { OverlayScrollbarsComponent } from 'overlayscrollbars-react';

function App(props) {
  return (
    <React.Fragment>
      <OverlayScrollbarsComponent
        options={{
          className: 'os-theme-dark',
          scrollbars: {
            autoHide: 'scroll',
            clickScrolling: true,
          },
          nativeScrollbarsOverlaid: {
            showNativeScrollbars: false,
            initialize: false,
          },
          resize: 'both',
          sizeAutoCapable: true,
          paddingAbsolute: true,
        }}
      >

... REST OF THE APP ... 

      </OverlayScrollbarsComponent>
    </React.Fragment>
  );
}

```

Is there a default initial .css case that I should be using to have the scrollbars show up... i.e. in my global-styles.css import.

**Comment by KingSora** [comment]
Good day!

Everything you need to know about `overlayscrollbars-react` you can find in the corresponding [Readme](https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-react#css). There is also described how to import the necessary css.

**Comment by KingSora** [comment]
@michaelcuneo any updates here?

**Comment by michaelcuneo** [comment]
I will check what I've done since, and update this.

**Comment by KingSora** [comment]
@michaelcuneo I'll close this issue for now. In case you still need help with your issue or you have any updates on this, please don't hesitate to reopen this issue.
