### ISSUE TITLE
[Style Issue] drag-line is wider than trackbar (os-theme-block)

### ISSUE THREAD

**Issue by BennyAlex** [KingSora/OverlayScrollbars#169]
Hello, 
when using the os-theme-block-dark, the thin drag-line is wider than the actrual trackbar.
This only applies to the vertical scrollbar, but on both dark and light themes.

See screenshot or try the on the themes website:

![bug](https://user-images.githubusercontent.com/17402724/71363624-00fd1a00-259a-11ea-9919-f5f548807375.png)

**Comment by KingSora** [comment]
Good day!

Thanks, I've uploaded the fixed styles. Clear your cache or realod the page with ctrl+F5 and download the styles anew.

**Comment by BennyAlex** [comment]
Merry Christmas :)

thanks for the fix!

**Comment by KingSora** [comment]
Merry Christmas!
