### ISSUE TITLE
Detect direction of scroll after start

### ISSUE THREAD

**Issue by pollux4321** [KingSora/OverlayScrollbars#170]
How can I detect scroll direction after start? Like if I wanted to add a scroll to bottom button when the user scrolls up.

**Comment by KingSora** [comment]
Good day!

You have to track the past and current scroll position and compare it. I've created a simple [demo](https://jsfiddle.net/vc1hbun4/1/) for you.

**Comment by KingSora** [comment]
I'll close this issue for now, since I believe I've answered your question. If thats not the case and my example / demo isn't what you expected please don't hestiate to reopen the issue!
