### ISSUE TITLE
Is there anyway I can resize the width of the scroll handle?

### ISSUE THREAD

**Issue by Horlaes** [KingSora/OverlayScrollbars#173]
Hi, thanks for this great plugin, it is awesome.

Is there any way I can resize the width of the scroll handle, it is a little too thin for my use case, thanks!

PS - Happy New Year

**Comment by KingSora** [comment]
Good day!

Of course there is, you can adjust the design of the scrollbars completely in CSS. I've created a small demo for you where I've changed the width (for vertical) and height (for horizontal) scrollbars to `14px` (previously `10px`): https://jsfiddle.net/mpLnfbe1/

I've changed the design of the standard theme in the demo, but you can simply create your own theme. It's not that complicated, just read [this section](https://kingsora.github.io/OverlayScrollbars/#!documentation/styling) if you wanna know more.

Happy new year :)

**Comment by Horlaes** [comment]
Thanks a lot, it works. You are blessed!

**Comment by Horlaes** [comment]
It is a little bit on top of my content, see: https://prnt.sc/qi5rdb is there any way I can make it like this: https://prnt.sc/qi5rwd, you see how that pushes the div to the left side

**Comment by KingSora** [comment]
You can use the `paddingAbsolute` option, I've created a small showcase of this option the [FAQ](https://kingsora.github.io/OverlayScrollbars/#!faq) (4th question from the top).

**Comment by Horlaes** [comment]
Thanks KingSora, you are really a king. I wonder why GitHub doesn't notify me of new comments, anyways, You are awesome1

**Comment by KingSora** [comment]
@Horlaes Glad I could help you :)
