### ISSUE TITLE
Conflict with Divi Theme (anchor links)

### ISSUE THREAD

**Issue by elzadj** [KingSora/OverlayScrollbars#174]
Hello!

It looks like there is a problem when the OverlayScrollbars is used with the latest Divi Theme. 

The anchor links do not work at all. Here is an example: https://finance.dev600.com/scroll-test/
Click "This is a test link" - it's not working.

Can you help us debug the issue please?

**Comment by KingSora** [comment]
Good day @elzadj !

I've looked into it, and this happens, because the Divi theme propagates the `scroll command` to the `html, body` elements, but with `OverlayScrollbars` this changes and thats why it's not working.

If you have the possibility to change or adjust the Divi Theme, then change the code of the `et_pb_smooth_scroll` function to:

```javascript
window.et_pb_smooth_scroll = function($target, $top_section, speed, easing) {
        var $ = jQuery;
	var $window_width = $(window).width();
	$("body").hasClass("et_fixed_nav") && 980 < $window_width ? $menu_offset = $("#top-header").outerHeight() + $("#main-header").outerHeight() - 1 : $menu_offset = -1,
	$("#wpadminbar").length && 600 < $window_width && ($menu_offset += $("#wpadminbar").outerHeight()),
	$scroll_position = $top_section ? 0 : $target.offset().top - $menu_offset,
	void 0 === easing && (easing = "swing"),
	$("html, body, body.os-host > .os-padding > .os-viewport").animate({
		scrollTop: $scroll_position
	}, speed, easing)
}
```

**Comment by elzadj** [comment]
Thank you! I will contact Divi's Dev Team.

**Comment by KingSora** [comment]
@elzadj no problem.
You should describe the whole situation a bit more universal, for example they should provide a possibility for the user to customize the selector or the element which shall be scrolled and the default value is `html, body`.

**Comment by KingSora** [comment]
I'll close this issue for now. If you have any updates on this please don't hesitate to post them!
