### ISSUE TITLE
<div class="os-viewport ..."> is somehow focusable on Firefox

### ISSUE THREAD

**Issue by ianthedev** [KingSora/OverlayScrollbars#175]
The `<div class="os-viewport ...">` element is somehow focusable on Firefox, while it should not be. On Chrome, it is correctly unfocusable.

You could verify the issue on Firefox by executing the following code (taken from [here](https://hiddedevries.nl/en/blog/2019-01-30-console-logging-the-focused-element-as-it-changes)) and then using the <kbd>Tab</kbd> key to tab to the element.

```javascript
document.addEventListener('focus', function() {
  console.log('focused: ', document.activeElement)
}, true);
```

**Comment by KingSora** [comment]
Good day!

This isn't really a bug of the plugin, but this happens due to how firefox handles elements with `overflow`. On Firefox they can always receive focus. I've created this fiddle: https://jsfiddle.net/y3t8mwz0/ to confirm my explanation. Run it on Firefox and chrome and check the console.

**Comment by ianthedev** [comment]
I see! Thank you for explaining.

**Comment by ianthedev** [comment]
Considering that sometimes there are keyboard users (e.g. laptop users and screen reader users), it would be great if the element could be unfocusable on Firefox.

**Comment by KingSora** [comment]
You could try the following:

```js
OverlayScrollbars(document.querySelector('...'), { 
   callbacks: {
      onInitialized: function() {
         this.getElements().viewport.setAttribute('tabindex', '-1');
      }
   }
});
```

**Comment by ianthedev** [comment]
Thank you. Setting `tabindex="-1"` does make the element unfocusable for keyboard navigation, though it also makes the element become focusable for mouse clicks. The latter effect probably is not a problem. I will think about it.

**Comment by KingSora** [comment]
Related Issue: https://github.com/KingSora/OverlayScrollbars/issues/153
