### ISSUE TITLE
Horizontal scroll not working

### ISSUE THREAD

**Issue by vonmaster** [KingSora/OverlayScrollbars#176]
Hi,

First of all, thank you for this incredibly useful library. I am trying to make an horizontal scrollable Bootstrap row.

With CSS, it is working fine: https://jsfiddle.net/von_master/pa612hvd/
But once I add OverlayScrollbars, it is not working: https://jsfiddle.net/von_master/pa612hvd/1/

I examined all options, but nothing worked. For me, the culprit is the property `flex-direction: column` of the class `.os-host`. I would be grateful if someone could help me identify and solve this issue.

**Comment by KingSora** [comment]
Good day!

This is some complicated styling, but I believe `OverlayScrollbars` should handle it:
https://jsfiddle.net/wxy30dhL/

**Comment by vonmaster** [comment]
Thank you very much for your help! It worked.
