### ISSUE TITLE
Reference Error: previousOverflow is not defined

### ISSUE THREAD

**Issue by nickensoul** [KingSora/OverlayScrollbars#178]
[There a line](https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L4001) where a variable `previousOverflow` is used to access its `y` property, but there is not such variable.
BTW, it exists in 1.10.0 version. please, fix this, if I'm right! Or, if I'll have a time, I could check this again and create a PR.
Thanks!

**Comment by KingSora** [comment]
Thanks, I'll fix it as fast as possible!

**Comment by KingSora** [comment]
The bug is now fixed in `version 1.10.3`:https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.10.3
