### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by tavo379** [KingSora/OverlayScrollbars#179]
Is there any way to add smooth scrolling? something similar to what this library does https://idiotwu.github.io/smooth-scrollbar/

**Comment by KingSora** [comment]
Good day!

Well... it depends. Since I'm using the native scrolling mechanism of the browser, you have to implement it yourself based on that. Your mentioned library uses CSS transformations to achieve it's smooth scrolling. That wouldn't (or only with very much effort) be possible here.

**Comment by KingSora** [comment]
I'll close this issue for now. In case you have further questions, please don't hesitate to ask!
