### ISSUE TITLE
Getting overlay scrollbar information on vue

### ISSUE THREAD

**Issue by Prixus** [KingSora/OverlayScrollbars#181]
Need to get the scrollbar info in my vue component. I am using SFC

**Comment by KingSora** [comment]
Good day!
Please provide more information. A codeexample would be also very useful!

**Comment by Prixus** [comment]
Thank you for your reply. I need to to listen to an event and trigger an action when the user reaches the end of the overlay scrollbar container

`    <overlayScrollbars :options="{ callbacks : {onScroll : this.checkLazyLoad} }">
     ...
    </overlayScrollbars>`

I need to make my checkLazyLoad function to do the following:

1. Get the recent the recent scroll information in vue. 
2. After getting the recent scroll information I need to trigger an event if the scrollbar reached the end of the container

**Comment by KingSora** [comment]
Recently I solved a similar issue. Please check #177 maybe it'll help you. If not please let me know, I'll make a example for you.

**Comment by Prixus** [comment]
The issue has been resolved.  Based from the comment above.
