### ISSUE TITLE
React-JSS styles aren't injected on componentDidMount in class components

### ISSUE THREAD

**Issue by sabotag** [KingSora/OverlayScrollbars#182]
I try work with overlayScrollbars on componentDidMount lifecycle, but I have some trouble

if I get osInstance on componentDidMount I dont have actual information(data) 
but if I wrap it in timeout I get actual information

Example: 
- I cant use `scroll({y: '100%'})`
- or this.ref.current.osInstance.scroll().max.y

```constructor( props ) {
    super( props );

    this.state = {
      message: '',
    };

    this.textAreaRef = React.createRef();
    this.osRef = React.createRef();
  }

  componentDidMount() {
    const osInstance = this.osRef.current.osInstance();
    const scroll = osInstance.scroll();

    if ( scroll.max.y === 0 ) {
       // always scroll.max.y === 0 
    }

    // overlay scroll not worked  #without timeout for some reason
    this.timeout = setTimeout( () => {
      // scroll.max.y === contentHeight
      // and scroll are scroll to bottom
      osInstance.scroll( { y:  '100%' } );
    }, 0 );
  }

render() {
  return (
    <OverlayScrollbarsComponent
            className='os-theme-dark'
            style={{ height: '100%', }}
            ref={this.osRef}
            options={{
              scrollbars: { autoHide: 'leave', },
              callbacks: {
                onScroll: this.onScroll,
              },
            }}
          >
            <div className={classes.messages}>
              {data.map( ( m, k ) => (
                <div
                  key={`${m.get( 'id' )}-${k}`}
                >
                  <div
                    className={classes.messageBody}
                  >
                    <div className={classes.messageText}>{m.get( 'content' )}</div>
                  </div>
                </div>
              ) )}
            </div>
          </OverlayScrollbarsComponent>

)
}
```

**Comment by KingSora** [comment]
Good day!

Could you create a example online? I tested it here: https://codesandbox.io/s/frosty-morning-ilho1 and the max position is correct.

**Comment by sabotag** [comment]
> Good day!
> 
> Could you create a example online? I tested it here: https://codesandbox.io/s/modest-dewdney-5ekfl and the max position is correct, it also scrolls to the bottom. 

I found why the instance shows false values!
Pls, check example and check console when you scroll, you see that `max.y` another

OS calculate wrong data because I use `react-jss` and dont include styles when initialize
I can't understand why, if you delete styles from `sheet.js` OS work correctly

**Comment by KingSora** [comment]
@sabotag Is it possible that you forgot to post the url of your example?

**Comment by sabotag** [comment]
> @sabotag Is it possible that you forgot to post the url of your example?

sorry)

[https://codesandbox.io/s/sweet-edison-nvpb4]

**Comment by sabotag** [comment]
Also, I try solution with react hooks and use hooks from `react-jss`
And its work correctly, but I still dont understand why its wont work with `react-jss` wrapper

[example with react-hooks and react-jss](https://codesandbox.io/s/lucid-keldysh-sfmqx)

**Comment by KingSora** [comment]
I've looked into it, and the reason is clear for me. In your `class Component` example the styles for the items aren't injected during the initialization of OverlayScrollbars. They also aren't injected at the time `componentDiMount` is called, thats why the numbers look wrong to you, but they are actually correct for this point in time.

In your `react hooks` example the styles are already injected before OverlayScrollbars initializes and thats why its working.

**Comment by sabotag** [comment]
> Check the console in both examples, I log the height of the first children element at the time `componentDidMount` gets called and 500ms after that. As you can see in the `class Component` the values differ, so the styles aren't injected at this point.

Do have any ideas how to use `class Component` and `react-jss` inject/wrapper together with OverlayScrollbars or its better ask `react-jss` developers ? :)

**Comment by KingSora** [comment]
Its definitely better to ask a `react-jss` developer. They 
- have to provide a way, where you know when exactly the styles are injected. If you know that you can react to that.
- have to make somehow sure the styles are already injected at the point in time `componentDidMount` gets called.

**Comment by KingSora** [comment]
@sabotag I'll close this issue for now. In case you've any updates you want to share, please don't hestiate to write them here :)
