### ISSUE TITLE
Make imgOnLoad functionality optional

### ISSUE THREAD

**Issue by treechime** [KingSora/OverlayScrollbars#183]
I'm building a very image dense display site using OverlayScrollbars with custom horizontal scrolling. Due to the nature of the layout all of the images have fixed dimensions even prior to loading, so this imgOnLoad functionality is totally unnecessary in my case and actually causes a huge amount of lag on page initialisation. I've commented all references to the function out in my local copy of the js file and performance has improved significantly.

Just a suggestion for enhancement 🍐
Love the plugin by the way. Super useful!

**Comment by KingSora** [comment]
Good day!

Thats a good idea, previously it was planned to make this functionality optional, but since nobody has mentioned it until now I've completely forgotten about it.

Thanks for this!

**Comment by treechime** [comment]
Thanks! 😁

**Comment by KingSora** [comment]
This is now implemented in [v1.12.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.12.0)! Set the `updateOnLoad` to `null` to remove any automatic updates on a `load` event.
