### ISSUE TITLE
Site Elements Don't load In correctly

### ISSUE THREAD

**Issue by cosmokid** [KingSora/OverlayScrollbars#185]
The custom scrollbar works fine, but the CSS(?) file for it is causing the rest of the site to act weird (like doesn't load content in unless you go full screen or slightly resize the window)

No errors reported from developer tools.

**Comment by cosmokid** [comment]
I have added a video to show.

[https://streamable.com/h6b61](url)

**Comment by KingSora** [comment]
Good day!

I've closed #186, you probably opened it twice by mistake.
In your case it looks like you've implemented it somehow incorrectly, can I check it with a live example? You can send it to me via email which you can find on my profie if you don't want to post it here publicly.

**Comment by KingSora** [comment]
I'll close this issue because of inactivity as well, if you have any feedback, please don't heistate to reopen the issue.
