### ISSUE TITLE
easing support

### ISSUE THREAD

**Issue by pankyka** [KingSora/OverlayScrollbars#19]
Hi,
Is there any plan to support easing?
Thanks!

edit:
I found it :-) 
https://kingsora.github.io/OverlayScrollbars/#!demos/scroll

**Comment by KingSora** [comment]
Hi!

If you are using the jQuery version I recommend to adapt these easings: [here](http://gsgd.co.uk/sandbox/jquery/easing/), so you have all kind of fancy easings.
If you are using the dependencyless version all the easings are included.

Have fun with the plugin :)
