### ISSUE TITLE
How to configure scrollbars to "fade and disappear" when not in-use?

### ISSUE THREAD

**Issue by Eric24** [KingSora/OverlayScrollbars#192]
One of the most appealing features of https://idiotwu.github.io/smooth-scrollbar is that it works like iPad scrollbars (i.e. scrollbars only become visible when they are active--during scrolling or when the mouse pointer is over the scrollbar area). Is there a way to accomplish this with OverlayScrollbars?

**Comment by KingSora** [comment]
Good day!

Yes, you can use the `autoHide` option for this:
```
OverlayScrollbars(document.body, { 
  scrollbars: {
    autoHiden: 'move'
  }
});
```
If you wanna know more about this or the other options, please take a look at the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/options).

**Comment by Eric24** [comment]
Ah, perfect! I didn't see that when I first read through the docs. Thanks for the quick response!

**Comment by KingSora** [comment]
Glad I could help :)
