### ISSUE TITLE
not working with react Material-UI

### ISSUE THREAD

**Issue by jamalcoder** [KingSora/OverlayScrollbars#193]
not working with react Material-UI as the topic says

**Comment by KingSora** [comment]
Good day!

Could you please create a example on [Stackblitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) so I can investigate on this?

**Comment by jamalcoder** [comment]
hi @KingSora 
[https://codesandbox.io/s/material-demo-dtn61](url)

**Comment by KingSora** [comment]
Thanks! You have to apply the `root` styles directly to the `OverlayScrollbarsComponent`. But I've realized, that the current implementation has struggles with hooks, so you have to go with this solution: https://codesandbox.io/s/material-demo-h570n until I've fixed the react wrapper.

**Comment by jamalcoder** [comment]
thank you....waiting for update because it's issues with other components

**Comment by KingSora** [comment]
@jamalcoder I'll try to update it this week :)

**Comment by KingSora** [comment]
This is now updated in the newest `overlayscrollbars-react` version (`v0.2.2`).
