### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by kodjo49** [KingSora/OverlayScrollbars#194]
Very good work.

Here you can found customizable Splash Screen for web app ([js-splash](https://github.com/koffiisen/js-splash)) :

https://github.com/koffiisen/js-splash 

😉

**Comment by FSDRE** [comment]
@kodjo49 Is GitHub also finally turning into an advertising platform? That's pretty sad 😞

**Comment by kodjo49** [comment]
Sorry. 
I saw that you were doing animation when loading the page, that's why I offer you js-splash

Good day

**Comment by KingSora** [comment]
@kodjo49 Thanks for your kind words! In case I'll need the functionality your plugin offers, I'll come back to you :)
