### ISSUE TITLE
Very weird bug on chrome

### ISSUE THREAD

**Issue by apuntovanini** [KingSora/OverlayScrollbars#199]
Hi, thanks for this great library. I encountered a weird bug using Chrome, I'll try to explain
I use the react-wrapper, and this is the html output: 

![Schermata 2020-04-03 alle 10 23 19](https://user-images.githubusercontent.com/1159781/78339691-2c2dd700-7595-11ea-8324-5382a6aa7544.png)

So far so good. Since the container is a flex element, I added some styling
```css
display: flex;
flex: 1;
min-width: 0; 
```

which is basically what's contained in os-host-flexbox (unless I missed something).

I use a double monitor: my retina macbook pro and a samsung HD. Why does it matter? I don't know, scrollbars work perfectly in Safari and in Firefox, but in Chrome, even if scrollbar is properly initialized and sized (and works dragging the scrollbar handling), mouse-scrolling is disable on the non-retina screen only. 🤔 I hope I made myself clear enough
I thought it was something related to DPI, but `getWindowDPR` works.

![Schermata 2020-04-03 alle 10 32 33](https://user-images.githubusercontent.com/1159781/78340523-8aa78500-7596-11ea-8224-4eb2507f241e.png)

Thanks for your support!

**Comment by KingSora** [comment]
Good day!

Thats indeed strange, could you send me the page you are using OverlayScrollbars in? If you don't want it to be public here, you can also send me an email (you can find my e-mail address on my profile page).

**Comment by apuntovanini** [comment]
Sure, here's a deploy preview: https://5e86fb55db6346c22dc906ed--guidu.netlify.com/

**Comment by KingSora** [comment]
I've figured out the problem, you are using the css property `overscroll-behavior-y: contain;`, if you remove this rule on the child, it works normally again.

**Comment by apuntovanini** [comment]
Indeed, it does, thanks . But in mobile (Safari or chrome) scrolling
doesn’t work...any ideas? Thanks for the quick answer!

Il giorno ven 3 apr 2020 alle 11:54 Rene Haas <notifications@github.com> ha
scritto:

**Comment by KingSora** [comment]
Honestly, I don't know whats wrong with your page on mobile... but it looks weird. Try to set the `display` of the `.os-content` to `flex` and also make sure that the div inside the `.os-content` div has `overflow-y: visible`.

**Comment by apuntovanini** [comment]
Now it seems close to what happens in #195, I'll try to disable touch support and then to add styles as you suggested. Thanks for your support

**Comment by apuntovanini** [comment]
Ok, I may have found it: we used `body-scroll-lock` in the inner content, to block body rubberband in ios (or clients who don't support `overscroll-behaviour`), we probably need to move it up to `OverlayScrollbarsComponent`. I tried with osTarget, but this isn't the scrollable element, so it doens't work. We'll see if we can safely drop `body-scroll-lock` or to find a workaround, it's a specific use case I know, but if you have any ideas and willing to share, we'll be grateful!
Thanks!

**Comment by KingSora** [comment]
You can apply it to the `viewport` element. You can get the viewport element like this:

```js
osInstance().getElements().viewport
```

**Comment by apuntovanini** [comment]
It works! How amazing, thank you very much!

**Comment by apuntovanini** [comment]
I guess this can be closed, I added some info about ios13 in the linked issue, thank you!

**Comment by KingSora** [comment]
Glad I could help! :)
