### ISSUE TITLE
Package Manager support

### ISSUE THREAD

**Issue by srtab** [KingSora/OverlayScrollbars#2]
Would be very useful integrating the plugin with a package manager like NPM or Webpack.

**Comment by KingSora** [comment]
Alright, I will take a look on that!

**Comment by KingSora** [comment]
Small update here:

I've decided to first create a jQuery independent version of this plugin an then provide a npm (and other package managers) package for both versions. 
The jQuery-less version is to 80% complete.

Thank you for your patience!

**Comment by buhuo00** [comment]
expectation

**Comment by KingSora** [comment]
Alright!

A new version is out and the NPM support is here: https://www.npmjs.com/package/overlayscrollbars
You can also check the [README](https://github.com/KingSora/OverlayScrollbars/blob/master/README.md) or [documentation](https://kingsora.github.io/OverlayScrollbars/#!overview).

Once again thank you for your patience!
