### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by SoftCreatR** [KingSora/OverlayScrollbars#20]
I just tried to implement this script in my existing structure.

There's a div container, that is dynamically being filled with contents. It has a max-height of 500px:

```
<div class="container">
	<div class="innerDivA" style="display: block;">
		<!-- foo -->
	</div>
		
	<div class="innerDivB" style="display: block;">
		<!-- foo -->
	</div>
</div>
```

As soon as i execute your script on the container div, it becomes this:

```
<div class="container os-host os-theme-dark os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-scrollbar-vertical-hidden os-host-transition">
	<div class="os-resize-observer-host">
		<div class="os-resize-observer observed" style="left: 0px; right: auto;">
		</div>
	</div>
	<div class="os-size-auto-observer" style="height: calc(100% + 1px); float: left;">
		<div class="os-resize-observer observed">
		</div>
	</div>
	<div class="os-content-glue" style="width: 252px; margin: 0px -5px 0px 0px; height: 501px;">
	</div>
	<div class="os-padding">
		<div class="os-viewport" style="right: 0px; bottom: 0px;">
			<div class="os-content-arrange">
			</div>
			<div class="os-content" style="padding: 0px 5px 0px 0px; height: auto; width: 100%;">
				<div class="innerDivA" style="display: block;">
					<!-- foo -->
				</div>
				<div class="innerDivB" style="display: block;">
					<!-- foo -->
				</div>
			</div>
		</div>
	</div>
	<div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable">
		<div class="os-scrollbar-track os-scrollbar-track-off">
			<div class="os-scrollbar-handle" style="width: 100%; transform: translate(0px, 0px);">
			</div>
		</div>
	</div>
	<div class="os-scrollbar os-scrollbar-vertical os-scrollbar-unusable">
		<div class="os-scrollbar-track os-scrollbar-track-off">
			<div class="os-scrollbar-handle" style="height: 100%; transform: translate(0px, 0px);">
			</div>
		</div>
	</div>
	<div class="os-scrollbar-corner">
	</div>
</div>
```

This results in an empty container directly before the element with a height of 501px (or whatever is being calculated). The scrollbar remains the system default one and i have two scrollbars now (the one from the element itself due to `overflow-y: auto;` and another one, that belongs to your plugin):

![image](https://user-images.githubusercontent.com/81188/37994729-b3403404-3212-11e8-950c-27b64baab682.png)

I just checked your recent issues and found #4 where you also posted a demo (https://jsfiddle.net/rq4xq5jf/1/). There, it also seems not to work as it should and i guess, it's the same problem.

**Comment by SoftCreatR** [comment]
Okay, after some fiddling it seems to be just a CSS issue. I'll close this issue for now and try to find the problem on my end.

**Comment by KingSora** [comment]
Good day!

It's possible that previous examples in previous issues aren't working because the path to the Javascript or CSS file (external ressources) has changed. If refresh the external ressources on this example: https://jsfiddle.net/rq4xq5jf/6/ it's working correctly again.

Your issue seems like you've forgot to implement the CSS file into your page. (Please load the CSS file before the JS file to prevent any bugs.)

**Comment by SoftCreatR** [comment]
Thank you. You are right and I just found this out myself shortly after posting this issue 😅

**Comment by KingSora** [comment]
Everyone is making mistakes, I'm glad everything is working now :)

**Comment by Tchomasek** [comment]
I have the same problem as [SoftCreatR](https://github.com/SoftCreatR), but i can't figure out what the problem is. Can you please explain?

**Comment by KingSora** [comment]
@Tchomasek please open a new issue with ypur details and a minimal example :)
