### ISSUE TITLE
Scrolling Behaviour for block content with margin (Chrome only)

### ISSUE THREAD

**Issue by FSDRE** [KingSora/OverlayScrollbars#202]
This works on Firefox and Edge-Edge (not Chromium-Edge).
Fails in Chrome or Chromium Browsers.

If you put a div with `display: block` and margin on all sides into the scroller, the margin on the right does not have any impact on the horizontal scrollbar.

If you make the div `display: inline-block` it works as expected.

Reproduce here:

https://stackblitz.com/edit/angular-ebiji1

Overlay Scrollbars version does not matter. Tried 1.10.2 up to 1.12.0

**Comment by KingSora** [comment]
Good day!

I'm afraid this isn't a bug related to the plugin, but a browser behavior. Chrome is handling margin on a overflowing side differently than other browsers. To prove this, I've pasted the same DOM just without OverlayScrollbars below, and the behavior is still the same: https://stackblitz.com/edit/angular-5fw3xw?file=src/app/app.component.html

**Comment by FSDRE** [comment]
Interesting! Could have checked that first 😄

**Comment by KingSora** [comment]
@FSDRE another thing I've noticed is, that the calculated scrollbar width is wrong on your example. And I've just found the issue. OverlayScrollbars is requiring its CSS file to calculate everything properly. You are importing the CSS file like this: 

```css
@import url('../node_modules/overlayscrollbars/css/OverlayScrollbars.css');
```

Which results in a async call, and thus the CSS file isn't there when the scrollbar width (and other things) are calculated. This results in incorrect behavior. Please import the CSS like this instead:

```css
@import '~overlayscrollbars/css/OverlayScrollbars.css';
```

To prevent such issues.

**Comment by FSDRE** [comment]
Oh I know, but StackBlitz had a bug a couple of weeks back where the `'~` was interpreted wrong. Good to know that it works again.
