### ISSUE TITLE
Non Overlayed Track

### ISSUE THREAD

**Issue by jibberishclient** [KingSora/OverlayScrollbars#204]
I'd like to make my MUI tables noWrap and allow horizontal scrolling once the table cells collapse on one another like so:

https://codesandbox.io/s/practical-herschel-1h0p2?file=/src/App.js

Obviously as the package name suggests, it's an overlayed scrollbar but is there a way to configure options such that the scrollbar won't overlay on the last table row, instead creating a track just beneath it?

**Comment by KingSora** [comment]
Good day!

Yes thats possible, you can use the `paddingAbsolute` option, and set a padding bottom if the container has a overflow. To know whether the container has a overflow you can use the `onOverflowChanged` callback with its arguments which contains that information. I've created a simple example for you: https://codesandbox.io/s/relaxed-forest-u6nm6

If you wanna know more about the options or callbacks with its arguments you can read the documentation here: https://kingsora.github.io/OverlayScrollbars/#!documentation/options

**Comment by jibberishclient** [comment]
On second, thought is there a cross browser way to visually hide all scrollbars in the app. I'm trying to give it that responsive mobile look and feel without jarring scrollbars popping in and out of the UI. Also would like to avoid using the component on every instance of overflow and just set it globally.

**Comment by jibberishclient** [comment]
So is there a way to make really really thin scrollbars? That behave like mobile scrollbars for all platforms and browsers?

**Comment by KingSora** [comment]
Everywhere where you want OverlayScrollbars to be active, you have to use the component. There isn't a magic way to somehow activate it everywhere where a overflow is, thats simply impossible (not impossible but expensive and not recommended) to detect. Simply use the component whereever you need it. The plugin was optimized for multiple instances in one page.

There is also a way for thin scrollbars. Simply style them as you want. Styling isn't hard or complex, you can read more about it in the documentation [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/styling).
