### ISSUE TITLE
Bottom padding is missing

### ISSUE THREAD

**Issue by ianthedev** [KingSora/OverlayScrollbars#206]
The following jsFiddle demo intends to have 30px padding inside the scrolling area. The top, right, and left paddings are implemented correctly. But the bottom padding isn't being implemented.

https://jsfiddle.net/IanY/spn6mvh5/3/

**Comment by KingSora** [comment]
Good day!

Unfortunately this is something which I can't really fix. In Firefox you have this behavior even with the native scrollbars: https://jsfiddle.net/7ndjy49c/

You could use the `paddingAbsolute` option to work around this behavior: https://jsfiddle.net/hLa8ytze/

**Comment by ianthedev** [comment]
Thank you for the prompt reply. `paddingAbsolute` can be a solution when the elements inside the scrolling area does not have CSS `box-shadow`, which would be cut-off by the `.os-viewport` element. Unfortunately, some of my elements have `box-shadow`.

I will use the last element's bottom margin to mimic the missing bottom padding of the scrolling area then.
