### ISSUE TITLE
Allow specifying offset of scrollbar

### ISSUE THREAD

**Issue by benmajor** [KingSora/OverlayScrollbars#208]
This may relate to a very small use case, but I still think that it would be a nice feature to add to this fantastic library nevertheless.

I am using OverlayScrollbars at the moment in a pane layout that has been designed using flexbox. Sometimes, these panes will contain a table that has a sticky header (achieved using `position: sticky` on the `th` elements). The scrollbars are added and work as expected, however, as is native behaviour, the scrollbar (and thus trackbar) starts at the top of the element. As a result, the initial scroll includes the space allocated for the sticky header.

It would be nice if we are able to specify an offset for the scrollbar, so that we can effectively ignore the first X pixels of an element. Here's a screenshot showing how they appear OOB, and another demonstrating how it should look with the offset implemented.

**Before:**
![screen](https://i.imgur.com/AFm1n6e.png)

**After:**
![screen](https://i.imgur.com/lJ7PlgX.png)

It would be nice if the offset could be specified in the `options` parameter, perhaps something like:

```javascript
{
  offsetX: 30,
  offsetY: 0
}
```

Currently, we are able to force the offset after initialisation by simply changing the CSS `top` rule of `.os-scrollbar-vertical` element (or similarly the `left` rule of the `.os-scrollbar-horizontal` element).

**Comment by KingSora** [comment]
Good day!

In the design process of this plugin I was very careful to separate CSS and JS. So everything which has to do with styling shall be solved with CSS and everything else with JS. Thats also the reason why you can adjust the max and min size of the scrollbar-handles in CSS and not inside of the options in JS.

Your case is pretty similar, I would solve it with the styling capabilities the plugin provides. There is even a example in the documentation [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/styling) with the sub-heading "Scrollbar position and length".

The solution I would go with in your case would look like this:

1. Decide a name for the class / theme which shall handle your style, as example I use the name `offset-top-scrollbars` and make the CSS rule: 
```CSS
.offset-top-scrollbars > .os-scrollbar-vertical {
    top: 30;
}
```
2. Initialize the `OverlayScrollbars` instance with your theme and use "Theme inheritance" as described in the documentation link above to also use the default theme called `os-theme-dark`.
```JS
OverlayScrollbars(/* your element */, {
    className: "os-theme-dark offset-top-scrollbars" 
});
```
This way you have the full advantages of CSS (like using percentage values, calculations etc.).

**Comment by benmajor** [comment]
Thanks for the reply! I think that separating the concerns was a very good choice, and I have to say that using the CSS directives to control the element makes perfect sense. 

I'll go ahead and close this issue now, but thanks for the explanation and great work!

**Comment by KingSora** [comment]
Glad I could help :)
