### ISSUE TITLE
Width calculation is wrong when there is no overflow

### ISSUE THREAD

**Issue by vdjurdjevic** [KingSora/OverlayScrollbars#209]
Hi, I have some weird behavior with library using React adapter. Below is an explanation with screenshots.

I have a grid layout with a column template auto 1fr auto. My scrollable element is in the middle. Inside the scrollable element, I have expansion panels each having number of cards. When all panels are collapsed, the element width is good. Here is a picture: 
![image](https://user-images.githubusercontent.com/17208031/80163083-4fb4d200-85d5-11ea-9719-2c7ae79460d4.png)

Now, if I expand the last panel which fits in the viewport (not causing overflow), width increases for some reason. Here is a picture (notice how the third column is clipped): 
![image](https://user-images.githubusercontent.com/17208031/80163174-97d3f480-85d5-11ea-95d2-dbdfef43c623.png)

And if I expand two panels, there is enough content to cause overflow, everything is ok. Here is a picture: 

![image](https://user-images.githubusercontent.com/17208031/80163243-dcf82680-85d5-11ea-8fa4-be6819761e0f.png)

Any ideas why is this happening?

**Comment by vdjurdjevic** [comment]
If i wrap expansion panels with div instead of OverlayScrollbarsComponent, everything works fine.

**Comment by KingSora** [comment]
Could you please send me your page or create a example on CodeSandbox or Stackblitz? That would make it much more easy to find a solution.

**Comment by vdjurdjevic** [comment]
I can add you as a collaborator to my private repository if you want to take a look. I am extremely busy now, can't create a reproduction repository.

**Comment by vdjurdjevic** [comment]
I added you to my repository. Relevant code is located at app/modules/ordering/layout/wide.tsx. You will see PanelScroll and PageScroll components, they are just wrappers for OverlayScrollbarsComponent to apply custom styling. You can change that to OverlayScrollbarsComponent, you will have the same behavior. I will be at my office for the next 6-8 hours, so If I can help, feel free to contact me. We can even make a zoom call or something similar and try to solve it together. Thanks :)

**Comment by vdjurdjevic** [comment]
@KingSora I have found a workaround for this. Instead of using 1fr on grid container, I use minmax(0, 1fr). And it works fine now. I will leave you with repo access anyways if you want to investigate this.

**Comment by KingSora** [comment]
@vdjurdjevic I've cloned your project and it seems like something is missing since the content in the ordering page is just "Meals".

**Comment by vdjurdjevic** [comment]
Swith to scrollbar-bug branch

**Comment by KingSora** [comment]
Alright, this is happening because you're applying `OverlayScrollbars` directly to a Grid child. The plugin isn't aware of that (basically the same problem as with `flexbox`, but with `grid`) and so it sets incorrect flags internally. The reason of why it is expanding is because it thinks that its `width` isn't fixed and so it expands when more content gets loaded. You can also check that with calling `getState()` on the instance and then checking the value of `widthAuto` prop of the returning object.

Since you already found a workaround already you can stick with that. My suggestion would be to use a wrapper div as you worte it [here](https://github.com/KingSora/OverlayScrollbars/issues/209#issuecomment-618961952).

**Comment by vdjurdjevic** [comment]
Ok, thanks for your time and this library :) Can I revoke access now?

**Comment by vdjurdjevic** [comment]
Hey, I have noticed one more thing. It would be great if you take a look. Try to expand all panels, and collapse only last. Some weird animation glitch happens. And it only happens with last. If you collapse the middle one, everything is ok.

**Comment by KingSora** [comment]
@vdjurdjevic this also happens without OverlayScrollbars.
You can test this by replacing this:
```js
<PageScroll {...mainScrollProps}>
    <OrderingLayoutContent>{children[1]}</OrderingLayoutContent>
</PageScroll>
```
with this:
```js
<div style={{ overflow: 'auto', height: '70vh' }} {...mainScrollProps}>
    <OrderingLayoutContent>{children[1]}</OrderingLayoutContent>
</div>
```

**Comment by vdjurdjevic** [comment]
Hm, it's expansion panel problem then. Thanks, I will take a look at it :)

**Comment by vdjurdjevic** [comment]
@KingSora There are definitely some issues with overlay scrollbars... I've noticed that in firefox expansion animation is laggy (noticeable). So I switched to div with overflow: auto and animation is smooth heaven with last expansion panel. In chrome, lag is not that bad, but in firefox is noticeable. And i checked, all other animations work fine (hamburger menu for example), and also native scrolls work fine.

**Comment by KingSora** [comment]
Well... thats weird because on my end it looks quite similar. I've attached two videos to show you how it looks on my end.
[Videos.zip](https://github.com/KingSora/OverlayScrollbars/files/4532692/Videos.zip)

**Comment by vdjurdjevic** [comment]
Ok, you can close this issue as far as I am concerned. Thanks :)

**Comment by KingSora** [comment]
Alright, glad I could help you! :)
