### ISSUE TITLE
Horizontal scrolling with wheel

### ISSUE THREAD

**Issue by christophe-glanum** [KingSora/OverlayScrollbars#211]
Is it possible to add the possibility of scrolling horizontally with the wheel?

Thank you.

**Comment by KingSora** [comment]
Good day!

Yes, its possible, but you have to implement it by yourself as you would do with a native element. I've create a example in #136 (https://jsfiddle.net/2sfaryb1/).

**Comment by christophe-glanum** [comment]
Thank you !
