### ISSUE TITLE
By introducing this component, I could not see any effect in the project， why?

### ISSUE THREAD

**Issue by PachVerb** [KingSora/OverlayScrollbars#213]
I'm using this component through the vue framework and using the global registry, and I'm using this scrollbar component in my project component and I'm not getting any results. Does it still need to be real column as the website says

![image](https://user-images.githubusercontent.com/43908467/80859767-cf0d6a00-8c95-11ea-88b9-cfbcbf892567.png)

![image](https://user-images.githubusercontent.com/43908467/80859776-da609580-8c95-11ea-83af-de45204c7868.png)

**Comment by KingSora** [comment]
Good day!

I guess you aren't restricting the component in size. It's the same as with a div with `overflow: auto`, when you don't add for example `height: 200px` or `max-height: 200px` the overflow will never be visible, because the div will always grow with its content.

**Comment by PachVerb** [comment]
> Good day!
> 
> I guess you aren't restricting the component in size. It's the same as with a div with `overflow: auto`, when you don't add for example `height: 200px` or `max-height: 200px` the overflow will never be visible, because the div will always grow with its content.

thank you , i got it
