### ISSUE TITLE
Why can't I get the class name？

### ISSUE THREAD

**Issue by PachVerb** [KingSora/OverlayScrollbars#215]
In the vue, I register the component manually, but in my stylesheet, I cannot refer to the component name at the time of registration as the class name, right? What happened? Help!
![image](https://user-images.githubusercontent.com/43908467/81100169-a65bcd80-8f3e-11ea-8221-714cbc148778.png)
![image](https://user-images.githubusercontent.com/43908467/81100197-b4115300-8f3e-11ea-91c6-ba279f9047c8.png)
![image](https://user-images.githubusercontent.com/43908467/81100220-bffd1500-8f3e-11ea-9951-007f30f5f5b4.png)
![image](https://user-images.githubusercontent.com/43908467/81100247-ca1f1380-8f3e-11ea-94e6-9dc66931331c.png)

**Comment by KingSora** [comment]
Good day!

`.overlay-scrollbars` isn't the class, its the component tag for the templates inside vue. You can simply add a class to the component:

```html
<overlay-scrollbars class="my-class">
</overlay-scrollbars>
```
and then add stylings inside CSS for that class:
```css
.my-class {
  max-height: 400em;
}
```

**Comment by PachVerb** [comment]
thank you,  i got it.   i'am  stupid
