### ISSUE TITLE
OverlayScrollbars in Popup/Modals - Angular, Kendo library

### ISSUE THREAD

**Issue by shuherco** [KingSora/OverlayScrollbars#219]
Hi @KingSora,
i really like OS, it's a great tool. I am using it with anular/kendo library and i did not find a way to add it in popup/modals(dropdown/combobox).
can you tell me please if it works ?
And also wich classnames i can add manually to make it work inside popups modals.
Thanks.
I added it with, but every time i close/open popup is gone(it's not part of DOM)
OverlayScrollbars(document.querySelector(".k-list-scroller"), this.osComponentOptions);
Thanks a lot!

**Comment by KingSora** [comment]
Good day!

Could you please create a small demo of your problem on CodeSandbox or StackBlitz? You can also create a project on Github which I can checkout. In this way it would be a lot simpler to solve your problem.

**Comment by shuherco** [comment]
Hi @KingSora,
thanks for your quick reply,
please check https://stackblitz.com/edit/angular-zlrw5z
and i try to add the OS on open event, it works first time but after some times when i want to open close it, doesn't wrk anymore and shows some spaces.
It won't be replaced.
I tried to add it on after view init bu still doesn't work.
also you can see the ugly windows scrollbar on the second dropdown.
![image](https://user-images.githubusercontent.com/1780721/81939853-29dc8500-95f7-11ea-8f2d-f175ae9c0644.png)
Thanks!

**Comment by KingSora** [comment]
Alright, I believe I've figured it out.

The reason why there was a blank space was, because the host element was scrolled (with javascript), which led to this blank space. I've redirected the scroll to the viewport, so that it does what is should do. I've also added a cleanup on the `close` event: https://stackblitz.com/edit/angular-zlrw5z-jiykal?file=app/app.component.ts

**Comment by shuherco** [comment]
Hello @KingSora,
yeah - it works great on the project! 
Really appreciated. 
The another thing i am figuring out to make is to make the scroll work on a kendo dropdown virtual list. Seems the scroll won't be attached. 
I will try more and if you have time will ask you to check.
Thanks a lot!!!!! The OS is really amazing

**Comment by KingSora** [comment]
@shuherco Glad I could help.
If you have more cases you need guidance, please feel free to post them. (Always provide a short StackBlitz / CodeSandbox example for me)

**Comment by shuherco** [comment]
Hi @KingSora, 
thank you very much for your support, it's very helpful
just last thing is not working for me is with kendo dropdownlist and virtual scrolling 
Overlayscrollbars with Virtual Scrolling dropdown
Can you check please what is the problem ?
https://stackblitz.com/edit/angular-zlrw5z
Please check that the browser is freezing if you put .k-virtual-list class or another that is in that list.
I am not sure why it's freezing but looks weird.
Thanks

**Comment by KingSora** [comment]
@shuherco looks like the code runs somewhere into a infity loop. I don't know where exactly the problem is, but I couldn't solve it.. I'm sorry.

This will probably work in `v2.0.0` though.
