### ISSUE TITLE
Wrapping around instead of replacing?

### ISSUE THREAD

**Issue by jsieler** [KingSora/OverlayScrollbars#22]
I have a suggestion of adding how plugin structure will be added. I will provide small example, so you can better understand what i mean.

Let's assume following HTML structure is given:
```
<div id="chat">
  <div id="messages">
    ... list of messages ...
  </div>
  <div id="input">
    ... input field ...
  </div>
</div>
```

We want to make our messages scrollable and input element should be static/not scrollable. We do:
`var messages= $('#messages').overlayScrollbars({ }).overlayScrollbars();`

Seems good so far, but, our element `#messages` is **replaced** with container of `overlayScrollbar`, and now we can not fill/add our chat messages to `#messages`, beucase it is broken now. The only possibility in this case is to add some middleware container which will make it scrollable, for example like this:

```
<div id="chat">
  <div id="scroll">
    <div id="messages">
      ... list of messages ...
    </div>
  </div>
  <div id="input">
    ... input field ...
  </div>
</div>
```

With such initialization:
`var messages= $('#scroll').overlayScrollbars({ }).overlayScrollbars();`

In this case we will be able to add all our messages directly to `#messages`.

My suggestion is actually not to replace the selected element with `overlayScrollbars` containers, but by wrapping around it, so we will not have to add some other containers to make it work.

Hope you understand what i mean :)

**Comment by KingSora** [comment]
Good day!

I understand your problem, but this is something you have to handle by yourself. There are two possibilities to solve this problem:

1. Since youre using jQuery, you can solve this problem like this:
```javascript
$('#messages').wrap('<div></div>').parent().overlayScrollbars({ });
```

2. You can add content without any special adjustmens but with a slightly different selector:
```javascript
$('#messages .os-content').first().append(/* your content */);
```

**Comment by jsieler** [comment]
Oh, nice solution! Thanks! :D
So, think we can close it then :)
