### ISSUE TITLE
[overlayscrollbars-react] Module not found

### ISSUE THREAD

**Issue by pre-ska** [KingSora/OverlayScrollbars#221]
**Describe the bug**
the error I'm getting:  
./node_modules/overlayscrollbars-react/dist/overlayscrollbars-react.esm.js
Module not found: Can't resolve 'overlayscrollbars' in 'C:\....\node_modules\overlayscrollbars-react\dist'

[screenshot](https://imgur.com/a/ixY3tfJ)

**Environment**
 - win10
 - Edge chromium stable
- "react": "^16.13.1"

ps:
I actually do have that file in dist folder in node modules

**Comment by KingSora** [comment]
Good day!

This must be something related to you building process, since I havent encountered such a issue in any project yet. Are you using `react-create-app` and `webpack`?

**Comment by pre-ska** [comment]
yes, I'm using create-react-app 
here is the npm list 

```
  "dependencies": {
    "@material-ui/core": "^4.9.14",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.53",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "axios": "^0.19.2",
    "mobx": "^5.15.4",
    "mobx-react": "^6.2.2",
    "react": "^16.13.1",
    "overlayscrollbars-react": "^0.2.2",
    "react-dom": "^16.13.1",
    "react-loading-overlay": "^1.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "shortid": "^2.2.15"
  },
```
I've reinstalled a couple of times, no use

**Comment by KingSora** [comment]
The `overlayscrollbars-react` package is dependent on the `overlayscrollbars` package, please install it and try again.

**Comment by pre-ska** [comment]
thanx, no errors now
I don't know how I missed big title **Peer Dependencies**  👍

**Comment by KingSora** [comment]
Glad I could help :)
