### ISSUE TITLE
Why can't the overlayScrollbars-vue demo be opened under IE10

### ISSUE THREAD

**Issue by FrontEnd-Hub** [KingSora/OverlayScrollbars#222]
your vue demo is wrong in ie 10, and my vue project also,
Can you find a solution?
thank

**Comment by KingSora** [comment]
Good day!

The demo and `overlayscrollbars-vue` was build with IE11 as the "browser with fewest features" in mind. So it is completely possible it won't work in IE10. The plugin intself works in IE8 though.

**Comment by FrontEnd-Hub** [comment]
thank, I only use overlayscrollbars not overlayScrollbars-vue now
