### ISSUE TITLE
Container scrolls to top when DOM is changed  (Angular 8).

### ISSUE THREAD

**Issue by rjborba** [KingSora/OverlayScrollbars#223]
Container scrolls to top when DOM is changed  (Angular 8).
I've found this issue with ngx-bootstrap tooltip component.

Whenever tooltip was toggled, container was scrolling up and then down, in a loop.

I could notice that it happens also with ng-if elements.
I guess it has something related with autoUpdate, once in older browsers like IE11 it is not reproducible. 

**To Reproduce**
1. Create an element with dynamic DOM insertion (ng-if, for example) 
2. Scroll down
3. Toggle element with ng-if
4. See error (container scrolls up)

**Expected behavior**
Container keep current scroll offset position

This issue is not reproducible on IE11

Amazing LIB, by the way.

**Comment by rjborba** [comment]
I just found that the problem is related to style scroll-behavior: smooth.

**Comment by KingSora** [comment]
@rjborba Thanks for the report!

Could you create a small example app which demonstrates the issue on [CodeSandbox](https://codesandbox.io/) oder [StackBlitz](https://stackblitz.com/)? It would make it easier for me to investigate it

**Comment by rjborba** [comment]
@KingSora 
I've try to reproduce it with a simpler code on StackBlit, but everything seems to be working just fine.
Looks like I'm doing something wrong with my actual code.

https://stackblitz.com/edit/angular-module-sandbox

I'm sorry. This issue may be closed.

**Comment by KingSora** [comment]
@rjborba Alright. A small advice: make sure no styles of your project are overriding any styles from `OverlayScrollbars`. In case you figure something out, please don't hesitate to post it here. I'll reopen this issue in case it's a bug.
