### ISSUE TITLE
Change the ant designUI library scrollbar problem

### ISSUE THREAD

**Issue by 1765659645** [KingSora/OverlayScrollbars#224]
I find the element by its class name, then call a method to change its scrollbar, and always encounter an error message:

DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by KingSora** [comment]
Good day!

Thanks for the report, could you please show me a codeexample or event upload a small demo? This would make it much easier for me to understand and solve your problem.

**Comment by 1765659645** [comment]
![image](https://user-images.githubusercontent.com/57136514/83382308-655bb980-a415-11ea-93dc-63b5ad687ed9.png)
This is a Transfer component of ant design

**Comment by 1765659645** [comment]
The scroll bar will appear when there is a lot of data, so I go to the console to look for the elements I need to set the scroll bar

**Comment by 1765659645** [comment]
Then I set the custom scrollbar at componentDidUpdate.

componentDidUpdate() {
    setTimeout(() => {
      setScrollBarByClassName('ant-transfer-list-body');
    }, 100);
  }

**Comment by 1765659645** [comment]
看起来设置成功了，因为滚动条样式改变了

**Comment by 1765659645** [comment]
But when I click on one side of the data transfer to the other side, I get an error：
NotFoundError: Node.removeChild: The node to be removed is not a child of this node

**Comment by 1765659645** [comment]
@KingSora 
I have uploaded the code screenshot, please check.

**Comment by KingSora** [comment]
@1765659645 Thanks for the example screenshots, except I can't really help you because I would be guessing... Is there a change you could make a example on [CodeSandbox](https://codesandbox.io/) / [StackBlitz](https://stackblitz.com/) or upload your project to github? In your case I really need to evaluate the DOM and code and try different things to figure out a suitable fix.

**Comment by KingSora** [comment]
@1765659645 Any news here?

**Comment by KingSora** [comment]
@1765659645  I'll close this issue because of inactivity. In case you need more help with this topic please feel free to reopen it.
