### ISSUE TITLE
Testing and feature adding to overlayscrollbars-ngx

### ISSUE THREAD

**Issue by NechiK** [KingSora/OverlayScrollbars#225]
Hi @KingSora 
I'm trying to add `InjectionToken` for overlayscrollbars-ngx. It relates to configuration.
And I need to know to test my feature properly.

I see that you import `OverlayscrollbarsModule` in the next way 
`import { OverlayscrollbarsModule } from 'overlayscrollbars'`;
However, as I understand, in this way angular will take module from `node_modules`. And even if I will make changes to the angular component and will build it, I will not see my changes.

So, I imported it in another way and it works
`import { OverlayscrollbarsModule, OVERLAY_SCROLLBAR_OPTIONS } from '../../../dist/overlayscrollbars-ngx.js';`

Could you, please, describe correct way? Because this feature will allow to configure scrollbar only once in `AppModule` and it is what I need in my project :)

**Comment by KingSora** [comment]
Good day!

So you are trying to make something of a sub-package where you make changes to my package and the you want to use your sub-package with the changes you made inside your project.. did I get this right?

**Comment by KingSora** [comment]
In case you just want to define the default options globally for your project you can use the built-in `OverlayScrollbars.defaultOptions` method. This method will do exactly what you want I believe. You can read more about the method [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/gmethod-defaultoptions).

**Comment by NechiK** [comment]
> In case you just want to define the default options globally for your project you can use the built-in `OverlayScrollbars.defaultOptions` method. This method will do exactly what you want I believe. You can read more about the method [here](https://kingsora.github.io/OverlayScrollbars/#!documentation/gmethod-defaultoptions).

How I can use default options in Angular? I followed your link and there is example only for JS. Angular has feature like `InjectionToken`. Which allows providing config inside `AppModule`. And I would like to implement this feature for your package

**Comment by KingSora** [comment]
Well, basically Angular _is_ normal JS (since TypeScript is a superset of it). I've created a small example for you here: https://stackblitz.com/edit/angular-ivy-jjr6qs

In the `main.ts` file you can see the following lines:
```js
import OverlayScrollbars from 'overlayscrollbars';

OverlayScrollbars.defaultOptions({ 
  paddingAbsolute: true,
  scrollbars : {
    autoHide : 'move',
  }
});
```
There I set the defaultOptions for all future instances, and since this is in the `main.ts` this means this are the defaultOptions for all instances. Later I'm normally using the `overlay-scrollbars` component inside the `app.component.html` and as you can notice, I'm not passing any options to it, so it has the previously defined defaultOptions applied.

**Comment by KingSora** [comment]
@NechiK did the example do what you wanted to implement, or do you still need help with your original question?

**Comment by NechiK** [comment]
Yes, it does. I just wanted to implement it in "Angular way". But your example works :) Thanks

**Comment by KingSora** [comment]
Glad I could help :)
