### ISSUE TITLE
Strange Behavior with SwiperJS

### ISSUE THREAD

**Issue by ravzkie12** [KingSora/OverlayScrollbars#231]
Hello,

After using the OverlaySB(with default values in the demo), my Coverflow Slider(SwiperJS) is having a gap below my lower solid color Div. after disabling the OverlaySB. the coverflow is back to normal again.

Video,
without OverlaySB: https://imgur.com/a/NB7ArEh
with OverlaySB: https://imgur.com/a/2ZOwSLQ

**Comment by KingSora** [comment]
Good day!

Is it possible to create a live example on [StackBlitz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/) or [JSFiddle](jsfiddle.net/)? It would make it more easy to fix your issue.

**Comment by KingSora** [comment]
@ravzkie12 any progress here?

**Comment by KingSora** [comment]
I'll close this issue due to inactivity, if you have anything new here, please don't hesitate to reopen it.
