### ISSUE TITLE
Bug in mobile version, height of scrollbar block is not recalculating

### ISSUE THREAD

**Issue by lossen** [KingSora/OverlayScrollbars#232]
Everything works well on the desktop, but in the mobile version, for blocks whose height has changed, the scrollbar does not work correctly. 
For example, in the desktop version, there are three buttons in a row in a block 100px high, and in the mobile version, these three buttons are arranged in a column, due to which the block height increased by 200 px and is 300 px. In this case, the scrollbar does not work correctly, as if not recounting the block height. 
I can fix this behavior by writing the maximum height minus the height by which the block increased in the mobile version. But this is not a solution to the problem.
Please see the real example on the gif.

![Screen Recording 2020-06-14 at 19 38 33](https://user-images.githubusercontent.com/14949813/84594982-59d9ab00-ae77-11ea-871c-58a6d11795f9.gif)

**Expected behavior**
I expect that in mobile version height of scrollbar block will recalculate automatically.

**Environment**
Mac os 10.15.4
Chrome 83.0.4103.97
overlayscrollbars 1.12.0
overlayscrollbars-react 0.2.1
react 16.8.6

**Comment by KingSora** [comment]
Good day!

Is it somehow possible to get a minimal example on [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/)? It would make the process mich easier to fix your issue.

You can also upload your entire project into a private github repo, so I could take a look this way.

**Comment by lossen** [comment]
@KingSora it happens even if I reload the page in mobile mode. 
https://codesandbox.io/s/wizardly-tdd-xfvgj?file=/TabList.js

![Screen Recording 2020-06-15 at 10 29 04](https://user-images.githubusercontent.com/14949813/84618237-6a2f6b80-aef3-11ea-8d09-7fcf6bbc3c6e.gif)

I made a bottom red border on blocks so you can see that in mobile mode red border of the last block is not visible
Please let me know your thoughts. Any help will be appreciated.

**Comment by KingSora** [comment]
@lossen are you sure the Sandbox link is correct? It seems some stuff is missing..

**Comment by lossen** [comment]
@KingSora yeah, sorry it was not saved for some reason. Now it should work.

**Comment by KingSora** [comment]
@lossen Thanks!

So what I found out is, that this isn't related to the plugin. The mistake lies in your CSS and how you calculate the height of the `tab-content` element. If I change the CSS like this, it works:
```CSS
.content-box .tab-content{
  height:calc(100% - 100px)
}
```

Basically you're cutting of the element, thats why it just looks like it doesn't scroll to the end.

![grafik](https://user-images.githubusercontent.com/12936317/84935604-3b72ea00-b0d9-11ea-8cac-774acb5e4c2b.png)

**Comment by KingSora** [comment]
@lossen did my answer solved your problem?

**Comment by lossen** [comment]
Yes, thank you so much!
