### ISSUE TITLE
scroll to bottom 

### ISSUE THREAD

**Issue by Massi-githuber** [KingSora/OverlayScrollbars#233]
hello there!
i searched for a long time how to init the scrollbar to the bottom like in messenger or set it to scroll automaticaly to bottom when the content of the div is loaded ...i was wondering if someone could help me with this !!
thanks in advance

**Comment by KingSora** [comment]
Good day!

Basically you can just use the `scroll` method of the instance:
```js
var osInstance = OverlayScrollbars(/* your element*/, { });
osInstance.scroll({ top: "100%" });
```
With this code you scroll to the bottom instantly after you've initialized the plugin.

**Comment by Massi-githuber** [comment]
> ```js
> var osInstance = OverlayScrollbars(/* your element*/, { });
> osInstance.scroll({ top: "100%" });
> ```

thank you so much ...it works!!!

**Comment by KingSora** [comment]
No problem, Glad I could help! :)

**Comment by robkiessling** [comment]
For people stumbling upon this later, the old `scroll` method is not (yet?) implemented in V2. You can manually scroll using native DOM methods as described [here](https://github.com/KingSora/OverlayScrollbars/issues/603#issuecomment-1884892175).
