### ISSUE TITLE
Native scrollbar visible in iOS Safari during horizontal scroll.

### ISSUE THREAD

**Issue by joh-sch** [KingSora/OverlayScrollbars#234]
**Description**

I am using the plugin to make a div horizontally scrollable. This is how I initialise the instance:

```
function init_shopFilterMenu_scrollbars() {
  var instance = OverlayScrollbars(
    document.querySelector(".shopControlWrapper"),
    {
      overflowBehavior: {
        x: "scroll",
        y: "hidden",
      },
      scrollbars: {
        visibility: "hidden",
        autoHide: "scroll",
      },
   }
  );
}
```

Everything work as expected, but the native scrollbars are still visible when the element is scrolled in Safari’s mobile Version.

**Expected behavior**

This is the expected behaviour, as it works correctly when the element is scrolled in Safari’s Responsive Design Mode:

![Reference_ScrollbarHiddenOnDesktop](https://user-images.githubusercontent.com/39758027/85508510-84083700-b5f4-11ea-8e62-4ff0bdb1810d.gif)

But when scrolled in Safari on an actual mobile device (iPhone 6s in my case), native scrollbars are revealed:

![Reference_ScrollbarVisible](https://user-images.githubusercontent.com/39758027/85508847-1d374d80-b5f5-11ea-9af5-3936654cb6c8.jpg)

**Environment**

Used Operating System(s): iOS 12.3.1
Used Browser(s) (with version): Safari 12

**Additional context**
I'm aware of a similar bug (mentioned on the plugin's website) that causes native scrollbars to appear when targeting the body-element. However, I am not targeting the body.

Thanks for any help or suggestions to solve this.

**Comment by KingSora** [comment]
Good day! 

Is this also happening in other Browsers like Chrome or Firefox on your Phone? Is there also a possibility to test your site with a Android device to see whether the issue appears there too?

**Comment by joh-sch** [comment]
Hi and thank you for the fast response.

Yes, the scrollbars are showing up in Google Chrome on the phone as well.

**Comment by KingSora** [comment]
One thing I forgot, can you please provide a minimal example on on [StackBlitz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/) or [JSFiddle](https://jsfiddle.net/)? I can then start looking into it via BrowserStack.

**Comment by KingSora** [comment]
@joh-sch any progress here?

**Comment by KingSora** [comment]
@joh-sch I'll close this issue because of inactivity, I would really like to fix it though! In case you have any more feedback, please feel free to write & reopen this issue.
