### ISSUE TITLE
Set scrollbar to visible always when the content is expanded

### ISSUE THREAD

**Issue by gh-supersudo** [KingSora/OverlayScrollbars#235]
I want the scrollbar to show when the content is expanded, and always visible unless the content is folded back that fit to browser width.

I tried it with this code but the scrollbar always hide when the mouse pointer left the sidebar div. 

Here is the code: 

```js
document.addEventListener("DOMContentLoaded", function() {
    OverlayScrollbars(document.querySelectorAll('.sidebar'), {
      sizeAutoCapable: true,
      scrollbars: {
        visibility: "visible",
        autoHide: "never",
      },
    });
});
```

**Comment by KingSora** [comment]
Good day!

Thats interesting... can you please post a minimal example on on [StackBlitz](https://stackblitz.com/), [CodeSandbox](https://codesandbox.io/) or [JSFiddle](https://jsfiddle.net/)? That would speed up the process. Thanks!

**Comment by KingSora** [comment]
@gh-supersudo any news here?

**Comment by KingSora** [comment]
@gh-supersudo I'll close this issue because of inactivity. Feel free to reopen it in case you need help!
