### ISSUE TITLE
auto height calculate or responsive height resize not works 

### ISSUE THREAD

**Issue by iamshareque** [KingSora/OverlayScrollbars#236]
I am new to all this, so don't know exactly to the way of reporting and ask feature request format.

**Is your feature request related to a problem? Please describe.**
I show HTML pages on the sidebar it has full height, 
in which I created a header which height depends on content normally 60px height. overlay scrollbar does not act as getting remaining height from an available height, it creates a problem.

**Describe the solution you'd like**
*when I try to assign 100vh - 60px it works normally on PC
but on iPad Safari 9 it misses 25px so add 25px = 100vh - 85 
on iPad Chrome 100vh - 60px

**Describe alternatives you've considered**
for a temporary purpose, I did this way using jquery but I think it's not perfect.
calling on page funcation 
```
<script>
  $(document).ready(function() {
    setContanierHeight("box-header",8,"scrollBox");
  });

  window.addEventListener('resize', function () {
    setContanierHeight("box-header",8,"scrollBox");
  });

  window.addEventListener("orientationchange", function() {
    setContanierHeight("box-header",8,"scrollBox");
  });
</script>
```

```
function setContanierHeight(headerClass,any_diff,containerClass){
  
  var windowHeight=$( window ).height();
  var headerHeight=$("."+headerClass).outerHeight(true);
  var newHeight= (windowHeight - headerHeight );
  $("."+containerClass).css('height', (newHeight+any_diff)+'px');
  console.log("Windown height:"+windowHeight+" outer height:"+headerHeight+" any_diff:"+any_diff+" new height="+(newHeight+any_diff));
}
```
![issue](https://user-images.githubusercontent.com/17742511/86879401-98762480-c108-11ea-91b6-32e6e05ea681.png)

**Comment by KingSora** [comment]
Good day!

This looks weird to me, since the calculated sizes you wrote aren't `auto` sizes but `fixed` sizes. To which element are you assigning those values? Did you also try to assign it directly via CSS? Which `box-sizing` model are you working with?

Is it possible for your to create a minimal example on [JSFiddle](https://jsfiddle.net/)?

**Comment by iamshareque** [comment]
here it is, it's not exactly same but similar, box-sizing is the default, and when changing layer position from fixed so it become draggable on iPad mini iOS9.3
http://jsfiddle.net/iamshareque/j1ecwmza

**Comment by KingSora** [comment]
Well.. I have bad news for you. This seems to be a common problem for iOS devices and has nothing to do with the plugin.
I've placed two containers side by side with the same styling and both do have the same dimensions: http://jsfiddle.net/L6wkoesh/4/ which indicates that the library is doing everything correctly and this is related to the browser / enviroment.

**Comment by iamshareque** [comment]
ok, thanks for the help @KingSora I will figure what else I can do.
