### ISSUE TITLE
Doesnt scroll on Mousewheel or Trackpad 90% of the time

### ISSUE THREAD

**Issue by kreadiv** [KingSora/OverlayScrollbars#237]
The script is working fine if i drag the scrollbar with the mouse.
But the most of the time, the wheel event or trackpad event doesnt do anything...

The problem occurs on Windows and MacOs in all Browsers.
There is no error message. If i reload the browser it works sometimes.

**Comment by KingSora** [comment]
Good day!

Could you create a example of how you are using the plugin? Its weird because the plugin isn't using a custom mechanism for scrolling, its relying completely on the native functionality of the browser.

**Comment by kreadiv** [comment]
Hello, thanks for your prompt reply!

Indeed, its weird. I can drag the scroll bar and can trigger the scroll methods. 

But if i move the mousewheel or using the trackpad, nothing happens...
On the Website i use a lot flexbox and grid css.
If it works the functionality disappears sporadically.

**Comment by kreadiv** [comment]
Ok, problem solved. I had a fixed positioned overlay. I removed that and now its working :-)

**Comment by KingSora** [comment]
Perfect! :)
