### ISSUE TITLE
Breaks when nested in a flex-box with flex-direction: 'column' in Non-Webkit browsers 

### ISSUE THREAD

**Issue by benjfriedrich** [KingSora/OverlayScrollbars#241]
When you nest an OverlayScrollbar-react component in a flexbox with the flex-direction set to 'column' in Firefox and chrome (but not safari) it breaks. Essentially it treats it as if there were no content.

```
<Wrapper style={{ display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    justifyContent: 'center',
}}>

<div> First item in flebox </div>

<OverlayScrollbar style={{ maxHeight: '50vh',  width: '50vw'}} > content <OverlayScrollbar>
</Wrapper>
```

But if you wrap the OverlayScroll component with a `<div>` it works again.

```
<Wrapper style={{ display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    justifyContent: 'center',
}}>

<div> First item in flebox </div>

<div>
    <OverlayScrollbar style={{ maxHeight: '50vh',  width: '50vw'}} > content <OverlayScrollbar>
</div>

</Wrapper>
```

**Comment by KingSora** [comment]
Good day!

Please try to add the class `.os-host-flexbox` and checkout wether it still breaks.

**Comment by KingSora** [comment]
@benjfriedrich any feedback here?

**Comment by benjfriedrich** [comment]
Oh--sorry forgot to follow up! That did the trick! Thanks a bunch
