### ISSUE TITLE
Keep the html element which scrolls consistent when introducing OverlayScrollbarsComponent

### ISSUE THREAD

**Issue by mallison** [KingSora/OverlayScrollbars#242]
**Is your feature request related to a problem? Please describe.**
I have a React app with some scroll/mousemove event handlers attached to the document.

With code like this

```jsx
<div className="scrollContainer">
  <div className="content"><!-- scrolling content here --></div>
</div>
```

I'm doing `document.getElementsByClassName('scrollContainer').forEach(el => doSomethingWith(el.scrollTop)`.

When I switch to `OverlayScrollbarsComponent`

<OverlayScrollbarsComponent className="scrollContainer">
  <div className="content"></div>
</div>

The above code breaks and I have to change to `document.getElementsByClassName('os-viewport').forEach(el => doSomethingWith(el.scrollTop)`.

**Describe the solution you'd like**
It'd be nice if the DOM element that actually scrolls remained consistent.

I appreciate that this might not actually be possible and that my use case wouldn't really justify a change because I'm doing things outside of the React abstraction. Perhaps a better design on my part would mean this isn't an issue.

I also think it's very common that you can't just swap an html element for a React component and expect things of the resulting DOM structure -- that's why things like `forwardRef` exist.

However, I thought I'd at least ask the question!

**Describe alternatives you've considered**
Fixing my document event handlers isn't too much of a problem and I'm also questioning whether I should attach event handlers to multiple React components instead of trying to 'cheat' with `document` event handlers.

**Comment by KingSora** [comment]
Good day!

The element which is respsonbile for scrolling is always the `.os-viewport` element. You can also get this element like:
```js
ref.osInstance().getElements().viewport
```
in react. I already had a discussion why the ref object isn't the `viewport` element directly and there are good reasons for it. If you are intereseted the disussion is [here](https://github.com/KingSora/OverlayScrollbars/issues/150#issuecomment-622337190).

**Comment by mallison** [comment]
Hello!

Thanks for the response and pointers to how to handle this. As I mentioned, I'm not super happy with my code and it is straightforward enough to detect `OverlayScrollbars` enabled components and handle them accordingly.

Cheers!
