### ISSUE TITLE
How do I set the track that displays the scroll bar？

### ISSUE THREAD

**Issue by 1765659645** [KingSora/OverlayScrollbars#243]
You can display the track of the scroll bar by setting the style, so are there properties that you can set the track of the scroll bar?

**Comment by KingSora** [comment]
Good day!

I'm sorry but I don't understand the question.. Maybe the [styling documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/styling) can give you the answers you need? In case it doesn't please rephrase your question and I'll try to help you out!

**Comment by 1765659645** [comment]
I want the scroll bar to show its track, and at the moment my scroll bar is translucent and has no track, is there any property that makes the scroll bar show the track?

**Comment by KingSora** [comment]
The track is always visible when the handle is visible. You can style the whole scrollbar with this selector:
```css
.os-scrollbar {
}
```
or just the track with:
```css
.os-scrollbar > .os-scrollbar-track {
}
```

**Comment by 1765659645** [comment]
Ok, thanks. I'll try it

**Comment by KingSora** [comment]
@1765659645 I'll close this issue. In case you have any further question please don't hesitate to ask them!
