### ISSUE TITLE
overlayscrollbars-ngx should support Angular 10

### ISSUE THREAD

**Issue by TokkeDev** [KingSora/OverlayScrollbars#244]
overlayscrollbars-ngx should allow peer dependency of Angular 10. When doing npm install, the following errors appear:
```
npm WARN overlayscrollbars-ngx@0.2.2 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```
However, everything works fine with both Angular 8, Angular 9 and Angular 10, so I think the peer dependencies of overlayscrollbars-ngx should just be updated to also accept Angular 10

**Comment by KingSora** [comment]
Good day!

Thanks, this is related to #210. I'm sorry I didn't have time to update it until now, but since its working I think its not that urgent.

**Comment by TokkeDev** [comment]
My bad, I didn't see that issue! 
I agree that it's not super urgent, but it's still something that I think should be fixed. Also because it's such an easy fix. 😊
