### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by dkornilove** [KingSora/OverlayScrollbars#250]
Hi. I am unable to get the component working. It is rendered in proper container but nothing happens when I try to scroll it.
I see only native scrollbars working. My container is a div with `<img height="1000px"/>` in it. 
container CSS
```
.test-scroll {
  position: relative;
  height: 500px;
  width: 100%;
  padding-right: 50px;
  overflow: auto;
}
```
So the container is scrollable.
JS
```
$(document).ready(function () {
      const os = OverlayScrollbars(document.querySelector('.test-scroll'), OverlayScrollbars.defaultOptions());
});
```
As it rendered I can see libs html elements with classes _os-host-scrollbar-vertical-hidden_, _os-scrollbar os-scrollbar-vertical os-scrollbar-unusable_. What should I do to get it working? Thanks!

**Comment by KingSora** [comment]
Good day!
In case you are using `box-sizing: content-box` which is the default if you haven't defined it otherwise, try to remove the `padding-right`, so that the container doesn't expand to the right.

I've created you a fiddle which corresponds to your setup: https://jsfiddle.net/ho1t49y7/ and it is working.. so maybe you have overlooked something on your end.

**Comment by Dutchman1990** [comment]
Hi.. me too having issue with the working procedure. I'm using the vue version. I have followed the guide provided with the repo.
But my application is still showing the native scrollbar. If I add the javascript/jquery script inside a script then its working. Without the script I'm seeing only the classes and divs. 
my app.js
`import Vue from 'vue'
import VueRouter from 'vue-router'
import Vuelidate from "vuelidate"
import Vuesax from 'vuesax'
import { OverlayScrollbarsPlugin } from 'overlayscrollbars-vue';
import { OverlayScrollbarsComponent } from 'overlayscrollbars-vue';

Vue.use(Vuelidate)
Vue.use(VueRouter)
Vue.use(Vuesax)
Vue.use(OverlayScrollbarsPlugin)

//js import
import routes from './routes.js'

//css components
import 'material-icons/iconfont/material-icons.css'
import 'vuesax/dist/vuesax.css'
import 'overlayscrollbars/css/OverlayScrollbars.css'

//vue component
 Vue.component('overlay-scrollbars', OverlayScrollbarsComponent);`


and my template..

`<overlay-scrollbars>
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Dashboard
                        <i class="right fas fa-angle-left"></i>
                    </p>
                    </a>
                    <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="index.html" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Dashboard v1</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="index2.html" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Dashboard v2</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="index3.html" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Dashboard v3</p>
                        </a>
                    </li>
                    </ul>
                </li>
               </ul>
            </overlay-scrollbars>`


Am i missing something?

**Comment by KingSora** [comment]
@Dutchman1990 In case you have still problems, please open a separate issue. I'll close this issue because of inactivity of @dkornilove. In case your issue still persists, pelase feel free to reopen the it.
