### ISSUE TITLE
Specifying callbacks in angular removes access to `this`

### ISSUE THREAD

**Issue by xDuck** [KingSora/OverlayScrollbars#257]
The callbacks (as intended) replace `this` with the instance of the scrollbar in angular. I am having a hard time trying to figure out how to get a reference to my class instance into the callback, do you know of a way to do this?

```
<overlay-scrollbars [options]="{ scrollbars: { autoHide: 'leave', autoHideDelay: 100 }, callbacks: { onScroll: cbFunction }}">
```

```
cbFunction($event: any) {
      console.log(this);           // Logs instance of scrollbar.. How do I get to my class references?
}
```

**Comment by KingSora** [comment]
Good day!

I know, I know, this is a plunder on my side, as this plugin wasn't developed with frameworks like `Angular` etc. in mind. OverlayScrollbars changes the `this` context of the callback functions to the current instance. It seemed like a good idea back in the days.

You can work around this with a arrow function: https://stackblitz.com/edit/angular-module-sandbox-s66gb5?file=src%2Fapp%2Fapp.component.ts

**Comment by xDuck** [comment]
Hi, thanks for the response. I ended up working around it by using an arrow function and setting the default options (arrow functions dont seem to work in HTML, they throw parsing errors). My case was a bit more complicated because I had multiple scrollbars in this component so I had to set all the callbacks I needed to `undefined` in the HTML as to not get the callbacks called extraneously..

A bit of a hack but I guess it all worked out in the end.

**Comment by KingSora** [comment]
Glad I could help! 👍

**Comment by akcasoy** [comment]
I am having a similar issue. and although your console.log(this) actually prints the component itself, somehow we cannot change any values in "this" component. Try changing the visibility of your "Togglable item" with this: this.itemVisible = true; in the callback function:

```
  osComponentOptions = {
    callbacks: {
      onScroll: () => {
        this.itemVisible = true;
        console.log(this);
      }
    }
  };
```

**Comment by KingSora** [comment]
This should be fixed with `v2` which comes with a new version of `overlayscrollbars-ngx` where the events work differently :)
