### ISSUE TITLE
How to get scroll offset x , y?

### ISSUE THREAD

**Issue by eagle-design** [KingSora/OverlayScrollbars#26]
How to get scrollTop , scrollLeft?

**Comment by KingSora** [comment]
Good day!

The plugins instance offers a method called [scroll](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll). With this method you're able to scroll to certain offset or to gain scroll information.

Here's a example of how to gain information:
```javascript
var instance = OverlayScrollbars(document.getElementById("id"), { });
var scrollLeft = instance.scroll().x.position;
var scrollTop = instance.scroll().y.position;
```

Here's a example of how to scroll:
```javascript
var instance = OverlayScrollbars(document.getElementById("id"), { });
instance.scroll({ x : 300, y : 300 }, 5000);
```

For further information please read the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll). I hope I could help you!

**Comment by Eve-Sama** [comment]
> Good day!
> 
> The plugins instance offers a method called [scroll](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll). With this method you're able to scroll to certain offset or to gain scroll information.
> 
> Here's a example of how to gain information:
> 
> ```js
> var instance = OverlayScrollbars(document.getElementById("id"), { });
> var scrollLeft = instance.scroll().x.position;
> var scrollTop = instance.scroll().y.position;
> ```
> 
> Here's a example of how to scroll:
> 
> ```js
> var instance = OverlayScrollbars(document.getElementById("id"), { });
> instance.scroll({ x : 300, y : 300 });
> ```
> 
> For further information please read the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll). I hope I could help you!

not work for 0.5.1

**Comment by KingSora** [comment]
@Eve-Sama please use the example in the FAQ section of the Readme: https://github.com/KingSora/OverlayScrollbars?tab=readme-ov-file#faq
