### ISSUE TITLE
We need a slim one of this lib

### ISSUE THREAD

**Issue by jackieveev** [KingSora/OverlayScrollbars#260]
**Is your feature request related to a problem? Please describe.**
This scrollbar is good but too heavy, about 50KB after g-zip!

**Describe the solution you'd like**
Can we do some treeshaking work to reduce its size.Such as:

1. remove supports which is under IE 10 version.
2. remove jq supports.

**Comment by KingSora** [comment]
Good day! 

I'm working on `v2.0.0` and there I'm planning to drop IE8-IE10 support and move certain things into extensions. The code is also rewritten in es6. I'm expecting a significant size reduction, but as I said, in `v2.0.0`.

**Comment by jackieveev** [comment]
> Good day!
> 
> I'm working on `v2.0.0` and there I'm planning to drop IE8-IE10 support and move certain things into extensions. The code is also rewritten in es6. I'm expecting a significant size reduction, but as I said, in `v2.0.0`.

Great!Thanks for what you've done to us, I can't wait to see it.
