### ISSUE TITLE
 Lighthouse warning : Passive listeners Similar case #124

### ISSUE THREAD

**Issue by stephenjason89** [KingSora/OverlayScrollbars#263]
Exact same thing is happening to me
I would like to give a reference to 
https://github.com/KingSora/OverlayScrollbars/issues/124

Here is the output of my
OverlayScrollbars.globals()

Thank you so much
```
{
  "defaultOptions": {
    "className": "os-theme-dark",
    "resize": "none",
    "sizeAutoCapable": true,
    "clipAlways": true,
    "normalizeRTL": true,
    "paddingAbsolute": false,
    "autoUpdate": null,
    "autoUpdateInterval": 33,
    "updateOnLoad": [
      "img"
    ],
    "nativeScrollbarsOverlaid": {
      "showNativeScrollbars": false,
      "initialize": true
    },
    "overflowBehavior": {
      "x": "scroll",
      "y": "scroll"
    },
    "scrollbars": {
      "visibility": "auto",
      "autoHide": "never",
      "autoHideDelay": 800,
      "dragScrolling": true,
      "clickScrolling": false,
      "touchSupport": true,
      "snapHandle": false
    },
    "textarea": {
      "dynWidth": false,
      "dynHeight": false,
      "inheritedAttrs": [
        "style",
        "class"
      ]
    },
    "callbacks": {
      "onInitialized": null,
      "onInitializationWithdrawn": null,
      "onDestroyed": null,
      "onScrollStart": null,
      "onScroll": null,
      "onScrollStop": null,
      "onOverflowChanged": null,
      "onOverflowAmountChanged": null,
      "onDirectionChanged": null,
      "onContentSizeChanged": null,
      "onHostSizeChanged": null,
      "onUpdated": null
    }
  },
  "autoUpdateLoop": false,
  "autoUpdateRecommended": false,
  "nativeScrollbarSize": {
    "x": 17,
    "y": 17
  },
  "nativeScrollbarIsOverlaid": {
    "x": false,
    "y": false
  },
  "nativeScrollbarStyling": true,
  "overlayScrollbarDummySize": {
    "x": 30,
    "y": 30
  },
  "cssCalc": "calc",
  "restrictedMeasuring": false,
  "rtlScrollBehavior": {
    "i": true,
    "n": false
  },
  "supportTransform": true,
  "supportTransition": true,
  "supportPassiveEvents": true,
  "supportResizeObserver": true,
  "supportMutationObserver": true
}
```

![image](https://user-images.githubusercontent.com/3810177/92597062-65ebd200-f2d9-11ea-8c84-bf5c455968b7.png)

**Comment by KingSora** [comment]
@stephenjason89 Thank you very much!
I've already fixed this issue in my local branch and it will be definitely released soon.

Currently I'm not able to add tests to ensure this will always work, but this is something which will definitely be in version `2.0.0` because there I'm using puppeteer for e2e tests.

**Comment by stephenjason89** [comment]
Thank you @KingSora. I would be patiently waiting for your release.
Keep up the great work! I love your overlay scrollbars.

Would like to report that since i'm using overlay scrollbars, vuetify can't detect scroll behavior. 
Some components that have autohide when scrolling does not auto hide. I had to implement a workaround on this by using the your scroll event. Is there anyway to trigger the default scroll event upon scroll?

**Comment by KingSora** [comment]
@stephenjason89 do you have a codeexample for that? Right now its quite hard for me to imagine the issue..

**Comment by stephenjason89** [comment]
Hello yes. I've just created a repo for that.

https://github.com/stephenjason89/OverlayScrollBug

It's a laravel project using vue.

imported overlayscrollbars on bootstrap.js
then used it on app.js

you'll see if you remove the overlay scrollbars, bottom navigation bar hides on scroll. It does not work however on overlayscrollbars.

same goes for every component in vuetify with scroll features and intersect.

Thank you

**Comment by KingSora** [comment]
Fixed with [version 1.13.1](https://github.com/KingSora/OverlayScrollbars/releases/tag/1.13.1)

**Comment by stephenjason89** [comment]
Thank you, will try it out.

**Comment by KingSora** [comment]
@stephenjason89 I just fixed the passive events

**Comment by stephenjason89** [comment]
Thank you for your great work ☺️

**Comment by stephenjason89** [comment]
Hello @KingSora, I didn't want to create a new thread. Would just want to say to please include in V2 a way to properly send scroll events so that vuetify would be able to detect it. This is for hide on scroll events and other stuff that use scrolling , like intersect.

**Comment by KingSora** [comment]
@stephenjason89 could you please elaborate on that further? I'm not sure I understand what you mean..

**Comment by stephenjason89** [comment]
Here is an example that i would like to use

https://vuetifyjs.com/en/components/app-bars/#hiding-on-scroll

the app-bars hide on scroll
but if i use the overlayscrollbars, they don't work

i had to implement something like this just to get the scroll event and hide the app-bar or anything that vuetify has which is triggered by the scroll event.

```
       document.querySelector('.os-viewport').addEventListener('scroll', (e) => {
            this.scrollY = e.target.scrollTop
        })
```

Basically, the scroll event that vuetify listens to is not triggered while using overlayscrollbars.

Thank you

**Comment by KingSora** [comment]
I understand.. in `v2` you'll get more freedom of how to initialize OverlayScrollbars, but it will still generate some elements. The only exception I'll be making will be the `body` element where the target element will also be scrolling element. 

With the `app-bars` for example you can specify the scroll target there with the `scroll-target` property. Thats something which will probably always remain unless you're using `v2` on the body element.

**Comment by stephenjason89** [comment]
@KingSora Thank you :) Will test out v2 once it is ready and provide more feedback :)
