### ISSUE TITLE
Auto Resizing Textarea with initial and max-height

### ISSUE THREAD

**Issue by PabloMarch** [KingSora/OverlayScrollbars#267]
I'm trying to achieve a behavior like on a chat textarea where it has an initial height, when the user types the textarea continues resizing automatically and if the user overflows certain height then the scrollbars shows up, as in this example:

https://codepen.io/heidewitzka/pen/yLNeLbO

When text reaches the bottom of the textarea, the textarea expands.
When the textarea reaches max-height, a scrollbar appears.
When deleting text, the textarea shrinks.

Is this possible with overlay-scrollbars?

**Comment by KingSora** [comment]
@PabloMarch absolutely: https://jsfiddle.net/2nf3uroL/

**Comment by PabloMarch** [comment]
@KingSora amazing!! Thanks
