### ISSUE TITLE
document.body.scrollTop

### ISSUE THREAD

**Issue by stephenjason89** [KingSora/OverlayScrollbars#268]
I'm trying to get the current scrollY position using document.body.scrollTop
but it just returns 0

is there anyway i can get the current Y location ?

I know that there is 
```
callbacks: {
                    onScroll: function save(e)
                }
```

which i can save the scrollY = e.target.scrollTop;

but is there an easier way where i can just get the current scrollTop?

**Comment by KingSora** [comment]
Good day!

If you have the OverlayScrollbars `instance` you can do `instance.scroll().position.y`. This gives you exactly what you want.

**Comment by stephenjason89** [comment]
Thank you

**Comment by lossen** [comment]
If anyone wants not only get position but change it use this 
`        instance.scroll({ y : "100%"  })
`
In this example, it will scroll to bottom.

**Comment by stephenjason89** [comment]
@lossen Thank you, glad to know
