### ISSUE TITLE
How to display extra divs with Linear gradients on vertical or horizontal Scroll?

### ISSUE THREAD

**Issue by fedi87** [KingSora/OverlayScrollbars#270]
Hi @KingSora ,
How can we add the extra divs when scrolling so we can display a gradient or a shadow indicating that a user can still scroll.
In the Styling Demo , it's your last example with javascript modifications.
How can we reproduce it? thanks

**Comment by KingSora** [comment]
Good day!

I answered a smiliar question in #262, please take look there first. If you still have trouble implementing it, please come back to this issue, so I can create a small fiddle for you.

**Comment by fedi87** [comment]
Thanks @KingSora , this is exactly what I need .
A good enhancement might be , if we can add an option when initing  OverlayScrollbars. Something like verticalGradient: true||false , horizontalGradient: true||false. 
I've seen lot of clients asking to display a gradient or a shadow indicating that the user can scroll.
Thanks

**Comment by KingSora** [comment]
@fedi87 You can take a look on Extensions: https://kingsora.github.io/OverlayScrollbars/#!documentation/extensions-basics which allow you to do exactly this.
