### ISSUE TITLE
Horizontal Scrolling

### ISSUE THREAD

**Issue by mathewdodds** [KingSora/OverlayScrollbars#271]
Hi there! 

First of all, awesome stuff here. I love this tool and it is just so clean and easy to use.

The problem I'm facing is horizontal scrolling with nested vertical scrolling. My structure is simple:

```
<div id='horiz-scroll' class='flex row'>

<div id='vertical-scroll' class='flex col'>
{{ dynamic content }}
</div>

<div id='vertical-scroll' class='flex col'>
{{ dynamic content }}
</div>

<div id='vertical-scroll' class='flex col'>
{{ dynamic content }}
</div>

</div>
```

What happens is the horizontal scrolling just automatically switches to vertical and my inline content becomes columned. 

I followed both of your directions for flexbox, appending the class as well as adding the inner block element. Neither work.

Any help is appreciated!! Thanks :D

**Comment by mathewdodds** [comment]
SOLVED:

Added a wrapper element around the horiz element and made that block with a fixed width. Then added overflow-x: scroll and overflow-y: hidden. Works beautifully.

**Comment by KingSora** [comment]
@mathewdodds Thanks for adding your solution 😄 
Glad everything works now.
