### ISSUE TITLE
Is there a way to capture mousedown event for the handle?

### ISSUE THREAD

**Issue by emmanuelulloa** [KingSora/OverlayScrollbars#275]
I need to detect if a user has interacted with the scrollbar but the mousedown event for the handle does not trigger.  I need to detect if the scrollbar handle has been dragged and I cannot use onScrollStart because my automatic animation trigger that one as well.

**Comment by KingSora** [comment]
Good day @emmanuelulloa 
Did you try to use the [getElements()](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-getelements) function to get the required elements, where you can then add the listeners?

**Comment by KingSora** [comment]
@emmanuelulloa I'll close this issue because of inactivity. In case you have any new feedback don't hesitate to reopen it.
