### ISSUE TITLE
[Chat App] - Show a "New Messages" popup at the bottom when new items are added, but the user has scrolled upwards

### ISSUE THREAD

**Issue by f135ta** [KingSora/OverlayScrollbars#276]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when new items are added to the scrolling panel - but I have scrolled up and I cant see that new items have been added

**Describe the solution you'd like**
Show a popup notification in the scrolling panel that tells me there are new items so I can click it, and go to the bottom of the list

**Describe alternatives you've considered**
Nothing yet

**Additional context**
Example: 
![ChatWindow](https://user-images.githubusercontent.com/2043562/98301037-16acdf80-1fb2-11eb-9c9e-7e3c1dbf840a.png)

**Comment by f135ta** [comment]
No response

**Comment by KingSora** [comment]
@f135ta please understand that I'm doing this whole project on my own in my spare time and can't always respond in time. 

What is the problem you're facing? - Are you struggeling to achieve the scroll change if you click on the button?
