### ISSUE TITLE
Scrollbar height flickering inside Angular's ngIf

### ISSUE THREAD

**Issue by swagata1603** [KingSora/OverlayScrollbars#279]
I have used overlay scrollbar in a div, which i am showing conditionally based on a Boolean variable. When i am setting the Boolean value to true then the div with scrollbar working fine. When i am setting it it false then it is flickering.

the container div which is holding overlay scrollbar has a transition of 400ms. When it hides items inside scrollbar hides immediately without any transition. then the div is hiding.

**Comment by KingSora** [comment]
Good day! 

Can you please create a small example on StackBlitz or Codesandbox? I've created a issue template for bug reports, please use it 😅

**Comment by swagata1603** [comment]
Hi, thank you for the reply, basically it is a search dropdown and the data that i am showing inside overlay-scrollbars component is dynamic, getting from my backend. I am sharing the code that i am using. Take a look if this can help you.

basically i have created a custom search type ahead. If i search something, i am getting the data from my backend, after getting the data i am showing dropdown. When the dropdown is showing the scrollbar is fine. On ESC key press or clicking outside the i am hiding the dropdown, at that point data inside scrollbar hides immediately and the height is flickering. Because i have added a custom animation in the dropdown which is taking 400ms to show and hide the dropdown.

```
<ng-container *ngIf="isSearchDropdownOpen">
  <div class="header-search-dropdown" [@headerSearchAnimation]>
      <div class="header-search-dropdown-top">
           <overlay-scrollbars [options]="scrollbarOptions">
                <ul>
                     <li *ngFor="let user of users">
                        <a href="#">
                               <h3>user.name</h3>
                               <p>user.email</p>
                       </a>
                    </li>
                </ul>
           </overlay-scrollbars>
      </div>
      <div class="header-search-dropdown-bot">
           <a href="#">View all users</a>
      </div>
  </div>
</ng-container>
```


```
handleSearch(searchKeyword : string){
    this._loader.start();

    const formData: any = new FormData();
    formData.append('search', searchKeyword);

    this._ajaxService.apiCall(formData, 'dashboard/searchsuggestion', 'POST').subscribe({
      next: (apiResult) => {
        const searchData = apiResult.response.data;
        this.headerSearchResults = searchData;
        this.isSearchDropdownOpen = true;
        this._loader.stop();
      },
      error: (apiError) => {
        this._loader.stop();
      }
    })
  }


  onHideHeaderSearch(event : any){
    if (
      !this.headerSearchContainer.nativeElement.contains(event.target) ||
      event.keyCode == 27
    ) {
      this.isSearchDropdownOpen = false;
    }
  }
```

**Comment by KingSora** [comment]
@swagata1603 thanks for the code, but without a real example I really can't help you as I can only guess the issue... The code looks fine though.

**Comment by swagata1603** [comment]
@KingSora , Yes when the dropdown is hiding at that point the problem is happening. Check out the StackBlitz that i have created, same problem happening here

`https://stackblitz.com/edit/angular-ivy-mzz1i1?embed=1&file=src/app/app.component.html`

**Comment by KingSora** [comment]
@swagata1603 thanks!

The problem is, that the plugin gets destroyed on `ngOnDestroy` and this lifecycle method gets called instantly when the dropdown should disappear. Honestly, I didn't know that you can define such animations in Angular. Does a lifecycle method exist which gets fired at the point in time where the transition is completed?

Made a small demo for demonstation: https://stackblitz.com/edit/angular-ivy-fsaxx3?embed=1&file=src/app/app.component.html Check the console for the `destroyed` message and when it appears.

**Comment by swagata1603** [comment]
@KingSora, check out this anguar.io animation pages link.  Where i think we can attach events after animation completes. Can we fire scrollbar destroy event after animation complete?

`https://angular.io/guide/transition-and-triggers#animation-callbacks`

**Comment by swagata1603** [comment]
@KingSora, Any solution on this, what I can do?

**Comment by KingSora** [comment]
@swagata1603 Well, you could just create your own `overlay-scrollbars` component, which suits your needs. The actual source code for the angular wrapper isn't very long or complex: https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-ngx/src/overlayscrollbars.component.ts

**Comment by swagata1603** [comment]
@KingSora, thank you, two more question I want to ask. 

1. If I remove the onDestroy method from the example that you have shared. is it going to leak memory?
2. How to prevent body scroll when overlay scrollbar reaches end.  Because overlay scrollbar's starts scroll body when it reaches end.

**Comment by KingSora** [comment]
@swagata1603 
If you don't destroy the instances, its a memory leak, yes. But you have now all the freedom you need to destroy them with a custom function maybe, or something like that. You just need to do it at some point.

If I remember correctly there was a extension for that: https://github.com/parsisolution/os-scroll-chain give it a shot :)

**Comment by swagata1603** [comment]
@KingSora 

thank you, One last question I forgot ask, after that you can close the issue, what will be the HTML markup to add overlay scrollbar in a text area?

**Comment by KingSora** [comment]
I've commented it here: https://github.com/KingSora/OverlayScrollbars/blob/914836370aa444b04cc9e0c2bca63915ac8fdba0/js/OverlayScrollbars.js#L6352-L6410

But please note that I haven't created a textarea component on purpose yet.

**Comment by swagata1603** [comment]
@KingSora, According to your code i have to repeat the last part(textarea) every time? or there is any shorter way?

**Comment by swagata1603** [comment]
@KingSora, after creating the custom component my issue got resolved, but i am struggling to add the extension. I don't want to pass it in the extensions input. I want to disable entirely for my project.

So for my custom scrollbar component i have used the extension in his way - 

1. Installed the npm package
2. Added os-scroll-chain.min.js in angular.json
3. imported like this in my scrollbar component -` import * as scrollChain from 'os-scroll-chain';`
4. In the component used like this - 
```
ngAfterViewInit() {
    this.ngZone.runOutsideAngular(() => {
      this._osInstance = OverlayScrollbars(
        this.osTarget(),
        this._options || {},
        scrollChain, {vertical: false, horizontal: false}
      );
    });
  }
```

**Comment by swagata1603** [comment]
@KingSora, can be able to help me with the scroll chain extension, means how i can use it in angular?

**Comment by KingSora** [comment]
You have to do it like:


```js
// in your entry js file, like index.js or main.js:
import * as scrollChain from 'os-scroll-chain';
OverlayScrollbars.extension("scrollChain", scrollChain );

// later in your component (no further import needed):
OverlayScrollbars(
  this.osTarget(),
  this._options || {},
  { scrollChain: {vertical: false, horizontal: false} }
);
```

**Comment by swagata1603** [comment]
@KingSora ,

Can i use these two imports in my custom overlay scrollbar component - 

```
// in your entry js file, like index.js or main.js:
import * as scrollChain from 'os-scroll-chain';
OverlayScrollbars.extension("scrollChain", scrollChain );
```

because, there is no entry js or main js in angular, at least id don't have any knowledge. Please suggest.

**Comment by KingSora** [comment]
@swagata1603 you always have a entry file, in angular its the `main.ts` file. 

Please don't get me wrong, but this issue has been going on for long enough, if you have further problems, you can always read the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation), or google stuff.. Please don't use Github as a support platform.
