### ISSUE TITLE
IE11 + Vue sometimes gets error "TypeError: Permission denied"

### ISSUE THREAD

**Issue by kulaone** [KingSora/OverlayScrollbars#28]
I couldn't reproduce this plug on a simple examples
When using complicated VUE app I get a lot of "TypeError: Permission denied" on line 909
`if (el.addEventListener) {`
And the OverlayScrollbars won't replace the element's scrollbars.

When I wrap this with Try & Catch the error is gone and OverlayScrollbars is working.
`try {el.addEventListener
                           if (el.addEventListener) {
                                for (i = 0; i < eventName.length; i++)
                                    el.addEventListener(eventName[i], handler);
                            }
                            else if(el.detachEvent) {
                                for (i = 0; i < eventName.length; i++)
                                    el.attachEvent('on' + eventName[i], handler);
                            }
                        } catch (e) {
                            // console.log(e);                        
                        }`

**Comment by KingSora** [comment]
Alright, thanks!

I've googled this error and found [this](https://stackoverflow.com/questions/2960153/permission-denied-with-internet-explorer-and-jquery/2960963#2960963) answer.
Please try it out and tell if this fix also works.

**Comment by kulaone** [comment]
@KingSora, 
Thanks, I tried but it didn't solve the problem. 
This is the error from the console:
[Vue warn]: Error in updated hook: "TypeError: Permission denied"

**Comment by KingSora** [comment]
Ok, I'll go with your fix. It will be available in `version 1.4.4`.
Once again, thank you very much for reporting and offering a solution for this bug!

**Comment by KingSora** [comment]
`version 1.4.4` is out now and this bug should be fixed! [https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.4.4](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.4.4)
