### ISSUE TITLE
disables sticky headers

### ISSUE THREAD

**Issue by bbpoizon** [KingSora/OverlayScrollbars#284]
Im using the os-theme-dark. I've tried using the os-host-flexbox, but it always breaks whatever flex box its applied to.

**To Reproduce**
1. Go to www.courtneybrown.digital
2. Click on ui/web design
2. Click on first project row (cmmc)
3. Scroll section on right side (project images)

**Expected behavior**
Sticky headers should remain at the tops of the container until replaced by the next one
![should-work-like-this](https://user-images.githubusercontent.com/44776007/100820863-2d155200-341d-11eb-9fc6-de0f5bbfe7ae.gif)

**Examples**
Sticky headers remain in natural document flow. Second sticky header doesn't stick at all.
![sticky-headers-dont-stick_3](https://user-images.githubusercontent.com/44776007/100820850-225abd00-341d-11eb-8d0f-08b0a2b0f15a.gif)

**Environment**
 - Used Operating System(s):
macOs Catalina 10.15.6
 - Used Browser(s) (with version):
Chrome 79.0.3945.88

**Additional context**

**Comment by KingSora** [comment]
Good day @bbpoizon!

Yes, thats kind of an small limitation, but you can work around it by changing the `height` of the `.os-content` element to `auto`.
In your case:

```css
.project-photos.os-host > .os-padding > .os-viewport > .os-content {
  height: auto !important;
}
```

**Comment by SuperiorJT** [comment]
Would there be any side effects by making this workaround be the default behavior? For my case, I used this selector to make the change only when there is an overflow: 

`.os-host-overflow-y > .os-padding > .os-viewport > .os-content`

 Seems like it would be worth considering, but I'm not sure if doing so would break it in other areas.

**Comment by KingSora** [comment]
`v2` released today which should fix this issue :)
