### ISSUE TITLE
[React] The plugin doesn't work inside a modal window with max-height: 100%

### ISSUE THREAD

**Issue by IgorLesnevskiy** [KingSora/OverlayScrollbars#286]
**Describe the bug**
The plugin doesn't work inside a modal window with `max-height: 100%`

**To Reproduce**
1. Go to https://codesandbox.io/s/optimistic-fire-qbim7
2. Click on the "Show modal" button (it opens in the Portal)
3. There is a lot of content in the modal, but the plugin doesn't work
4. Go to the console and replace manually the height of the `.os-host` element with any value 
5. The plugin starts working

**Expected behavior**
The plugin works correctly from the beginning

**Examples**
https://codesandbox.io/s/optimistic-fire-qbim7

**Environment**
 - Used Operating System(s): MacOS Catalina
 - Used Browser(s) (with version): Google Chrome for MacOS (version 86.0.4240.198 (Official Build) (x86_64))

**Additional context**
Hello, @KingSora 

I try to apply the plugin to the content in a modal window. As far as I can see, the `.os-resize-observer-host` doesn't observe the changes in the size of the modal window (and for some reason, it doesn't work from the beginning). To be honest, I spent several hours trying out different options and styles, but unfortunately, I couldn't solve this problem. 

I'm not sure that it's a bug, but may I ask you to take a look and help me with it?

**Comment by KingSora** [comment]
Good day!

This is related to the flexbox setup you have inside the modal. `OverlayScrollbars` currently doesn't work well as direct flexbox child/item. Thats why I created the `os-host-flexbox` class to solve such issues: https://codesandbox.io/s/winter-wildflower-4i9s5?file=/src/App.js

**Comment by IgorLesnevskiy** [comment]
oh, I'm sorry... I was adding that class to the outer container...

```jsx
<div class="os-host-flexbox">
    <OverlayScrollbarsComponent>
        <div className={"modal__content"}>{props.children}</div>
    </OverlayScrollbarsComponent>
</div>
