### ISSUE TITLE
Ability to add visual markers on the overlay scrollbar

### ISSUE THREAD

**Issue by jetacpp** [KingSora/OverlayScrollbars#295]
Hello, I was wondering if it would be a good idea for the library to support scrollbar markers. One example of scrollbar visual markers would be Chrome's scrollbar markers that highlights occurrences of search results. :+1:

**Comment by KingSora** [comment]
Good day @jetacpp 

Thats definitely 100% possible, although I probably won't do it myself, because the usecase is very specific. Its something which could be done as a extension.
