### ISSUE TITLE
Check if scroll bar reached end of the container

### ISSUE THREAD

**Issue by swagata1603** [KingSora/OverlayScrollbars#296]
Hi,

I have created my own custom component using overlay-scrollbar. In there I am trying to detect if the scrollbar reached end of the container. I have found one of your previous solutions where you have mentioned to check if the **y ratio is 1**. But in my custom component, on scroll event I am never getting 1 but the scrollbar is already reached end. This is the max number I am getting `0.9904761541457403`. 

I have tried the following but not getting ratio of 1. Any help would be appriciated.

```
private config : OverlayScrollbars.Options = {
    className            : "os-theme-dark",
    resize               : "none",
    paddingAbsolute      : true,
    normalizeRTL         : true,
    autoUpdate           : true,
    scrollbars : {
      visibility       : "auto",
      autoHide         : "move",
      autoHideDelay    : 800,
      dragScrolling    : true,
      clickScrolling   : true,
      touchSupport     : true
    },
    callbacks : {
      onScroll: () => {
        let scrollInfo = this._osInstance.scroll();
        console.log(scrollInfo.ratio.y);
      }
    }
  }
```

**Comment by KingSora** [comment]
Good day!

Can you send me a small example of your component / app on [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/)? I can remember that I've had a similar bug which I've fixed in the past already, so please make sure to use the latest release. Also checked it here in my fiddle and it works well: https://jsfiddle.net/mzLye41b/2/

**Comment by swagata1603** [comment]
Hi, Thank you for the reply, don't know what happened, in the demo StackBlitz it is also working fine, but in my local app it is not. Let me check my local app. Can you please the component that I have created if it is ok or not I am using the same component in my demo app. 

One more question how can I create a custom component for text area in angular. I have read your docs could not find anything that help me to create a text area component with overlay scrollbar.

[https://stackblitz.com/edit/angular-ivy-qqfuek?file=src/app/overlay-scrollbar.component.ts](https://stackblitz.com/edit/angular-ivy-qqfuek?file=src/app/overlay-scrollbar.component.ts)

Thank You.

**Comment by swagata1603** [comment]
@KingSora , Hi, can you please guide me , how I can create a component for textarea's with custom scrollbar

**Comment by KingSora** [comment]
@swagata1603 is your initial problem solved?

Regarding Textarea you can take a look at: https://github.com/KingSora/OverlayScrollbars/issues/167
You can also use a directive https://github.com/KingSora/OverlayScrollbars/issues/278 on a textarea which will give you the desired effect.

**Comment by swagata1603** [comment]
@KingSora Thank You
