### ISSUE TITLE
Uncaught ReferenceError: OverlayScrollbars is not defined

### ISSUE THREAD

**Issue by swagata1603** [KingSora/OverlayScrollbars#297]
I am trying to add os-scroll-chain extension in my angular app. But getting this error - `index.js:1 Uncaught ReferenceError: OverlayScrollbars is not defined`

I have added the cdn in my index.html - 
`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/os-scroll-chain@1/dist/os-scroll-chain.min.js"></script>`

I have added these in my main ts file 
```
import * as scrollChain from 'os-scroll-chain';
import OverlayScrollbars from 'overlayscrollbars';
OverlayScrollbars.extension('scroll-chain', scrollChain )
```

Then in my custom overlay scrollbar component I have used this - 

```
ngAfterViewInit() {
    this._osInstance = OverlayScrollbars(this.osTarget(), this.config || {});
    this._osInstance.addExt('scroll-chain', {vertical: true, horizontal: false})
  }
```

**Comment by KingSora** [comment]
Good day!

Please try to import `OverlayScrollbars` first, like:

```js
import OverlayScrollbars from 'overlayscrollbars';
import * as scrollChain from 'os-scroll-chain';
```

And I guess you don't need that line: `OverlayScrollbars.extension('scroll-chain', scrollChain)` this plugin does this for you already.

**Comment by swagata1603** [comment]
Hello Thank you for the response, I have done this in main.ts, but getting this error below.

```
import OverlayScrollbars from 'overlayscrollbars';
import * as scrollChain from 'os-scroll-chain';
```


![scroll-chain-error](https://user-images.githubusercontent.com/67018265/104869432-0cbd3a80-596c-11eb-9263-518126edc7e4.jpg)

**Comment by swagata1603** [comment]
@KingSora, Can you be able to provide any solution on this? if you can not then tell me I will close the issue.

**Comment by KingSora** [comment]
@swagata1603 I don't really know where this error is coming from. If I set up a example angular project everything works as expected: https://stackblitz.com/edit/angular-module-sandbox-lwehqx?file=src%2Fapp%2Fapp.component.ts

- in main.ts I'm registering the extensions:
```js
import OverlayScrollbars from "overlayscrollbars";
import "os-scroll-chain";
```
- app.component.html I'm using the component and I'm using `scroll-chain` as extension:
```html
<overlay-scrollbars #osComponentRef [extensions]="'scroll-chain'">
</overlay-scrollbars>
```

- app.component.ts I'm logging all the instances and infos
```ts
ngAfterViewInit() {
    const instance = this.osComponentRef.osInstance();
    console.log("osInstance:", instance);
    console.log("scroll chain instance:", instance.ext("scroll-chain"));
    console.log("all extensions", OverlayScrollbars.extension());
  }
```

I hope this helps.. I added the package via npm or yarn and didn't do it like you via CDN, maybe thats the issue on your side? You can do it simply with `npm i os-scroll-chain` or `yarn add os-scroll-chain`.

**Comment by swagata1603** [comment]
@KingSora , Thank you. You are Awesome. The error was occurring because i have injected the os-scrollchain js in my angular.json. now with the help from your example it works like charm.
