### ISSUE TITLE
Using OverlarScrollbars with Materialize

### ISSUE THREAD

**Issue by realleoman** [KingSora/OverlayScrollbars#30]
Hi:

I'm creating a new site using Materialize.css and there is one function I'm using, .sideNav(), (https://materializecss.com/sidenav.html)  which allows creating a slideout menu.  The issue here is when I include the OverlaysScrollbars css and js files on my code, I'm not able to access the elements inside of the menu for some reason. The result of including Overlays code is an sidenav-overlay class that covers all the screen and I can't click on each element on the menu.

Here is a small snippet of my code along with Overlays Scrollbars initialization.

$(document).ready(function(){
    $('.button-collapse').sideNav();
    $('.parallax').parallax();
    $('.collapsible').collapsible();
    // NOTE: m_slider = materialize slider, we rename it because it conflicted with jquery UI slider
    $('.slider').m_slider();
    $('.dropdown-button').dropdown({
          inDuration: 300,
          outDuration: 225,
          constrainWidth: false,
          hover: false,
          gutter: 0,
          belowOrigin: true,
          alignment: 'left',
          closeOnClick: true
      }
    );
    $('.settings-nav-btn').sideNav({
      menuWidth: 300,
      edge: 'right',
      closeOnClick: true,
      draggable: true,
    });
    $('body').overlayScrollbars({ 
      className: "os-theme-dark",
      scrollbars : {
        visibility  : "auto",
        autoHide  : "move",
        touchSupport  : true
      },
    });
 });

**Comment by KingSora** [comment]
Good day!

This bug happens, because Materialize is adding divs to the body element. Under normal circumstances this is absolutely okay, but if you're using OverlayScrollbars on the body element this can mess up things.

The solution is to move the added divs to the correct place: the generated `.os-content` div.
I've created two demos for you, since the API for this component is slightly different with different Materialize versions:

**Materialize 1.0.0-rc.1** : https://jsfiddle.net/Lo14gw4q/
**Materialize 0.100.2** : https://jsfiddle.net/wdyc2wxy/

**Comment by realleoman** [comment]
Awesome!!! That made it work... Great stuff you've built.. I have another question but I'll open a new thread for it..

**Comment by KingSora** [comment]
I'm glad I could help, I'll take a look on your other question as soon as possible!

**Comment by realleoman** [comment]
Hi @KingSora:

Founa new bug on this implementation.. After adding the code you sent me, there was one element I couldn't see on the page after installing OverlayScrollbars.


Here is a screenshot of the Quick Notes window floating in the bottom right part of the site
<img width="1230" alt="without scrollbars" src="https://user-images.githubusercontent.com/699501/39738969-f7b59e10-5253-11e8-9f10-2deaca46608a.png">

Then, after adding Overlay scrollbars, the div is still there but can't be seen. Any idea how should I initialize it to be shown?
<img width="1124" alt="with scrollbars" src="https://user-images.githubusercontent.com/699501/39738977-fae2801c-5253-11e8-8ea0-86c3dfef1805.png">


Here is part of the code implementation so you can take a look:

    var osBodyInstance = $('body').overlayScrollbars({ }).overlayScrollbars();
    var quicknotesElms = $('body > #quick-notes-widget');
    var osContentElmQN = $(osBodyInstance.getElements().content);
    osContentElmQN.append(quicknotesElms);
    $(".settings-nav-btn").sideNav({
      menuWidth: 300,
      edge: 'right',
      closeOnClick: true,
      draggable: true,
      onOpen: function() {
        var sidenavElms = $('body > .sidenav-overlay, body > #sidenav-overlay, body > .drag-target');
        var osContentElm = $(osBodyInstance.getElements().content);
        if (sidenavElms.length > 0 && osContentElm.length > 0) {
          osContentElm.append(sidenavElms);
        }
      }
    });
