### ISSUE TITLE
Can't get it working with div, b-table in vue

### ISSUE THREAD

**Issue by RoboVij** [KingSora/OverlayScrollbars#303]
I'm using overlayscrollbars-vue. `"overlayscrollbars": "^1.13.1", "overlayscrollbars-vue": "^0.2.2"`
I'm new to styling scrollbars. So wasted a lot of time and got it to work on the `<body>` like below, not sure if it's the right way.

`index.html`:

```
<body>
    <noscript>
      <strong>We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled.
          Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        OverlayScrollbars(document.querySelectorAll('body'), {
          className: "os-theme-dark os-theme-dark-edgy"
        });
      });
    </script>
  </body>
```

 But not able to get it to work on `div` and mainly with boostrap-vue `b-table`.

Component registration in `main.js`:

```
import 'overlayscrollbars/css/OverlayScrollbars.css';
import Vue from 'vue'
import App from './App.vue'
import router from "./router";

import { OverlayScrollbarsPlugin } from 'overlayscrollbars-vue';
Vue.use(OverlayScrollbarsPlugin);
```

`somefile.vue`:

```
<div id="test1" style="height: 300px; width: 500px; overflow: auto">
      <overlay-scrollbars>
      <!-- Tried this as well: <overlay-scrollbars :options="{ className: 'os-theme-dark' }"> -->
        <div v-for="n in 80" :key="n">aaa{{ n }}</div>
      </overlay-scrollbars>
    </div>
```

I'm sure I'm doing some very basic mistake, but can't figure it out myself. Help is much appreciated.

**Comment by KingSora** [comment]
Good day!

I'm not a expert with Vue, but your code looks good to me. Maybe you'll find a clue by taking a look at the Vue repo (with example): https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-vue

**Comment by RoboVij** [comment]
I did check it out multiple times before asking here. But I didn't find anything specific and I don't understand it fully either as it has lot of extra code (I think it's probably importing some code from the main `overlayscrollbars` project and it's deployed at a subroot on the main project's site so I didn't even find the code for scrollbar on `<body>`. I found it via google).

It'd be very helpful if you  (or anyone) could provide simple code without extra functionality, like a page with scrollbar on `<body>` and a scrollbar for a `<div>` like I presented above in the `somfile.vue`.

**Comment by KingSora** [comment]
I've created a small CodeSandbox for you: https://codesandbox.io/s/pensive-payne-1h7wr

Things I did:
1. Add dependencies `overlayscrollbars` and `overlayscrollbars-vue`
2. Add imports and `Vue.use` to the `main.js`:
```js
import "overlayscrollbars/css/OverlayScrollbars.css";
import { OverlayScrollbarsPlugin } from "overlayscrollbars-vue";

Vue.use(OverlayScrollbarsPlugin);
```
3. Go to the `HelloWorld.vue` component and use it as the root.
4. Make sure the OverlayScrollbars component doesn't grow with the content infinitely (added `max-height` style)
```html
<overlay-scrollbars style="max-height: 200px;">
<!-- ... -->
</overlay-scrollbars>
```

**Comment by RoboVij** [comment]
Wow! Thanks a lot. As I thought, just a basic mistake. Keeping `max-height` as you pointed in Step no. 4 and removing the `<div>` around it worked for me. 

Same goes to the `<body>` scrollbar. Your code worked, instead of changing the `index.html` as I did. I think it'd be helpful for new programmers like me if this is added in the documentation.

One last problem is with the `<b-table>`. It works fine normally, but doesn't work when I use `sticky-header` option (to add vertical scrollbar and keep the header titles visible while scrolling). I will look more into what the problem might be and check the other bootstrap related issues raised here but please suggest me if you've any solution on top of your head.

**Comment by KingSora** [comment]
I guess `b-table` is a different library you're using. The usual problem here is, that `b-table` doesn't know `OverlayScrollbars` and OverlayScrollbars also doesn't know `b-table`. 

Solutions for this kind of usecase are in general complex because each library works differently and has its own quirks. In `v1.x´ of this plugin I haven't really focused on this particular problem (although its working with many libraries), so you don't have that many possibilities.. but in `v2.0.0` I'll implement an interface where you'll have more freedom.

I can try making it work, but you'd have to create a minimal example on [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/).

**Comment by RoboVij** [comment]
Ya, I thought the same.

Here's a simple example: https://codesandbox.io/s/icy-surf-ecdd3
(Sharing a sandbox for the first time. Lemme know if there's any problem accessing it)

**Comment by RoboVij** [comment]
An update: My company is switching to Vuetify instead of bootstrap-vue. So, I don't need this `b-table` support anymore.

**Comment by KingSora** [comment]
@RoboVij alright, is it fine to close the issue then?

**Comment by RoboVij** [comment]
Yes
