### ISSUE TITLE
Fixed element inside scroll container draw over the scrollbar

### ISSUE THREAD

**Issue by Pipas** [KingSora/OverlayScrollbars#306]
I am trying to have an element inside the scroll content overflow outside this area, and to achieve this I give it position fixed and calculate it's position according to the viewport and it works.

However when the element overlaps with the scrollbars the scrollbars are drawn on top of it since the the `os-padding` z-index, which is the stacking context for any element inside of the scroll area is lower than the `os-scrollbar` context.

Since I'm only using an horizontal bar I found a work around by giving `os-padding` z-index of 2 and bottom of 6px so it doesn't overlap with the bar allowing it still to be selected. This appears to work correctly, although I'm not sure if it has any unintended side-effects yet.

Is there another way I can achieve this outcome without this workaround?

Any feedback is appreciated and thanks for the library, it's excellent for all my use cases!

**Comment by Pipas** [comment]
It appears my workaround does have many unintended consequences so for now my elements are being drawn under the scrollbars.

**Comment by KingSora** [comment]
Good day @Pipas!
The usage of `z-index` should be fine, but the `bottom: 6px` rule will definitely cause problems. Since its intended that scrollbars are always drawn above the content (because whats the concrete usecase of having partially covered scrollbars?) I don't have a solution from the top of my head. Maybe you could create a small example on https://jsfiddle.net/ so I could try out different things according to your usecase / example.

**Comment by Pipas** [comment]
Sorry for the late response I have been busy these past weeks.

An option I have encountered and started using is to use react portals to render the popup outside of the scrolling element from inside to not disrupt the logic. I used [this](https://www.npmjs.com/package/react-cool-portal) library to achieve this but you can just implement them in react. Here is the documentation for [react portals](https://reactjs.org/docs/portals.html).

**Comment by KingSora** [comment]
@Pipas glad to hear that you solved the problem, also thanks for sharing your solution! I guess this issue can the be closed?

**Comment by Pipas** [comment]
I guess so
