### ISSUE TITLE
Lagging: 2 Ways Data Binding with OS is Laggy on IE11

### ISSUE THREAD

**Issue by KiddoV** [KingSora/OverlayScrollbars#307]
**Describe the bug**
See the attached gif(s) below.
See that when data-binding without OS is very smooth, feel like instantly.
With OS, it's like 1-2 seconds delay there.  (Even with only 14 items on the array)
- I also tried osInstance.sleep() and osInstance.update(), still doesn't works.
-  On other browsers are very smooth.
- My project only target IE11.

**Environment**
Windows 7 | Jquery v3.5.1 | Knockout.js v3.5.1 (for data binding)
Also laggy on AngularJS as well.

**Additional context**
With OS:
![with-os](https://user-images.githubusercontent.com/28552977/109997187-8f5c4800-7cd5-11eb-85d3-37b4ec961933.gif)

Without OS:
![without-os](https://user-images.githubusercontent.com/28552977/109997337-b7e44200-7cd5-11eb-8128-98efadcae654.gif)

Any suggestion or work around for this issue would be nice!
Thanks,

**Comment by KingSora** [comment]
Hey @KiddoV,
sorry for the late reply..

I've no idea whats happening there, but since other browsers seems to be fine, I'm not sure whether I'll investigate this. If you want, you can create a small demo for me, where I can then test my suspicions.

**Comment by KiddoV** [comment]
Hi @KingSora 
Here is the demo: [OS-Issue.zip](https://github.com/KingSora/OverlayScrollbars/files/6243941/OS-Issue.zip)
Please open it with IE11. Thanks!

**Comment by Rajdeep97** [comment]
@KiddoV Why do you want to support a browser that's dead?

**Comment by KiddoV** [comment]
> @KiddoV Why do you want to support a browser that's dead?

I wish I can get rid of IE11 man, I really do. Unfortunately for me, some of my projects still need the Trident engine from IE to run.

**Comment by KingSora** [comment]
`v2` is released now, you can try if this version also casues this issue

**Comment by KiddoV** [comment]
Nice. Thank you!
