### ISSUE TITLE
Chrome Spacebar or Arrow keys doesn't scroll when scrollbar is clicked

### ISSUE THREAD

**Issue by aquaductape** [KingSora/OverlayScrollbars#310]
**Describe the bug**
When container is selected, Spacebar or Arrow keys will scroll container as expected. But when scrollbar is previously clicked,
Spacebar or Arrow keys doesn't scroll the container.

**To Reproduce**
1. Visit [demo page](https://kingsora.github.io/OverlayScrollbars/#!demos/basic).
2. Click content inside scrollable demo container.
3. Press Spacebar or Arrow keys to scroll, it will successfully scroll.
4. Now click scrollbar button or track and scroll a little bit.
5. Press Spacebar or Arrow keys.
6. Does nothing.

**Expected behavior**
On a native scrollbar, when the scrollable container is selected, pressing Spacebar or Arrow keys will always scroll the container, even after clicking the scrollbar. Caveat, if parent has been scrolled and then nested scrollable container's scrollbar is selected, keyboard will not scroll it.

Only tested on Firefox and Chrome. Chrome shows this bug.

**Environment**
 - Ubuntu 20.04.2 LTS x86_64
 - Kernel: 5.8.0-44-generic
 - Chrome 89.0.4389.82 (Official Build) (64-bit)

**Comment by KingSora** [comment]
Good day @aquaductape!

I've tested it, and it seems to be only happening in chrome. Firefox is fine. I'm not sure whether I can do someting about it, but I'll see what I can do.

**Comment by aquaductape** [comment]
Thanks! It's not a deal breaker for me, but it is good to keep as close to native scroll behaviors as possible.

**Comment by KingSora** [comment]
@aquaductape it seems that `tabindex="-1"` fixes this issue. You just have to add it to your target element.
