### ISSUE TITLE
How it work with Svelte

### ISSUE THREAD

**Issue by mxmvrnn** [KingSora/OverlayScrollbars#311]
I am trying to create a wrapper for Svelte, but upon initialization, my DOM is blocked. Guys who came across this have examples of initialization.

**Comment by KingSora** [comment]
@blackamlet Good day and sorry for the late answer.

I'm not very familiar with svelte, so I'm probably not the best guide for this issue..

**Comment by idiotWu** [comment]
You can use [actions](https://svelte.dev/tutorial/actions) to do this:

```js
// scrollbar.js
import OverlayScrollbars from 'overlayscrollbars';

export function scrollbar(node, options = {}) {
  const scrollbar = OverlayScrollbars(node, options);
  
  return {
    update(newOptions) {
      scrollbar.options(newOptions);
    },
    
    destroy() {
      scrollbar.destroy();
    },
  };
}
```

```svelte
<script>
  // App.svelte
  import { scrollbar } from './scrollbar';
  const options = { ... };
</script>

<div use:scrollbar={options}></div>
```

Online demo: https://svelte.dev/repl/a6dce67002354a8a9fc99b1b3e51609e?version=3.44.1

**Comment by KingSora** [comment]
Today I released `overlayscrollbars` `v2` which includes the new package [`overlayscrollbars-svelte`](https://www.npmjs.com/package/overlayscrollbars-svelte) :)
