### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by therealgilles** [KingSora/OverlayScrollbars#312]
**Describe the bug**
I am getting this JS warning when I resize the browser window. Depends on the window size, sometimes the sidebar gets hidden by CSS. Not sure if that has anything to do with it.

**To Reproduce**
The site isn't public so I cannot share it. Let me know if you need more information to track this down.

**Expected behavior**
I am not expecting any JS warning messages (unless I am doing something wrong).

**Environment**
 - Used Operating System(s): Mac OS 11.3 beta
 - Used Browser(s) (with version): Firefox 87.0

**Comment by KingSora** [comment]
Good day @therealgilles!

Which warning do you mean? Is it also appearing on the documentation page: https://kingsora.github.io/OverlayScrollbars/#!overview ?

**Comment by therealgilles** [comment]
This is the warning: "ResizeObserver loop completed with undelivered notifications"
but I think it may be coming directly from the browser.

Weirdly I don't see it in the JS console. It is only reported by the Debug Bar plugin I use on the WP site, so I'm not sure how to reproduce the behavior in a different environment. Sorry for not being more helpful.

**Comment by KingSora** [comment]
@therealgilles thats weird.. It could be connected to #90.. I'll look into it as soon as I have time

**Comment by therealgilles** [comment]
@KingSora: I see the scrollbar area sometime disappear on window resize because of this:

```CSS
.os-host-overflow {
    overflow: hidden !important;
}
```

Is there a way to re-init the scrollbar on resize?

**Comment by therealgilles** [comment]
I was able to use the destroy() function to remove the instance on resize and re-create a new one. I also avoid creating an instance when I actually do not want the scrollbar, based on a screen size breakpoint. With these two changes, the warnings have disappeared :)

**Comment by therealgilles** [comment]
I think the warning occurs if something changes in the layout (window resize for instance) and the scrollbar is not necessary anymore or necessary again. In my case, I have a grid layout with two columns. I want the second column to have a minimum height but not be longer than the first column (if the first column is longer than the min height). I use a flexbox to make it work and put the scrollbar on the second column if it overflows.

Now in some situations, the first column length will change when it contains tabs and the user switches between them. Based on the length of the tab content, the scrollbar will switch from being required to not being required. Some of the switches create warnings and the scrollbar only reappears every other time somehow.

I can probably hook up another destroy/recreate on the tab click handler to workaround the issue. Or maybe fix the height of the second column once the scrollbar is initialized the first time.

**Comment by KingSora** [comment]
`v2` released today where this issue is hopefully fixed.
