### ISSUE TITLE
how to show horizontal scrollbar in both side top and bottom of div

### ISSUE THREAD

**Issue by saeed410** [KingSora/OverlayScrollbars#323]
hi.
how to show horizontal scrollbar in both side top and bottom of a div.

**Comment by KingSora** [comment]
Good day @saeed410 

Well.. the library wasn't really build to display two scrollbars of the same kind in two differen places at once.. You'd have to somehow clone the existing one with all its listeners.

**Comment by KingSora** [comment]
@saeed410 this feature was added in `v2` :)

**Comment by rlconst** [comment]
@KingSora I don't see anything in documentation about enabling both scrollbars. How it's possible to do?

**Comment by KingSora** [comment]
@rlconst in `v2` its possible to clone scrollbars and position them wherever you want.

Please open a new issue for your problem

**Comment by khairaf** [comment]
wondering on how to clone a bottom scrollbar of a table and position them at the top of the table to get horizontal scrollbars in both side top and bottom..
