### ISSUE TITLE
Scrolling will not update on display: none element

### ISSUE THREAD

**Issue by SourceCipher** [KingSora/OverlayScrollbars#329]
**Libraries**
All latest

**Issue**
When the element is set to `display: none` via css, the scrollbar will not update at all even with update(force) or update() calls.

**To replicate**
You can go on the libraries website here https://kingsora.github.io/OverlayScrollbars/#!demos/scroll and add the style  `display: none` to the `id='scroll-demo-plugin'` element. When you press the buttons to scroll to various positions it will not scroll even tho the element is there but not visible.

**Why should it work?**
Hiding elements via `display: none` is a very common way to optimize mounted components in react, especially using tabs. We have many tables which are within the tabs and we do scrolling in multiple tables even when they are not visible. 

In the past it was working fine with default offsets, but with this library, I cant make it to work no matter what. It will only scroll to row when the table is in view.

**Comment by KingSora** [comment]
Good day @SourceCipher 

So your goal is to change the scroll offset of a element while it is set to `display: none`?

**Comment by SourceCipher** [comment]
Hi @KingSora,

Thanks for your quick response. You are right, but it seems like even trying to update the scrolling in the onUpdated callback or when I switch the tabs to go to the table and scroll it it doesnt update as well. 

For example we have a func to scroll to a selected row and when you switch the tab, I have tried to call that func to scroll in onUpdated callback which is fired after the tab is switched and the table gets into a view. That does not work as well for some reason. I can see if I can create a demo for that if necessary

**Comment by KingSora** [comment]
@SourceCipher yes please create a demo.. then I can work out the best solution possible. 😄

**Comment by SourceCipher** [comment]
Actually I made it work and I am using the `onUpdated` callback to scroll to the row if the table is visible.. I think the issue was that it was scrolling when the table was in display none mode and react wasnt updating it properly.

This is not an issue with the library as its more with our project, the way we integrated I would think. Thanks for your speedy support!

**Comment by KingSora** [comment]
I'm glad everything is working now :)

**Comment by LeonGus** [comment]
> I'm glad everything is working now :)

I had the same problem， demo（https://jsfiddle.net/leon0613/knx1s6ag/22/）
Operation path ->  Click the (hide, scroll, show) button -> Click the (scroll x+=20) button -> Click the  (hide, scroll, show) button to display the dom -> Click the (scroll x+=20) button; At this time, the scroll method has failed.
