### ISSUE TITLE
Scroll bar does not update itself accurately

### ISSUE THREAD

**Issue by adirkandel** [KingSora/OverlayScrollbars#33]
I'm developing a product with a feed/wall of posts and i'm loading the images with lazy loading.
The scroll bar is getting "crazy" every time an image is loaded, it goes up and down and sometimes i can't reach the end of the feed or in some cases i have a gap between the end of the bar to the actual end of the feed.

What is the problem and what can i do?

Try to make a simple feed with lazyload images async and you will see.

**Comment by KingSora** [comment]
Please try [this](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.4.0) version of the plugin and tell me if this problem still exists.
I've added a feature in `version 1.4.1` where async loaded images are now detected and the plugin gets updated after a load. (I'm basically listening to the `load` event of the `<img>` element.) This feature is still in beta, so there can be unexpected behaviors. Please try the version above and tell be how the plugin is reacting.

**Comment by KingSora** [comment]
Any updates on this issue?

**Comment by KingSora** [comment]
I'll close this issue for now. If you have any updates on this, feel free to comment them and I'll reopen it.
