### ISSUE TITLE
os-content-glue extremely laggy width change

### ISSUE THREAD

**Issue by whoisme555** [KingSora/OverlayScrollbars#331]
When adding a slide out panel on my app as shown in the gif, the os-content-glue width slowly ticks down. The width transition on the panel is set for .3s, but it ends up taking 5+ seconds to complete. Any idea why this might be happening?

![slow scrollbar width](https://user-images.githubusercontent.com/50149901/117190598-a559b800-adad-11eb-8a3f-ea6d7e15736b.gif)

**Comment by KingSora** [comment]
Good day @whoisme555 :) 
Do you mind creating a minimal example on [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/)? Its hard for me to analyze the problem only from your gif.

**Comment by whoisme555** [comment]
Sorry, @KingSora I went to make a jsfiddle just a second ago and not only is it not reproducible there, it's not reproducible in my own solution. I'm operating under the assumption that my computer decided it was giving up on the day I took this gif haha
