### ISSUE TITLE
Unfixed-heighted host's height become 0 due to a flex parent

### ISSUE THREAD

**Issue by ianthedev** [KingSora/OverlayScrollbars#332]
**Describe the bug**
When the parent element has the CSS `display: flex` declaration and the host's height is unfixed, the host cannot be seen because its height becomes 0.

**To Reproduce**
1. Set CSS declaration `display: flex` on the parent element.
2. Do not set any height on the host element (.os-host)

**Expected behavior**
The host element should remain in sight.

**Examples**
[CodePen example](https://codepen.io/IanY/pen/MWpYrpz). You can use your browser's developer tool to toggle the CSS `display: flex` declaration and see the difference.

**Environment**
 - Used Operating System(s): Windows 7
 - Used Browser(s) (with version): Mozilla Firefox and Google Chrome

**Comment by KingSora** [comment]
Good day @ianthedev :)
OverlayScrollbars has troubles with `flexbox` and `grid` layouts. In `v2.0.0` this will probably be completely solved, but until then you have to add the class `os-host-flexbox` to your target element, if its a flexbox item. You can read more about it in the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/flexbox). 

Until then you can fix your issue by initializing it like:
```js
$('ul').addClass('os-host-flexbox').overlayScrollbars({})
```

**Comment by ianthedev** [comment]
@KingSora Thanks for the tip!
