### ISSUE TITLE
Error when initiating on .selectize-dropdown-content

### ISSUE THREAD

**Issue by Briareos17** [KingSora/OverlayScrollbars#34]
Hi. I'm trying add scrollbar to selectize dropdown but get error:

Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
selectize - library for custom select: [https://github.com/selectize/selectize.js](url)

**Comment by KingSora** [comment]
Alright, I've found the error and this is happening only in the non-jQuery version of this plugin.
This problem will be fixed in `version 1.4.5`. Although your problem should be fixed faster by the fiddle I've posted above.

**Comment by Briareos17** [comment]
Thanks a lot, I'm already foun similar solution as you show in jsfiddle.
