### ISSUE TITLE
How to scroll a OverlayScrollbars area by using mousewheel on a non-OverlayScrollbars area?

### ISSUE THREAD

**Issue by ianthedev** [KingSora/OverlayScrollbars#346]
The [Capabilities Demo](https://kingsora.github.io/OverlayScrollbars/#!demos/capabilites) demonstrates a feature which allows you to scroll a non-OverlayScrollbars area by using mousewheel on a OverlayScrollbars area.

What I need is the other way around. I need to scroll a OverlayScrollbars area by using mousewheel on a non-OverlayScrollbars area. Is that possible?

**Comment by KingSora** [comment]
Good day @ianthedev 

Its definitely possible, listen to the scroll event on your non-OverlayScrollbars element, and set its scroll offset as the scroll offset of the OverlayScrollbars element: https://jsfiddle.net/pwd2hu3y/
