### ISSUE TITLE
Is $(window).resize() the only way to correct the horrizontal scrollbar's width?

### ISSUE THREAD

**Issue by ianthedev** [KingSora/OverlayScrollbars#348]
When my container is being initialized, it is in the hidden state (because of its [`hidden` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden)). After I removed the `hidden` attribute, the horizontal scrollbar's width is not correct. That's totally understandable.

My question is: Is `$(window).resize()` the only way to correct the horizontal scrollbar's width? I tried the [`update` method](https://kingsora.github.io/OverlayScrollbars/#!documentation/method-update) and that does not help.

**Comment by KingSora** [comment]
Good day @ianthedev 

Is it possible for you to setup a minimal example on [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/) for me? The library should be able to handle size changes..

**Comment by ianthedev** [comment]
@KingSora My mistake. Actually it's not OverlayScrollbars' problem and is also not fixed by `$(window).resize()`.
