### ISSUE TITLE
About new releases.

### ISSUE THREAD

**Issue by jsieler** [KingSora/OverlayScrollbars#35]
I like the way you support us, and how you're fixing the bugs, but it is annoying how new versions are released. For example, version 1.4.3 to 1.4.4, jQuery Release... What changed? Nothing, but new version was released. That confusing a lot... May be you should separate this versions, also jquery one and vanilla?

**Comment by jsieler** [comment]
I'm not saying that it is that bad, but just confusing a little bit. Thinking like, hey, new version is there... After adding new version to source you notice... Only version has changed :D

**Comment by KingSora** [comment]
Alright, I'll write now everytime if only a certain version has changed, to prevent any confusion. I hope this is a way in which we both will be happy.
