### ISSUE TITLE
add support for react 17

### ISSUE THREAD

**Issue by metrocoding** [KingSora/OverlayScrollbars#350]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KingSora** [comment]
Well, the plugin supports `react 17`.. The peer Dependencies just need an update

**Comment by jesec** [comment]
Indeed. It works with React 17 flawlessly. 

However, due to the npm 7 behavior change on `peerDependencies`, we would have this error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.4.0" from overlayscrollbars-react@0.2.2
npm ERR! node_modules/overlayscrollbars-react
npm ERR!   dev overlayscrollbars-react@"^0.2.2" from the root project
```

@KingSora Would you mind to release a new version that relaxes the peerDependency?
