### ISSUE TITLE
Back To Top functionality doesn't work with Scrollbars

### ISSUE THREAD

**Issue by 01Kuzma** [KingSora/OverlayScrollbars#353]
Hello!
There is a bug or configuration conflict.
My website theme has `Back To Top` button.
I'm using Gantry 5 Framework based on Grav CMS. Here is a [demo](http://demo.gantry.org/), how the `Back to top` function is made:

The problem is that on my website `Back To Top` doesn't work once `OverlayScrollbars` is loaded. Clicking on anchor makes nothing and there are no errors in the console.

I'm initializing `scrollbars` like this:
```

$(function() {	
	$("body").overlayScrollbars({
          className: "os-theme-light custom-scroll",
        });
});
```

**Comment by KingSora** [comment]
Good day @01Kuzma.

If you apply the plugin to your target, then it creates helper elements which have different responsibilities. One of the is the `viewport` element which is doing the actual scrolling. Currently your back to top button is changing the scroll offset of the `window / html / body` element, but because the plugin created its own element (`viewport`) for it, the button has to change the offset of that element. You can get the `viewport` element like this:

```js
var osInstance = $("body").overlayScrollbars({
  className: "os-theme-light custom-scroll",
}).overlayScrollbars();

var viewportElement = osInstance.getElements().viewport;
```

**Comment by 01Kuzma** [comment]
@KingSora thank you for your support!
Unfortunately, I'm not able to fix it...
I've change the `init` code to this:

```
$(function() {	
	var osInstance = $("body").overlayScrollbars({
	  className: "os-theme-light custom-scroll",
	}).overlayScrollbars();

	var viewportElement = osInstance.getElements().viewport;
});
```

and `Back to Top` still doesn't react...
I'm not sure, does it init properly...
![image](https://user-images.githubusercontent.com/569504/120096457-54cb4580-c134-11eb-9dec-2c8ebae928f9.png)

**Comment by 01Kuzma** [comment]
@KingSora any thoughts?

**Comment by KingSora** [comment]
@01Kuzma the code I wrote to you was not the entire code to fix the problem. It was just the code to get the `viewport` element, not the entire code... Did you write the code for the "back to top" button yourself or is it a plugin?

**Comment by 01Kuzma** [comment]
@KingSora, understood. It's a plugin from the `Gantry 5` framework

**Comment by KingSora** [comment]
@01Kuzma I could write you a simple back to top function which you can assign to your buttons `click` event if you like

**Comment by 01Kuzma** [comment]
@KingSora that would be awesome 👍

**Comment by KingSora** [comment]
```js
function backToTopBtnClick() {
  var osInstance = $('body').overlayScrollbars();
  if (OverlayScrollbars.valid(osInstance)) {
    osInstance.scroll({ top: 0 }, 1000);
  }
  else {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}
```

**Comment by 01Kuzma** [comment]
@KingSora thahk you!
I've added the `onclick="backToTopBtnClick();"` event to link, everything works just fine 👍
