### ISSUE TITLE
The bottom menubar on some browsers on mobile (like Safari) stays fixed when using OverlayScrollBars

### ISSUE THREAD

**Issue by Anam0927** [KingSora/OverlayScrollbars#356]
**Describe the bug**
The bottom tray or menubar that's present on some mobile browsers like Safari doesn't vanish while using the library. It remains fixed. 

**Expected behavior**
Normally, the bottom bar would only appear when scrolling up and slide down and hide itself when scrolling down...

**Environment**
 - Used Operating System(s): iOS or android
 - Used Browser(s) (with version): Safari on iOS. Can try with Brave on android

**Comment by KingSora** [comment]
Good day @Anam0927.

Thats a quirk of the library itself (related to how it works) which can't be fixed without a breaking change. Thus this will be fixed with version `2.0`, but I can't do anything against it for now.

**Comment by Anam0927** [comment]
Oh, I see...
Will be awaiting the `2.0` version then... I don't want to change my awesome scrollbar to native just for this...
😃

**Comment by hoangtrung99** [comment]
@KingSora 
Hi sir, 
this issue seems to still exist, doesn't it? I am using the latest version and still encountering this problem.
