### ISSUE TITLE
Focus on element with autofocus attribute gets lost after scrollbar init

### ISSUE THREAD

**Issue by AgentSmith0** [KingSora/OverlayScrollbars#357]
Hello.
When I initialize OverlayScrollbars the focus of my input element with autofocus attribute gets lost. I had to focus it via JavaScript manually after the initialization. Is there a way to prevent the autofocus lost?

**Comment by KingSora** [comment]
Good day @AgentSmith0 

To which element did you initialize OverlayScrollbars?

**Comment by AgentSmith0** [comment]
I assigned it to the body, maybe this it the problem?

**Comment by KingSora** [comment]
@AgentSmith0 yeah, on body I'm indeed switchting focus because of some other issues in the past.. Unfortunately I don't have real fix for you.. you would have to switch the focus by yourself manually again:

```js
const focusedElement = document.activeElement;

/* OverlayScrollbars initialization here */

focusedElement.focus();
```

**Comment by AgentSmith0** [comment]
I made already a workaround like yours. Anyway, thank you for your help!

**Comment by KingSora** [comment]
@AgentSmith0 can you please provide a minimal usecase on `jsfiddle` or a similar service? I would again take a look on it

**Comment by KingSora** [comment]
@AgentSmith0 should be fixed: https://7gr2xq.csb.app/
