### ISSUE TITLE
Reduce the humongous size of the library

### ISSUE THREAD

**Issue by xeoneux** [KingSora/OverlayScrollbars#362]
**Is your feature request related to a problem? Please describe.**
I used this library in my project simply to move away from default scrollbars on windows. After adding it, I see that this is the largest library in my whole application which has more than 20 deps!

**Describe the solution you'd like**
Is there any way to reduce the library size or maybe I'm doing something wrong? Is this a known issue?

**Describe alternatives you've considered**
I haven't considered any alternatives but the 360.24KB of JS and 25.09 KB of CSS (totalling 385.33KB) bloat definitely means I cannot afford it.

**Additional context**
Attaching visualiser screenshot:

![Screenshot_20210609_111236](https://user-images.githubusercontent.com/3099626/121300090-fc562e00-c913-11eb-91fb-d4786ed3c20e.png)

**Comment by KingSora** [comment]
Good day @xeoneux 

There was a similar issue in the past (#55) where I described a little bit the sturcture of the library etc. and why it is currently as big as it is. This won't change until `v2` is released, because it would require a whole rewrite (which I'm doing for `v2` anyway). I'm planning to release version 2 at the end of the year.

**Comment by KingSora** [comment]
@xeoneux good news, `v2` is now in beta and the size was reduced significantly. Even without treeshaking its 50% smaller than `v1`. You can see a comparison here: https://bundlephobia.com/package/overlayscrollbars keep in mind that depending on what you import the size is even lower

**Comment by xeoneux** [comment]
That's so amazing @KingSora! Thanks a lot, I'm going to update the lib to try out the beta this week 🚀
