### ISSUE TITLE
[React Nested scrollbars] Child component width doesnt perform right

### ISSUE THREAD

**Issue by ooo2003003v2** [KingSora/OverlayScrollbars#363]
Hello there.
I'm having trouble making a nested scrollbars with flex box react table with fix header. But the horizontal scroll for the table body doesnt has the size with the parent element. Any idea of how to fix it?
![image](https://user-images.githubusercontent.com/55082067/121638043-e899fb80-cabc-11eb-845d-d6e842b62a61.png)

```
```

**Comment by KingSora** [comment]
Good day @ooo2003003v2 

Can you share a minimal example on [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/) with me? Like this can't really help you.

**Comment by KingSora** [comment]
@ooo2003003v2 any feedback here?

**Comment by ooo2003003v2** [comment]
> @ooo2003003v2 any feedback here?

I've fix that by controling the width css with checking if the window width is smaller than tbody width.
