### ISSUE TITLE
Height not updating...

### ISSUE THREAD

**Issue by glassesUSA** [KingSora/OverlayScrollbars#370]
![image](https://user-images.githubusercontent.com/76479522/123765116-19a46980-d8ce-11eb-9bea-8e7bc2b3aec5.png)

For some reason this height is not updating to be the height of the window causing scroll where I do not want

**Comment by KingSora** [comment]
Good day @glassesUSA 

Can you provide a a minimal example on [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/)? Otherwise I can't really help you.

**Comment by glassesUSA** [comment]
Apologies the issue was in my end
