### ISSUE TITLE
Refresh on swipe down

### ISSUE THREAD

**Issue by glassesUSA** [KingSora/OverlayScrollbars#376]
When this is applied on mobile I am unable to swipe down to refresh the page... Is there a way to fix this?

**Comment by KingSora** [comment]
Good day @glassesUSA!

This is a restriction of `v1` but should be possible in `v2`.

**Comment by glassesUSA** [comment]
Is there an eta on v2?

**Comment by KingSora** [comment]
@glassesUSA I planned to finish it this year..

**Comment by KingSora** [comment]
`v2` released today where this issue should be fixed :)
