### ISSUE TITLE
Detached HTMLImageElement Memory Leak

### ISSUE THREAD

**Issue by tryggvigy** [KingSora/OverlayScrollbars#377]
**Describe the bug**
It seems OverlayScrollbars accumulates references to HTMLImageElements over time that do not get cleaned up when the images no longer exist in the DOM. https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L4120

**To Reproduce**
In a long virtually scrolled list that contains images:

![image](https://user-images.githubusercontent.com/2373958/125350981-09b96a80-e34f-11eb-9d3e-91c051b9ade8.png)
Snapshot 1: loaded first page.
Snapshot 2: scrolled down to the 1000th item
Snapshot 3: forced garbage collection
Snapshot 4: after pausing in code and called `_updateOnLoadElms.length = 0;`
Snapshot 5: forced garbage collection

**Expected behavior**
No memory to leak due to tracking HTMLImageElement load events

**Additional context**
As expected, the issue is not present when `updateOnLoad: null` option is passed.

**Comment by KingSora** [comment]
Good day @tryggvigy!

I realized that too as I reworked that in `v2` but thought that this might not be an issue in reality.. Seems like I was wrong 😄.
I'll try my best to fix it asap. Do you mind creating an minimal example somehwere so I'm not left with just my gutfeeling?

**Comment by KingSora** [comment]
@tryggvigy I believe I've fixed the issue, can you confirm it?
Here is an updated Sandbox: https://codesandbox.io/s/overlayscrollbars-memory-leak-forked-3gu4r?file=/src/index.js

**Comment by KingSora** [comment]
@tryggvigy should I wait for your feedback or is an blind update also fine for you? 😄

**Comment by tryggvigy** [comment]
Sorry @KingSora! I've been on summer vacation, I'll take a look this week to verify. Feel free to merge regardless of course! Thanks for taking a look at this!

**Comment by KingSora** [comment]
@tryggvigy no worries, I'll wait for your feedback.. I guess we aren't in a rush with this

**Comment by tryggvigy** [comment]
@KingSora I haven't had time to check on this properly! The codesandbox looks good though. A blind update is fine by me!

**Comment by ZoltanDobrovolni** [comment]
Hi @KingSora 
Is there any update regarding this issue?
(I am tracking a memory leak as well, and see the OverlayScrollbars name plenty of time in Snapshots. So would be great if I could check it again after this bug is fixed)
Thank you in advance!

**Comment by tryggvigy** [comment]
@ZoltanDobrovolni if you pass  `updateOnLoad: null` in the options, do you still see `OverlayScrollbars` a lot in the snapshots?

**Comment by ZoltanDobrovolni** [comment]
@tryggvigy 
Yes, I still can see the `OverlayScrollbars` in the Retainers
![image](https://user-images.githubusercontent.com/39996317/141067010-988f5881-a599-473d-abfb-bcbe45e0e3cc.png)
In the picture above, `update` and `_base.addExt` methods are the "key players".

![image](https://user-images.githubusercontent.com/39996317/141068291-e04529ce-14be-495f-ada8-8a69a62c913e.png)
In the picture above, `_plugin = window[PLUGINNAME] = function (...)` method is the refered method.

My package.json
`overlayscrollbars-vue": "^0.2.2"`

My options: 
```
{
            className: 'my-theme',
            resize: 'none',
            sizeAutoCapable: true,
            clipAlways: true,
            normalizeRTL: true,
            paddingAbsolute: false,
            autoUpdate: null,
            autoUpdateInterval: 33,
            // updateOnLoad: ['img'],
            updateOnLoad: null,
            nativeScrollbarsOverlaid: {
                showNativeScrollbars: false,
                initialize: true,
            },
            overflowBehavior: {
                x: this.scrollX ? 'scroll' : 'hidden',
                y: this.scrollY ? 'scroll' : 'hidden',
            },
            scrollbars: {
                visibility: 'auto',
                autoHide: 'never',
                autoHideDelay: 800,
                dragScrolling: true,
                clickScrolling: false,
                touchSupport: true,
                snapHandle: false,
            },
            textarea: {
                dynWidth: false,
                dynHeight: false,
                inheritedAttrs: ['style', 'class'],
            },
            callbacks: { ... },
        }
```

Shall I create an another issue for this?
Thank you!

**Comment by souphuhn** [comment]
Let me dig out that topic again, because I just updated to the latest versions (because of Vue3)

@KingSora  So previously I did `updateOnLoad: null,`. How does it look like with the latest **Options**? Is this still necessary to
avoid that mentioned menory leak above?

```
update: {
      elementEvents: [['img', 'load']],
      debounce: [0, 33],
      attributes: null,
      ignoreMutation: null,
},
```

**Comment by KingSora** [comment]
@souphuhn The leak won't happen in any version anymore. `updateOnLoad: null` was just a workaround. The equivalent to that would be:
```js
update: {
      elementEvents: null,
},
```

**Comment by souphuhn** [comment]
Thanks a lot. I will go with `elementEvents: null`.
