### ISSUE TITLE
Add support for Vue.js 3

### ISSUE THREAD

**Issue by glen-84** [KingSora/OverlayScrollbars#390]
**Is your feature request related to a problem? Please describe.**
The library doesn't appear to support Vue.js 3 (based on the peer dependencies, at least).

**Describe the solution you'd like**
Add support for Vue.js 3.

**Describe alternatives you've considered**
Using the base library, and writing my own component/directive.

**Additional context**

(unrelated: Looking forward to a lighter-weight v2)

**Comment by KingSora** [comment]
@glen-84 
Good day!

As far as I know Vue3 has still the same API as Vue2, so in theory it should work.
I'll take a deeper look as soon as I have time!

**Comment by glen-84** [comment]
I'm not sure, but at a minimum, the peer dependency would need to be updated.

I created a simple component for now:

```vue
<template>
    <component :is="tag" ref="element">
        <slot />
    </component>
</template>

<script lang="ts" setup>
import "overlayscrollbars/css/OverlayScrollbars.css";
import {assert} from "@sindresorhus/is";
import OverlayScrollbars from "overlayscrollbars";
import {onMounted, onUnmounted, ref} from "vue";

defineProps({
    tag: {
        type: String,
        default: "div"
    }
});

const element = ref<HTMLElement | null>(null);
let instance: OverlayScrollbars | null = null;

onMounted(() => {
    assert.domElement(element.value);
    instance = OverlayScrollbars(element.value, {});
});

onUnmounted(() => {
    instance?.destroy();
});
</script>

<style lang="scss">
.os-viewport {
    overscroll-behavior-block: contain;
}
</style>
```

**Comment by doutatsu** [comment]
Bump for this. Trying to use the library with vue3 throws:
`The requested module '/node_modules/overlayscrollbars/js/OverlayScrollbars.js' does not provide an export named 'default'`

**Comment by doutatsu** [comment]
Another bump on this - things have been quiet for a long time now. And Vue 3 is the default now, so sounds like it's about time to make this a higher priority?

**Comment by cjnarvaez22** [comment]
+1 for vue 3 support

**Comment by arifineu** [comment]
any updates for Vue 3 support?

**Comment by ddenev** [comment]
> As far as I know Vue3 has still the same API as Vue2, so in theory it should work.
No, it doesn't. Importing immediately fails because in `OverlayScrollbarsComponent.vue` you have:
```js
import Vue, { VueConstructor, VNode, CreateElement, PropType } from 'vue';
```
and this import no longer is valid in Vue 3.

Could you please share your plans on adding Vue 3 support as I need to make a decision on using this lib?

Thank you.

**Comment by KingSora** [comment]
@ddenev I'll try to release a vue3 version soon :)

**Comment by ErmiasF** [comment]
@KingSora have you done?

**Comment by KingSora** [comment]
I've pushed the changes to github but haven't released them yet. After fine tuning I'll release `v0.3.0` of the plugin which has vue3 support. In the next days it should be done

**Comment by KingSora** [comment]
I've release `overlayscrollbars-vue` version `0.3.0` which has vue3 support.

**Comment by AlmaFenetre** [comment]
Re-open, our application still uses Vue2 and this new minor version is not compliant with Vue2. Minor version changes are committed to our application automatically, so this update breaks the application. This version should have been released as a major version change since it contains breaking changes.

**Comment by bobvandevijver** [comment]
@AlmaFenetre  [Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.](https://semver.org/#spec-item-4)

I believe your automated tool needs some adjustments...

**Comment by AlmaFenetre** [comment]
Thanks for your reply, I will make sure no automatic minor updates are done for this package.
