### ISSUE TITLE
How to integrate infinite scroll feature with OverlayScrollbars

### ISSUE THREAD

**Issue by AnhTuan-AiT** [KingSora/OverlayScrollbars#398]
Hi, thanks for this useful tool. I'm trying to integrate infinite scroll feature using the library **react-infinite-scroller** or **react-infinite-scroll-component**. I searched but didn't find any information on how to integrate, I also tried to integrate but no success. Can you guide me how to do that?

**Comment by AnhTuan-AiT** [comment]
Thank @JasonasIgn for your suggestion. I tried this but it still not work as expected. Here is my sample sandbox: https://codesandbox.io/embed/festive-dubinsky-t1948?fontsize=14&hidenavigation=1&theme=dark

**Comment by sbkl** [comment]
Giving an id to the OverlayScrollbar component and targeting the children ".os-viewport" of that element works for me.

`scrollableTarget={document.getElementById("target-sidebar")?.querySelector(".os-viewport")}`

Also made sure the dataLength prop was the length of the current data fetched. Not the total data to pull from. Wasn't clear from the docs.

Below the code:

```
    <OverlayScrollbarsComponent
      id="target-sidebar"
      className="relative h-full flex-1"
      options={{
        nativeScrollbarsOverlaid: {
          initialize: true,
        },
        scrollbars: { autoHide: "scroll" },
      }}
    >
      <InfiniteScroll
        dataLength={data.length}
        className="h-full flex-1"
        next={showNextPage}
        hasMore={hasMoreData}
        loader={<h4>Loading...</h4>}
        scrollableTarget={document
          .getElementById("target-sidebar")
          ?.querySelector(".os-viewport")}
      >
       ...
      </InfiniteScroll>
    </OverlayScrollbarsComponent>
```
