### ISSUE TITLE
Issue with a floating element on body

### ISSUE THREAD

**Issue by realleoman** [KingSora/OverlayScrollbars#40]
Hi @KingSora:

Found new bug on this implementation.. After adding the code you sent me, there was one element I couldn't see on the page after installing OverlayScrollbars. It is a floating element which is attached to the body after the construction of body.

Here is a screenshot of the Quick Notes window floating in the bottom right part of the site BEFORE adding OverlayScrollbars:
<img width="1230" alt="39738969-f7b59e10-5253-11e8-9f10-2deaca46608a" src="https://user-images.githubusercontent.com/699501/40013265-b4eeeeb4-5772-11e8-950f-da51f345bb27.png">

Now, there is a screenshot of the same floating window AFTER OverlayScrollbars:
<img width="1124" alt="39738977-fae2801c-5253-11e8-8ea0-86c3dfef1805" src="https://user-images.githubusercontent.com/699501/40013283-bf8e206a-5772-11e8-9e6e-467f159d0c5c.png">

Here is how I declared the Quick Notes div on my initial javascript OverlayScrollbars file. It doesn't show when the page loads the first time but the quick notes DIV is shown after clicking on the sideNav element:

```
var osBodyInstance = $('body').overlayScrollbars({ }).overlayScrollbars();
var quicknotesElms = $('body > #quick-notes-widget');
var osContentElmQN = $(osBodyInstance.getElements().content);
osContentElmQN.append(quicknotesElms);
$(".settings-nav-btn").sideNav({
  menuWidth: 300,
  edge: 'right',
  closeOnClick: true,
  draggable: true,
  onOpen: function() {
    var sidenavElms = $('body > .sidenav-overlay, body > #sidenav-overlay, body > .drag-target');
    var osContentElm = $(osBodyInstance.getElements().content);
    if (sidenavElms.length > 0 && osContentElm.length > 0) {
      osContentElm.append(sidenavElms);
      osContentElm.append(sidenavElmsQN);
    }
  }
});
```

And this is the JS that attaches the quick notes to the main body of the page.
```
updateQuickNoteCounter = (inc) ->
  countEl = $('#quick-notes-count')
  countEl.html(parseInt(countEl.html()) + inc) # update counter in header

$ ->
  $(document).on 'click', '.quick-notes-header', ->
    $(this).parent().toggleClass('expanded')

  $(document).bind 'quick-notes:create', (e, html) ->
    $('.quick-notes-body ul').prepend(html)
    $('.quick-notes-body textarea').val('').trigger('mouseover'); # reset form, trigger mouseover need to reset counter
    updateQuickNoteCounter(1)

  $(document).bind 'quick-notes:remove', (e, id) ->
    $('#' + id).remove()
    updateQuickNoteCounter(-1)

```

Any idea how Can I fix it to support this Floating element when the page loads the first time?

**Comment by KingSora** [comment]
Good day!

Well the fix has to be the same as the fix for the sideNav. After your `quick-notes-widget` is loaded, you have to put it into the `os-content` element which is generated by the plugin. 

Please make sure every selector is correct (try to change the selector from `body > #quick-notes-widget` to `#quick-notes-widget`). If this isn't working, check if the code which is initializing and attaching the quick-notes-widget to the body runs before this code:

```javascript
var osBodyInstance = $('body').overlayScrollbars({ }).overlayScrollbars();
var quicknotesElms = $('body > #quick-notes-widget');
var osContentElmQN = $(osBodyInstance.getElements().content);
osContentElmQN.append(quicknotesElms);
```

**Comment by realleoman** [comment]
Awesome dude! It worked as you suggested. My issue was that the floating element was loading at the very end of my page loading and even after the document.ready() (using a partial from rails) so for that reason I wasn't able to include it into the body.  

Thanks again for your swift response and incredible attitude! Keep the good work!

**Comment by KingSora** [comment]
I am glad I could help you!
