### ISSUE TITLE
Flickers or height changes/restores noticeably when used with jQuery UI Accordion

### ISSUE THREAD

**Issue by ianthedev** [KingSora/OverlayScrollbars#403]
**Describe the bug**
When jQuery UI accordion contents expand/collapse, there are two weird behaviors:
- When the height of the scrollable area is larger than the accordion and the scrollbar isn't visible at the beginning, the scrollbar flickers between visible and invisible states on the activation of accordion contents.
- When the height of the scrollbar area is smaller than the accordion and the scrollbar is visible all the time, the height of the scrollbar changes noticeably and then quickly restores its correct height.

**Examples**
https://codepen.io/IanY/pen/eYGOQbv

**To Reproduce**
Steps to reproduce the behavior 1:
1. Adjust your browser height so that there is no overflow and the scrollbar isn't visible at the beginning.
2. Click between the accordion headers of Section 1 and 2.

Steps to reproduce the behavior 2:
1. Adjust your browser height so that there is overflow and the scrollbar is visible.
2. Click between the accordion headers of Section 1 and 2.

**Expected behavior**
The scrollbar is not supposed to flicker, and its height is not supposed to change/restore noticeably.

**Environment**
 - Used Operating System(s): Windows 7 (64-bit)
 - Used Browser(s) (with version): Mozilla Firefox 94.0.2 and Google Chrome 96.0.4664.45

**Comment by KingSora** [comment]
Please try `v2` and report back whether the issue still persists :)
