### ISSUE TITLE
Ability to adjust spacing between scrollbar and edge of scrollable area

### ISSUE THREAD

**Issue by Eric24** [KingSora/OverlayScrollbars#404]
**Is your feature request related to a problem? Please describe.**
For fine control over layouts, it is often desirable to adjust the default spacing between the scrollbar and the edge of the scrollable area. This can be done today using a class, but that isn't convenient when the layout is code-driven.

**Describe the solution you'd like**
Ideally, the scrollbar would accept an optional property that adds spacing in terms of pixels (not sure if this is "margin" or "padding", but it would probably be best not to use one of those property names, since they have specific meaning in CSS context, while "spacing" would only apply to the gap between the edge of the scrollbar and the edge of the scrollable area). Note that the spacing would apply regardless of the orientation (vertical or horizontal) of the scrollbar.

**Comment by KingSora** [comment]
This should be fixed now with `v2` of `overlayscrollbars` where the scrollbars can be cloned and / or moved into different dom elements. You have complete freedom over them now.
