### ISSUE TITLE
Angular Ivy distribution

### ISSUE THREAD

**Issue by cypressious** [KingSora/OverlayScrollbars#413]
When building my project with Angular 13, I'm getting the following output:

```
Processing legacy "View Engine" libraries:
- overlayscrollbars-ngx [module/esm5] (https://github.com/KingSora/OverlayScrollbars)
Encourage the library authors to publish an Ivy distribution.
```

**Comment by KingSora** [comment]
This should be fixed now with the `v2` version of `overlayscrollbars` and with it the `0.4.0` version of `overlayscrollbars-ngx`
