### ISSUE TITLE
[React] Scrollbar doesn't appear when the height is not specified statically (ex: height : auto)

### ISSUE THREAD

**Issue by wargniy** [KingSora/OverlayScrollbars#418]
Hi ! Thank you for your work on OverlayScrollbars.

[REACT]
**Describe the bug**
When I use the scrollbar on a div wrapped with a height dynamically computed (css property _height : auto_)
The scrollbar doesn't appear at all.
Moreover, If I use _display: flex_ on the div wrapped by the scrollbar, the scrollbar appears and takes full heigt of content + few pixels. but doesn't scroll as expected.

**To Reproduce**
1. Go to the link [codesandbox](https://codesandbox.io/s/inspiring-banach-sjn86?file=/src/styles.css) below in example section.
2. See Scrollbar is here but does not scroll.
3. Go to _styles.css_  line **45** , class **Content**,  comment the line (display: flex)
4. See Scrollbar disappears (height: auto -> not computed by Scrollbar)

**Expected behavior**
Scrollbar should scrolls on a dynamic content without impose to set a static size.
Use flexbox should be possible and Scrollbar should adapt and scroll regardless the height of the content .

**Examples**
(https://codesandbox.io/s/inspiring-banach-sjn86?file=/src/styles.css)
see lines 45 + 46 in class "Content" in styles.css

**Environment**
 - Used Operating System(s): **Windows 10 Pro**
 - Used Browser(s) (with version): Chrome - Version 97.0.4692.99 (Build officiel) (64 bits)

**Additional context**
I use the Scrollbar in a component Dialog which has a size _auto_ or a max height, the full content is dynamic.
In these situations, the behaviour expected by the scrollbar is to take the maximum possible space then scroll when all the free space is used.

**Comment by KingSora** [comment]
Good day @wargniy 

`v2` released today which should fix this issue. Please also update `overlayscrollbars-react` to the latest version
