### ISSUE TITLE
os-content-glue height behaves strangely with flex box

### ISSUE THREAD

**Issue by kimyuil** [KingSora/OverlayScrollbars#424]
**Describe the bug**
os-content-glue height behaves strangely with flex box.

**To Reproduce**
1. make flex box to make horizontal scrollable box
2. make flex items with "style = 'flex : none'"
3. os-content-glue makes design strangely

I read guide about flex box (https://kingsora.github.io/OverlayScrollbars/#!documentation/flexbox)
but it dosen't work.
what am i missing?
Thank you for checking it out. @KingSora 

**Examples**
https://jsfiddle.net/only61/3qumg5ea/4/

**Environment**
- chrome browser
- use jQuery initialization

**Comment by KingSora** [comment]
Good day @kimyuil :)
In your fiddle your forgot to import the CSS file. I've created an updated version: https://jsfiddle.net/0t786efb/ with the CSS file in the ressources

**Comment by kimyuil** [comment]
Thanks for checking @KingSora  :)
It is so weird that the way jsfiddle works and the way my vscode works are different.
I copied the code you wrote in jsfiddle and moved it to my vscode and run as liveserver extension.
But It looks like the Examples that I wrote above. ( https://jsfiddle.net/only61/3qumg5ea/4/ )

This is my source code modified through your code wrote in jsfiddle.

`<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
    <style>
      .os-content-glue {
        background-color:red;
      }

      #testScroll .os-content {
        display: flex;
      }
    </style>
</head>
<body> 
  
  
  <div id="testScroll" style="overflow-x: auto;">
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    <div style="flex: none; width: 180px; height: 80px; background-color: aqua; margin: 2px;">
      image
    </div>
    </div>
  
</body>

<script src="https://code.jquery.com/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/overlayscrollbars/1.13.1/js/jquery.overlayScrollbars.min.js" integrity="sha512-3Ofi0j25Ar6Hyqk2sdvfuoVCvvN6nE6Dh/eoMc8RQ/bnCvO8wpE+M5KyJz6T08T7pl/x82I/3Y5Amz9n3T9Esw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  $(function() {
    $("#testScroll").overlayScrollbars({
      scrollbars : {  autoHide : "scroll" },      
    });    
  }); 
</script>
</html>`

And I ran the source code as a live server to see the screen.

But the screen looks like this.
![image](https://user-images.githubusercontent.com/49484871/154388987-0358688d-684a-4f02-939d-9d887fd95b0d.png)

Thank you for checking again..

**Comment by KingSora** [comment]
@kimyuil please import / use the CSS file which comes with OverlayScrollbars

**Comment by kimyuil** [comment]
It works! Thank you for the reply.
