### ISSUE TITLE
iOS default scroll-to-top behavior seems to not work

### ISSUE THREAD

**Issue by filipjakobsen** [KingSora/OverlayScrollbars#425]
**Describe the bug**
When tapping the top 40px of the screen in an app on iOS, the open app will scroll to the top. When doing this on a site I am making using overlayScrollbars, it seems like it does not work

**To Reproduce**
1. Open a page using overlayScrollbars on an iOS device
2. Scroll down on the page
2. Tap the center of the very top of the screen (the top 40px of the screen where the status bar with the clock and battery appear)
4. Notice how the page does not scroll to top of the page

**Expected behavior**
The page should scroll to the top

**Examples**
You can use this page on an iOS device to test: https://cdpn.io/pen/debug/wvPPeZx/8d2787285f08cc3eb9a9820ef6df5177

**Environment**
 - Used Operating System(s): iOS 15.0
 - Used Browser(s) (with version): Safari

**Comment by KingSora** [comment]
This should be fixed in `v2` which released today. Please update to the latest version :)
