### ISSUE TITLE
OverlayScrollbars go away when window is resized

### ISSUE THREAD

**Issue by Nsbx** [KingSora/OverlayScrollbars#43]
Hello,
To avoid bad description there is a gif to explain the problem.

[https://gfycat.com/ReasonableSandyAfricanwildcat](https://gfycat.com/ReasonableSandyAfricanwildcat)

This is like this on all pages of my app so i don't think is a bad comportent with the other js.

thank for advance

**Comment by KingSora** [comment]
Good day!

Are you using a flexbox layout on your page? Also which browser are you using?

**Comment by Nsbx** [comment]
Yeah i use bootstrap 4 and ".row" use flex
I use Chrome

**Comment by KingSora** [comment]
Well, that explains this behavior. Please don't use OverlayScrollbars directly on a flexbox element. Use a inner div, which has the size `height: 100%; width: 100%` and `display: block`. Unfortunately OverlayScrollbars doesn't work that well on flexbox elements.

**Comment by Nsbx** [comment]
Oh ok i see unfortunately i can't change my layout  without broke everything :(
Thank for your help and thank for you script :D

**Comment by KingSora** [comment]
You could also try to set the option `sizeAutoCapable` to `false`. Maybe this will also help in your case.

**Comment by KingSora** [comment]
I'm glad to hear that!
I'll definitely write an article about flexbox in my documentation, to make it more clear how to use the plugin in such a enviroment.

**Comment by IamTC** [comment]
Hi! I have an issue with the flexbox as well. The flow changes to a column where my initial flow was a row. 
Here is a snapshot without OS https://ibb.co/PTVbx2n
and with https://ibb.co/gyGd0y6

**Comment by KingSora** [comment]
@IamTC Please try to change your DOM according to the changes the plugin is making. Append the flexbox styling to the generated `.os-content` element.
