### ISSUE TITLE
Emit events from vue component

### ISSUE THREAD

**Issue by NWaterbury** [KingSora/OverlayScrollbars#430]
As a developer I would like the ability to listen for the event handlers supported by the overlay scrollbars plugin when using the vue component, such as scroll events.

Please update the vue component to emit the events

**Comment by KingSora** [comment]
`v2` of `overlayscrollbars` was released today and with it a new version of `overlayscrollbars-vue` which emits events: [README](https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-vue)
