### ISSUE TITLE
onInitializationWithdrawn callback doesn't work.

### ISSUE THREAD

**Issue by christophe-glanum** [KingSora/OverlayScrollbars#434]
**Describe the bug**
onInitializationWithdrawn callback  doesn't work.

**To Reproduce**
I use **nativeScrollbarsOverlaid : { initialize : false }.** and the callback onInitializationWithdrawn doesn't work.

**Comment by KingSora** [comment]
Good day @christophe-glanum 
Can you please create an minimal example on jsfiddle, codesanbox or somewhere else where I can review it? :)

**Comment by KingSora** [comment]
This should be fixed in version `1.13.2` :)
