### ISSUE TITLE
The scrollbar gets unnecessarily applied when the max-content width is used

### ISSUE THREAD

**Issue by kulism** [KingSora/OverlayScrollbars#436]
**Describe the bug**
The scrollbar gets unnecessarily applied when the max-content width of the container is used.

**To Reproduce**
1. Create a div element and apply the width and max-width with CSS (see examples section). Mind div height is not limited.
2. Populate the div with some content.

**Expected behavior**
No scrollbar should be added/visible.

**Examples**
```
<style>
  .ctn {
    width: max-content;
    max-width: 400px;
  }
</style>

<div class="ctn">
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum 
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum   
</dv>

<script>
  document.addEventListener("DOMContentLoaded", function() {
     OverlayScrollbars(document.querySelectorAll(".ctn"), { });
  });
</script>
```
<img width="413" alt="image" src="https://user-images.githubusercontent.com/15194583/164482700-d6552614-7a19-4fb6-b5b8-bd2ccf04e5d3.png">

**Environment**
 - macOS
 - Google Chrome 100.0.4896.75
 - OverlayScrollbars 1.13.1

**Comment by KingSora** [comment]
Good day @kulism 

`v2` released today where thos issue should be fixed :)
