### ISSUE TITLE
Auto scroll when near the edge while dragging an element

### ISSUE THREAD

**Issue by conrad-scherb** [KingSora/OverlayScrollbars#439]
**Is your feature request related to a problem? Please describe.**
Native scrollbar behaviour causes a scroll when at the edges of the scrollbar, scrolling down while an element is currently being dragged. This feature however doesn't seem to be supported based on the documentation.

**Describe the solution you'd like**
An implementation of this feature in OverlayScrollbars.

**Comment by PratkinV** [comment]
I tried in Chrome and scroll starts when you drag an item to the edge of the container, however in Firefox it doesn't work for some reason.

**Comment by KingSora** [comment]
This seems to be a browser bug though and there is nothing I can do since the library relies on this styles.. You can try to open an issue on Mozillas side.

Your workaround also seems valid as long as it is not causing any issues for you though :)
