### ISSUE TITLE
Build project error

### ISSUE THREAD

**Issue by Rusl10** [KingSora/OverlayScrollbars#441]
Hello.
Can you help to fix this bug?
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26712091/169796993-1e2377b9-c8c3-4a23-b4ff-80ff22a36522.png)
Locally everything works well but when i try to build my project with the library i get this error.

**Comment by ankha0109** [comment]
@Rusl10 Hi, how did you resolve this issue?
