### ISSUE TITLE
Angular 13 directive

### ISSUE THREAD

**Issue by atgote** [KingSora/OverlayScrollbars#442]
**Is your feature request related to a problem? Please describe.**
It is not possible (AFAIK) to use the Angular component with \<cdk-virtual-scroll-viewport\> or for any other custom container.

**Describe the solution you'd like**
A directive named 'overlayScrollbar' applicable with all possible options to any HTML element.

**Describe alternatives you've considered**
I've tried to create \<overlay-scrollbars\> inside \<cdk-virtual-scroll-viewport\> but that doesn't work.
The working alternative is 'fuseScrollbar' (with 'PerfectScrollbar' under the hood), however it has not a pleasant scrolling behavior.

**Comment by KingSora** [comment]
`v2` of `overlayscrollbars` released today. Please update every `overlayscrollbars` dependency to the latest version. In the new version of `overlayscrollbars-ngx` the component selector changed and I've also added a directive. [README](https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-ngx)
