### ISSUE TITLE
Uncaught SyntaxError: invalid arrow-function arguments 

### ISSUE THREAD

**Issue by fmirjalili** [KingSora/OverlayScrollbars#448]
I have this error _Uncaught SyntaxError: invalid arrow-function arguments (parentheses around the arrow-function may help)_ in 
`let li=n=21=>crypto.getRandomValues(new Uint8Array(n)).reduce()`;
I cant Find where the error comes.
Please help how can i resolve it.

**Comment by KingSora** [comment]
Good day @fmirjalili 
I believe this error isn't coming from `OverlayScrollbars` as the library isn't doing anything with `crypto` and `Uint8Array`.
