### ISSUE TITLE
[React] Flex-basis property not working

### ISSUE THREAD

**Issue by danylo-holovenko** [KingSora/OverlayScrollbars#449]
**Describe the bug**
Is there any way to make flex-basis work when `<OverlayScrollbarComponent>` is wrapped with it without setting `sizeAutoCapable: false`? 
In [this example](https://codesandbox.io/s/purple-https-sct1n5?file=/src/styles.css) you can see that I wrapped 2 components into a `flex-basis` property set to 50% each, but content width was miscalculated, you can see this by looking at the Content Glue Element in DOM. 
**But** if I replace `flex-basis: 0 0 50%` to simple `width: 50%` it works perfectly.

**Examples**
https://codesandbox.io/s/purple-https-sct1n5?file=/src/styles.css

**Environment**
 - Used Operating System(s): MacOS
 - Used Browser(s) (with version): Chrome 103.0.5060.114

**Comment by KingSora** [comment]
Good day @danylo-holovenko 

It seems like this is a limitation of version 1. I've tried it with an early build of `v2` and it works there...
I'm working hard on releasing `v2` mid to end of the month.. I cant offer you any solution besides waiting or using the `width: 50%` style.

**Comment by danylo-holovenko** [comment]
@KingSora thank you for your reply! Will be waiting for v2

**Comment by KingSora** [comment]
@danylo-holovenko `v2` released today, please update `overlayscrollbars` and `overlayscrollbars-react` to the latest version :)
