### ISSUE TITLE
I want to add "offset" to 「getState」

### ISSUE THREAD

**Issue by FontEndArt** [KingSora/OverlayScrollbars#450]
**Is your feature request related to a problem? Please describe.**
Gets the offset of the current Scrollbars. I can only get the viewport DOM by getElement, then I got scrollLeft or scrollTop in the dom.

**Describe the solution you'd like**
I hope add like offset .. key to getState() result.

**Describe alternatives you've considered**
No. Because I can through getElement got it, but It's not what I wanted

**Additional context**
no content.

**Comment by KingSora** [comment]
Good day @FontEndArt 

I am not sure whether I'm understanding you correctly.. do you mind sharing a code example to break through the language barrier? :)

**Comment by FontEndArt** [comment]
Yes, I can.

But I might be a little later. Please wait some time.. thanks

**Comment by KingSora** [comment]
Ahhh I guess you can use `instance.scroll()` for this. https://kingsora.github.io/OverlayScrollbars/#!documentation/method-scroll

**Comment by FontEndArt** [comment]
Oh, I really didn't find it. I think... May be for two reasons.
The one is no drop obvious example in there.

**Comment by FontEndArt** [comment]
Thanks for you!

**Comment by KingSora** [comment]
I'll try to document it better for version 2 :)
