### ISSUE TITLE
flex-direction: column-reverse not working as expected

### ISSUE THREAD

**Issue by KoenPaas** [KingSora/OverlayScrollbars#451]
The scrollbar position should go to to the bottom just as the default browser behavior when using column-reverse.

What I've treid so far is add this class to the scrollbar component:
`<OverlayScrollbars :options="{ className: 'orderbook-asks' }" class="os-host-flexbox">`

the class:
```
.orderbook-asks .os-content {
    display: flex !important;
    flex-direction: column-reverse;
}
```

Or is there a better way of implementing this reverse behavior for this package?

Thanks

**Comment by andreuka** [comment]
Did you find the solution? It seems like the library is not suitable for this

**Comment by KingSora** [comment]
@andreuka I havent looked into this yet, since I'm focusing on version 2.x, which should definitely fix this issue

**Comment by andreuka** [comment]
> @andreuka I havent looked into this yet, since I'm focusing on version 2.x, which should definitely fix this issue

Didnt notice you have 2.0 beta already, will try to test it now :)

**Comment by andreuka** [comment]
Tested with 2.0-beta1 and still not possible to get that reverse behaviour like is possible with CSS provided by the topic starter.

**Comment by KingSora** [comment]
@andreuka please provide a minimal example on jsfiddle / stackblitz or codesandbox so I can have a deeper look into it :)

**Comment by KingSora** [comment]
@andreuka @KoenPaas this seems to work for me: https://stackblitz.com/edit/stackblitz-starters-hdrcme?file=src%2FApp.tsx If thats the behavior you are looking for

**Comment by tchin8** [comment]
@KingSora I'm also having the same issue. Although the items are reversed, the scrollbar still initializes at the top, when really the bottom content should be scrolled into view.
