### ISSUE TITLE
Doesn't seem to override native overlay scrollbars

### ISSUE THREAD

**Issue by brc-dd** [KingSora/OverlayScrollbars#453]
Firefox, Chrome and Edge (experimental) have now natively overlaid scrollbars. This plugin doesn't seems to override them. Here are some screenshots of the official website:

Chrome with default settings (expected):

![image](https://user-images.githubusercontent.com/40380293/180659613-876ecef4-cb34-465b-ab82-00b4811560e8.png) ![image](https://user-images.githubusercontent.com/40380293/180659622-f1c6f58c-c9a4-4557-adc3-35030674dea8.png)

Firefox (v103.0b9, on v102.0 its also similar):

![image](https://user-images.githubusercontent.com/40380293/180659051-cde74d15-fd13-4e72-b732-0e79ad5e9574.png) ![image](https://user-images.githubusercontent.com/40380293/180658939-ce798404-90e1-4ef0-be2a-ea005e71ba4c.png)

Chrome (v103.0.5060.134 with `chrome://flags/#overlay-scrollbars` enabled):

![image](https://user-images.githubusercontent.com/40380293/180659002-2f018ce2-64cb-4cf4-bdbf-67e506c46e8c.png) ![image](https://user-images.githubusercontent.com/40380293/180659027-5ac88c3b-c830-4c18-ad02-619330aea766.png)

Edge (v103.0.1264.62 with `edge://flags/#edge-overlay-scrollbars-win-style` enabled):

![image](https://user-images.githubusercontent.com/40380293/180659223-eb777577-3181-4212-a72a-dc8ee68d3419.png) ![image](https://user-images.githubusercontent.com/40380293/180659231-cb3e4a26-8e1b-4d7b-82dc-dcc2de05ac43.png)

(Above screenshots were taken on Windows 11.)

All of these browsers on macOS Monterey (looks pretty similar to expected one though):

![image](https://user-images.githubusercontent.com/40380293/180659397-943e8090-5a68-468b-a1d2-e0c4f60969a1.png) ![image](https://user-images.githubusercontent.com/40380293/180659339-7d190536-f1fe-4e7e-a3b0-b4f288324686.png)

(Images on right are of scrollbars in focus/active state.)

**Comment by KingSora** [comment]
Good day @brc-dd 
It should do that - Can you please post the output of `OverlayScrollbars.globals()` here and a snipped of how you initialize the plugin? One of the browsers should be enough.

**Comment by brc-dd** [comment]
Hi! I'm testing this on your website (https://kingsora.github.io/OverlayScrollbars/#!overview), and this is the output of `OverlayScrollbars.globals()`:

```json
{
   "defaultOptions":{
      "className":"os-theme-dark",
      "resize":"none",
      "sizeAutoCapable":true,
      "clipAlways":true,
      "normalizeRTL":true,
      "paddingAbsolute":false,
      "autoUpdate":null,
      "autoUpdateInterval":33,
      "updateOnLoad":[
         "img"
      ],
      "nativeScrollbarsOverlaid":{
         "showNativeScrollbars":false,
         "initialize":true
      },
      "overflowBehavior":{
         "x":"scroll",
         "y":"scroll"
      },
      "scrollbars":{
         "visibility":"auto",
         "autoHide":"never",
         "autoHideDelay":800,
         "dragScrolling":true,
         "clickScrolling":false,
         "touchSupport":true,
         "snapHandle":false
      },
      "textarea":{
         "dynWidth":false,
         "dynHeight":false,
         "inheritedAttrs":[
            "style",
            "class"
         ]
      },
      "callbacks":{
         "onInitialized":null,
         "onInitializationWithdrawn":null,
         "onDestroyed":null,
         "onScrollStart":null,
         "onScroll":null,
         "onScrollStop":null,
         "onOverflowChanged":null,
         "onOverflowAmountChanged":null,
         "onDirectionChanged":null,
         "onContentSizeChanged":null,
         "onHostSizeChanged":null,
         "onUpdated":null
      }
   },
   "autoUpdateLoop":false,
   "autoUpdateRecommended":false,
   "nativeScrollbarSize":{
      "x":0,
      "y":0
   },
   "nativeScrollbarIsOverlaid":{
      "x":true,
      "y":true
   },
   "nativeScrollbarStyling":false,
   "overlayScrollbarDummySize":{
      "x":30,
      "y":30
   },
   "cssCalc":"calc",
   "restrictedMeasuring":false,
   "rtlScrollBehavior":{
      "i":false,
      "n":true
   },
   "supportTransform":true,
   "supportTransition":true,
   "supportPassiveEvents":true,
   "supportResizeObserver":true,
   "supportMutationObserver":true
}
```

**Comment by KingSora** [comment]
@brc-dd ah, testing on the documentation page body element is a bad example, because it won't initialize on the body if the native scrollbar are overlaid. It should still be working on the various demos I've put on the page.

**Comment by brc-dd** [comment]
>  I'm initializing it with `{ nativeScrollbarsOverlaid: { initialize: false } }`

Ah, okay! I didn't checked that part. Thanks for the clarification. Yes it works fine in the demos!
