### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'ownerDocument')

### ISSUE THREAD

**Issue by adrianvincent91** [KingSora/OverlayScrollbars#457]
**Describe the bug**

```
main.6aa13.js:23839 Uncaught TypeError: Cannot read properties of undefined (reading 'ownerDocument')
    at createStructureSetupElements (main.6aa13.js:23839:15)
    at createStructureSetup (main.6aa13.js:24814:21)
    at OverlayScrollbars (main.6aa13.js:25276:23)
    at HTMLDocument.<anonymous> (main.6aa13.js:240:20)
```

**To Reproduce**

```
const { OverlayScrollbars } = require('overlayscrollbars');`

document.addEventListener("DOMContentLoaded", function () {

    const el = OverlayScrollbars(document.querySelectorAll('div.myWindow'), { });

});

```

**Environment**

Using webpack 5 to output my js

**Comment by KingSora** [comment]
Good day @adrianvincent91 :)
You are using 'document.querySelectorAll` which gives you an collection of elements. Since version 2 OverlayScrollbars only supports a single element. 
Instead use the `forEach` function to iterate over the element array and initialize OverlayScrollbars individually

**Comment by adrianvincent91** [comment]
> Good day @adrianvincent91 :) You are using `document.querySelectorAll` which gives you a collection of elements. Since version 2 OverlayScrollbars only supports a single element in the init function.
> 
> Instead use the `forEach` function to iterate over the element array and initialize OverlayScrollbars individually to each element.

Thanks, I was reading the wrong documentation version.

On a slightly related note, .scroll() seems to have been removed in version 2. Is this intentional?

**Comment by KingSora** [comment]
V2 is currently in beta, and I'm planning to bring the function back, just as an opt-in plugin.. in this way users who arent using it wont have it in their bundle
