### ISSUE TITLE
Scrollbar thumb size

### ISSUE THREAD

**Issue by Charles-XD** [KingSora/OverlayScrollbars#458]
I used OverlayScrollbarsCompoent with react-window. The problem is the size of the scrollbar thumb is not accurate when the list layout is horizontal.

expected: 
![image](https://user-images.githubusercontent.com/85753603/187382187-6fe1e43e-4ade-49ad-bae9-4e003e2e583c.png)
![image](https://user-images.githubusercontent.com/85753603/187382330-40ca46c5-527d-4944-b0ed-2e1e945152be.png)

current behavior:
![image](https://user-images.githubusercontent.com/85753603/187382535-959492cd-cc3b-4930-9180-34d748da492a.png)
![image](https://user-images.githubusercontent.com/85753603/187382697-c4f96e93-a457-43bf-985b-206b1fcf02bd.png)

**Comment by KingSora** [comment]
Good day @Charles-XD 
Which OverlayScrollbars version are you using? Could you also please post a minimal example on jsfiddle / codesandbox / stackblitz or a similar website? This would help me to identify the issue

**Comment by Charles-XD** [comment]
Hi @KingSora 
I created a demo [https://stackblitz.com/edit/react-ts-xqojzk?file=App.tsx](https://stackblitz.com/edit/react-ts-xqojzk?file=App.tsx)

I used overlayscrollbars-react v.0.3.0 with overlayscrollbars v.1.13.3 (which installed as a dependency)

Also the component wrapper links are broken [https://kingsora.github.io/OverlayScrollbars/#!overview](https://kingsora.github.io/OverlayScrollbars/#!overview)

Thanks a lot for your quick reply.

**Comment by KingSora** [comment]
@Charles-XD sorry for the late reply. `v2` is released now and was designed to work with `react-window` as well as other virtual scrolling libraries. Here is a working example based on your code: https://stackblitz.com/edit/react-wdbggw?file=index.js
