### ISSUE TITLE
SSR / ESM issue

### ISSUE THREAD

**Issue by MorevM** [KingSora/OverlayScrollbars#465]
**Describe the bug**
Can't be used (v2 at least) on the server.
Can't be imported from Node with `type: "module"` declared in `package.json`

**To reproduce server error**
1. Go to [reproduction link on stackblitz](https://stackblitz.com/edit/node-ert9gw?file=index.js)
2. Run `node index.js` in the integrated terminal
3. See a Reference Error. There are some errors related to usage of `Element`, `HTMLElement`, `window `etc

**To reproduce ESM import error**
1. Go to [another reproduction link on stackblitz](https://stackblitz.com/edit/node-2bq5hk?file=index.js)
2. Run `node index.js` in the integrated terminal
3. See a Syntax Error.

**Expected behavior**
No errors on the server side.

---

Thank you for your work, looks very solid :)
Let me know if I can help somehow.

**Comment by KingSora** [comment]
@MorevM Good day!

I know.. this is something I just fixed and [added tests for](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars/test/jest-node/server.test.ts) but its not released yet.. I'm planning on releasing the last beta version soon.

**Comment by KingSora** [comment]
Published version [2.0.0-beta.3](https://www.npmjs.com/package/overlayscrollbars/v/2.0.0-beta.3) where both of the issues should be fixed :)

**Comment by MorevM** [comment]
@KingSora I can confirm it's fixed in beta.3, so I close this.
Thank you for your work :)
