### ISSUE TITLE
`z-index` of scrollbars

### ISSUE THREAD

**Issue by MorevM** [KingSora/OverlayScrollbars#467]
**Describe the bug**
Scrollbar has `z-index: 99999` by default, it may affect other app elements.

**To Reproduce**
1. Go to https://typescript-gzypfp.stackblitz.io
2. Scroll down a bit
3. See how the scrollbar overlaps the sticky header

**Expected behavior**
No overlapping.

**Additional context**
I guess you can even safely remove the `z-index` from `.os-scrollbar` at all, since there are no other absolute elements in a parent container. 
I'm not sure about sentence above if plugin applied to `body` (then it seems maybe reasonable) or `textarea` element, but i'm 100% sure I don't want to monkey-patch the default styles (or change the layout of my site creating [another stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) for example) in cases such in reproduction link above.

**Comment by KingSora** [comment]
Good day @MorevM 

I guess you're right - I'll remove the z-index but only if the target element is not the `body`. For now you can fix this by apllying `z-index: 0` to the host / target element.

**Comment by KingSora** [comment]
This is now in `v2` which released today
