### ISSUE TITLE
Vue3 + Vite use Can't work

### ISSUE THREAD

**Issue by WilsonXinxin** [KingSora/OverlayScrollbars#468]
**Describe the bug**
Use
> import 'overlayscrollbars/css/OverlayScrollbars.css';

Tip
![image](https://user-images.githubusercontent.com/43174390/197698815-a281e137-a893-4041-968c-a05d8f4365d9.png)

**Packages**
![image](https://user-images.githubusercontent.com/43174390/197698999-c925a557-8f6e-47d0-b7f6-ce2af05e870d.png)

**Comment by KingSora** [comment]
Good day! OverlayScrollbars `v2` is currently not compatible with any of the framework wrappers. I'm working towards a release at the end of the month.

**Comment by KingSora** [comment]
@WilsonXinxin `v2` is now released with the `0.4.0` version of `overlayscrolbars-vue` which should work :)
