### ISSUE TITLE
Correct markup to use with frontend frameworks?

### ISSUE THREAD

**Issue by MorevM** [KingSora/OverlayScrollbars#469]
Hello again :)

I'm trying to get it work (v2.0.0-beta.3) with [Nuxt](https://nuxtjs.org/) currently (on top of Vue 2).

[Stackblitz link illustrating the problem](https://stackblitz.com/edit/typescript-ehuktv?file=index.html)
If the right part of a link above with demo doesn't load (I experience this for some reason O_o), here is [direct link to demo which works fine](https://typescript-ehuktv.stackblitz.io).

I'm struggling with correct HTML markup that should I use to let the plugin consider it as Vue component.

As you can see in demo I have an element that has width and height more than container, and with "empty DOM" initialization (first box) all works fine, but with "full" markup (that I need to make it work with Vue) horizontal scrollbar doesn't show. 

I've tried to use the markup from [previous Vue component from repo](https://github.com/KingSora/OverlayScrollbars/blob/96a7683d65ec8a3926b410f0a906882a0640e861/packages/overlayscrollbars-vue/src/OverlayScrollbarsComponent.vue) (box 2), also I've tried to extract the markup generated from "box 1" initialization, but this behavior persist.

I saw you're [working on framework wrappers](https://github.com/KingSora/OverlayScrollbars/issues/468), but maybe it's already can be done without any extra release if you can tell me how :)

Sorry if I'm annoying/impatient or it makes you feel like you're racing.
I just have an (already hung up a little) work task that I really want to solve with your plugin, it's seems the best solution for now ^^

So, any tip maybe? :) 
Thank you for your time.

**Comment by KingSora** [comment]
@MorevM good day :)

Currently I'm in the middle of making each of the framework wrappers for `react`, `vue`, `angular` and `svelte`.. The [react](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-react/src/OverlayScrollbarsComponent.tsx) one is the most advanced and I consider it pretty much finished. As you can see the markup is really just one element.

Can you explain why the simple initialization (box 1 in your case) is not suited for frontend frameworks?

**Comment by KingSora** [comment]
Here is an basic example with the starter nuxt project I found on StackBlitz: https://stackblitz.com/edit/nuxt-starter-r3ztby?file=pages%2Findex.vue and it seems to work pretty good.

**Comment by MorevM** [comment]
@KingSora 

> Can you explain why the simple initialization (box 1 in your case) is not suited for frontend frameworks?

Well, maybe I was too hasty about "all frameworks" :)
I really surprised it works in Vue 3! Seems pretty fine, agreed with your previous comment. 

I was thinking it's not suitable because the plugin manipulates with DOM of the component directly, but framework can't track these chages - so if content is updating from outside - it just breaks.

Vue3 (works fine and I surprised about):
[Playground on stackblitz](https://stackblitz.com/edit/vue-hmwdv3?file=src/App.vue)
[Direct link to example](https://vue-hmwdv3.stackblitz.io)

But Vue2... That's why I need to reproduce the whole markup - to put `<slot>` content in the right place:
[Codesandbox playground with the same things but in Vue2](https://codesandbox.io/s/vue-2-playground-forked-3jnifr?file=/src/App.vue)

You can see the difference clicking `Add` / `Remove` with Vue2 and Vue3 versions :)

**Comment by KingSora** [comment]
@MorevM Indeed, I remember this problem... I believe `angular` has / had a similar behavior.. 
For that you can initialize OverlayScrollbars with an complete initialization object like:

```js
// <template>
//   <div>
//     <div ref="slot">
//       <slot></slot>
//     </div>
//   </div>
// </template>
OverlayScrollbars(
  {
    target: this.$el,
    elements: {
      viewport: this.$refs.slot,
      content: false,
    },
  },
  {}
);
```
I made an example for you here: https://codesandbox.io/s/vue-2-playground-forked-rgku0z?file=/src/components/overlay-scrollbars.vue

The only negative here is that you are setting `content: false` which makes it not possible anymore to control this element with the `defaultInitialization`. This should be fixed with the `2.0.0` release, where you can set the `viewport` and `content` elements to the same element and the plugin is smart enough to determine what you want depending on the `defaultInitialization`. I've already updated the [react component](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-react/src/OverlayScrollbarsComponent.tsx#L33-L43) to this new strategy.

**Comment by KingSora** [comment]
@MorevM is that working out for you? :)

**Comment by KingSora** [comment]
@MorevM I've released `v2` today. There should also be the `vue` wrapper with the corresponding initialization code and markup. :)
