### ISSUE TITLE
Scrollbars not visible after creating with autoHide 'leave'

### ISSUE THREAD

**Issue by mbrainiac** [KingSora/OverlayScrollbars#48]
After creating OverlayScrollbars with autoHide = 'leave' and the mouse overhead the container, scrollbars not visible.
The scrollbars only visible when we move the mouse out/in the container.

Click refresh then move mouse over yellow box.
https://jsfiddle.net/wxaeqcn2/2/

**Comment by KingSora** [comment]
Good day!

I haven't thought someone would need this kind of functionality, but it shouldn't be a problem to fix this.
Thanks for reporting!

**Comment by KingSora** [comment]
Small update: 
I've implemented this functionality and it will be present in the next version which will be `version 1.5.0`.

**Comment by KingSora** [comment]
[Version 1.5.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.5.0) is now published and the fix is implemented.

Thank you very much for reporting this bug, if you find any other bugs please don't hesitate to open a issue!
