### ISSUE TITLE
Cannot import CSS - missing export in `package.json`

### ISSUE THREAD

**Issue by Magiczne** [KingSora/OverlayScrollbars#480]
**Describe the bug**
When trying to import css file into the build:
```
Error: Package path ./styles/overlayscrollbars.min.css is not exported from package <redacted>/node_modules/overlayscrollbars
```

**To Reproduce**
Create simple webpack-driven build, add 
```scss
@import "overlayscrollbars/styles/overlayscrollbars.min.css";
```

to SCSS file, or

```ts
import 'overlayscrollbars/styles/overlayscrollbars.min.css'; 
```

to JS/TS file

**Expected behavior**
Working imports

**Comment by KingSora** [comment]
Good day @Magiczne 

I'm not exposing the `.min.css` file from the package.. is there a reason you want to import it and not the normal version?

**Comment by Magiczne** [comment]
For some reason the default version was not working. I'll look again into that, and go back to you.

But using already minified version could be useful for some environments which are ran without minifying step.

**Comment by KingSora** [comment]
@Magiczne anything new here? :)

**Comment by Magiczne** [comment]
Sorry, busy days at work, an currently sitting on version 1.x

Will try to update on this issue in coming week

**Comment by ddenev** [comment]
Just to mention that the proper import for v1 styles is:

`'import "overlayscrollbars/css/OverlayScrollbars.css'`

**Comment by canderis** [comment]
For anyone who comes across this while upgrading this package, make sure you're importing `import 'overlayscrollbars/overlayscrollbars.css';` and not `import 'overlayscrollbars/styles/overlayscrollbars.css';`. That's how I ended up getting this error

**Comment by Mng12345** [comment]
The `overlayscrollbars.css` was metioned in the package.json.
```json
"exports": {
    ".": {
      "require": "./overlayscrollbars.cjs",
      "import": "./overlayscrollbars.mjs",
      "types": "./types/overlayscrollbars.d.ts"
    },
    "./overlayscrollbars.css": "./styles/overlayscrollbars.css"
  },
```
So, you should use `import 'overlayscrollbars/overlayscrollbars.css'` instead of `import 'overlayscrollbars/styles/overlayscrollbars.css'`
