### ISSUE TITLE
[React] Scrollbar handles get clipped when scrolled to the end

### ISSUE THREAD

**Issue by swese44** [KingSora/OverlayScrollbars#483]
**Describe the bug**
Scrollbar handles move beyond the scroll area and get clipped when scrolled to the end.
![Screenshot 2022-12-01 at 11 25 51 AM](https://user-images.githubusercontent.com/471731/205131283-a6fa8919-31af-4d18-999c-0d8c0a39a7e9.png)
![Screenshot 2022-12-01 at 11 26 00 AM](https://user-images.githubusercontent.com/471731/205131291-03c05b83-0aef-4d20-bf0d-10bd4a0e7a54.png)

**To Reproduce**

1. Scroll all the way to the right or to the bottom of the scrollable area
2. Scroll handle gets clipped at the end

**Expected behavior**
Scroll handle is fully visible and not clipped

**Examples**
Please create a small example of the bug.
To do this you can use online platforms like [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/). You can also create a separate Github repository which I can clone.

**Environment**

- Used Operating System(s): Mac OS Ventura 13.0.1
- Used Browser(s) (with version): Edge 107.0.1418.62
- overlayscrollbars: 2.0.1
- overlayscrollbars-react: 0.5.0

**Additional context**

**Comment by swese44** [comment]
No longer reproducing, may have been a styling issue on my end :)

**Comment by KingSora** [comment]
@swese44 alrighty, in case you need anything else dont hesitate to open an issue / discussion :)
