### ISSUE TITLE
CDN Version.

### ISSUE THREAD

**Issue by David-Carty** [KingSora/OverlayScrollbars#484]
Older versions of OverlayScrollbars work great with the CDN.  Version 2+ Doesn't seem to.  Also, just because a framework and build system isn't required doesn't mean the stack is legacy.  Some quick jobs don't require a full ecosystem, and the CDN version is useful for rapid demos.

**Comment by KingSora** [comment]
@David-Carty Good day :)

No worries `v2` also works perfectly fine without a build system. Follow the instructions in the README for [manual download & embedding](https://github.com/KingSora/OverlayScrollbars#manual-download--embedding). After you've embedded script and styles on your page you can use the `OverlayScrollbarsGlobal` window global:

```js
const instance = OverlayScrollbarsGlobal.OverlayScrollbars(document.body, {});
```

`OverlayScrollbarsGlobal` holds all the keys you can import in node:
```js
import { 
  OverlayScrollbars, 
  ScrollbarsHidingPlugin, 
  SizeObserverPlugin, 
  ClickScrollPlugin
} from 'overlayscrollbars';
// is equivalent to
const { 
  OverlayScrollbars, 
  ScrollbarsHidingPlugin, 
  SizeObserverPlugin, 
  ClickScrollPlugin
} = OverlayScrollbarsGlobal;
```

**Comment by David-Carty** [comment]
Dropped the idea in favour of a CSS-only solution.  Feel free to close.

**Comment by KingSora** [comment]
@David-Carty I made a demo for you here: https://jsfiddle.net/rqdg2uLn/

In this demo I'm using `jsdelivr` as my CDN (https://www.jsdelivr.com/package/npm/overlayscrollbars).
- JS File: `browser/overlayscrollbars.browser.es6.js`
- CSS File: `styles/overlayscrollbars.css`

You can use every file in the `browser` directory though.. the differences between the files are in browser support and whether the code is minified or not.

**Comment by David-Carty** [comment]
Thanks a lot for your time.  Best, David.
