### ISSUE TITLE
Missing functions in Angular

### ISSUE THREAD

**Issue by elementalPRESS** [KingSora/OverlayScrollbars#486]
Hi,

first of all: thank you for this lib. The first lib that really works. Simply wonderful!

But  I have one problem with the angular wrapper. I can't find a way how to get and to set the scroller to a certain position. I can get the scroll event with `onScroll` but I don't understand how I can get the current scroll position from it or how I can set the scroller to a position.

Please can somebody provide an example how to do this?

Thx and best regards,
Lars

**Comment by KingSora** [comment]
Good day @elementalPRESS 

If you applied the plugin to the body element, you can scroll with the `windiw.scroll` function.. In case you applied it to a `div` or something you need the `instance` for it:

`osInstance.elements().viewport.scroll({ top: 0, left: 0 });`

**Comment by elementalPRESS** [comment]
Wonderful and thank you very much. That was what I'm looking for.

But one more question please: currently, I'm trying to integrate the scroller into the swimlane/datatable. This causes some issues when I resize the browser. The expected behaviour would be that the scrollbar would be redrawn and adopts to the current width/height. But this doesn't work so far. So I'm wondering how I can trigger the OS to redraw or reinit itself.

**Comment by KingSora** [comment]
@elementalPRESS the `instance` has a `update` function, you can use it like:

```js
osInstance.update();
// or
osInstance.update(true); // ignore cache
```
