### ISSUE TITLE
Missing programmatic scroll

### ISSUE THREAD

**Issue by mmswi** [KingSora/OverlayScrollbars#488]
Hello,

In the latest version, how can we scroll the component? We have this code in our app, but now I can't seem to find a scroll method anywhere. 

    overlayScrollbarsRef.current?.osInstance()?.scrollStop().scroll(
          {
            el: elem,
            scroll: 'ifneeded',
            block: 'begin',
            margin: 20,
          },
          500
        )

Also, was thinking of passing an id to the OverlayScrollbarsComponent to then use an external library for scrolling, but I can't do this either.

Thanks,

**Comment by mmswi** [comment]
I've seen that you have it as a WIP plugin, so I will close this

**Comment by mmswi** [comment]
Would help tough if you could provide an eta for this. Thanks

**Comment by KingSora** [comment]
@mmswi you can always use a an external library like:

```js
const { viewport } = osInstance.elements();
scrollLibrary(viewport, ...)
```
