### ISSUE TITLE
React Native FlatList support

### ISSUE THREAD

**Issue by Quaaani** [KingSora/OverlayScrollbars#490]
Hello!
I would like to ask if it really possible to support react-native FlatList component using useOverlayScrollbars hook?

I already successfully implemented this approach with ScrollView component, but with FlatList its kind a tricky because FlatList is using virtualization under the box.

Also I have two questions:
1. How do I typify ref of component so initialize function can accept it without casting ref manually (e.g. as unknown as InitializationTarget)
2. How could I use 'instance' in this approach and should I?

My implementation: 

```
export const CustomFlatList = observer(<T,>({data}: CustomFlatListProps<T>): ReactElement => {
  const [initialize, instance] = useOverlayScrollbars({options, defer: true})
  const flatListRef = useRef(null)

  useEffect(() => {
    initialize(flatListRef.current as unknown as InitializationTarget)
  }, [initialize, instance])

  return (
    <View style={styles.dropdown}>
      <FlatList
        ref={flatListRef}
        showsHorizontalScrollIndicator={false}
        showsVerticalScrollIndicator={false}
        data={data}
        renderItem={() => <Texts.BodyM>Item</Texts.BodyM>}
        keyExtractor={(item, index) => `CustomFlatList_${index}`}
      />
    </View>
  )
})
```

If you already have some examples of using this useOverlayScrollbars hook with different examples I would really enjoy to investigate them, because I didnt find them in this repo or documentation

**Comment by KingSora** [comment]
@Quaaani Good day :)

I believe `FlatList` support should be possible. If you setup a `CodeSandbox` or `StackBlitz` I could try to create a example for you. In your case the `useOverlayScrollbars` `instance` method might be the best option.

The `ref.current` has to be a `HTMLElement` or a `object` with a field called `target` which has to be a `HTMLElement`.

**Comment by Quaaani** [comment]
@KingSora Hello again!

Sorry for long waiting, I was on vacation ;)

I did an example of CustomScrollView component using your library on [CodeSandbox](https://codesandbox.io/s/overlay-scrollbars-example-lm68ju?file=/src/CustomScrollView.tsx) 

If it possible for you and you have a free time, can you make a review and also help me with implementing CustomFlatList too?

**Comment by KingSora** [comment]
@Quaaani Sorry for the late reply.. I've created a working example based on your code here: https://codesandbox.io/s/overlay-scrollbars-example-forked-x5w6pq?file=/src/App.tsx

In case you have any question please don't hesitate to ask

**Comment by KingSora** [comment]
@Quaaani I'll close this issue for now.. In case the example is lacking or not working for you please feel free to re-open the issue or create a new one :)
