### ISSUE TITLE
clickScroll not working in svelte

### ISSUE THREAD

**Issue by akashlama1998-icloud** [KingSora/OverlayScrollbars#492]

**Comment by KingSora** [comment]
@akashlama1998-icloud good day :)

Unfortunately I can't help you if you submit an empty issue. I need a piece of code, a demo or anything else I can use to look into your case.

**Comment by akashlama1998-icloud** [comment]
Hi! Sorry about that 😅. I'm using sveltekit v1.0 and using `overlayscrollbars` and `overlayscrollbars-svelte` package. I'm trying to click on the point where scollbar is not present let's a little bit down the bottom, but it is not working for some reason.

```svelte
<script lang="ts">
	import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte';
</script>

<OverlayScrollbarsComponent options={{ scrollbars: { theme: 'scrollbar-theme' } }}>
	<div class="flex flex-col gap-1.5 self-stretch md:overflow-y-auto md:pr-3 lg:pr-3.5">
		<slot />
	</div>
</OverlayScrollbarsComponent>
```

**Comment by akashlama1998-icloud** [comment]
Hi! Sorry about that 😅. I'm using sveltekit v1.0 and using `overlayscrollbars` and `overlayscrollbars-svelte` package. I'm trying to click on the point where scollbar is not present let's say a little bit down the bottom, but it is not working for some reason.

```svelte
<script lang="ts">
	import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte';
</script>

<OverlayScrollbarsComponent options={{ scrollbars: { theme: 'scrollbar-theme',  clickScroll: true } }}>
	<div class="flex flex-col gap-1.5 self-stretch md:overflow-y-auto md:pr-3 lg:pr-3.5">
		<slot />
	</div>
</OverlayScrollbarsComponent>
```

**Comment by akashlama1998-icloud** [comment]
Hi! Sorry about that 😅. I'm using sveltekit v1.0 and using `overlayscrollbars` and `overlayscrollbars-svelte` package. I'm trying to click on the point where scollbar is not present let's say a little bit down the bottom, but it is not working for some reason.

```svelte
<script lang="ts">
	import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte';
</script>

<OverlayScrollbarsComponent
	options={{ scrollbars: { clickScroll: true, theme: 'scrollbar-theme' } }}
>
	<div class="flex flex-col gap-1.5 self-stretch md:overflow-y-auto md:pr-3 lg:pr-3.5">
		<slot />
	</div>
</OverlayScrollbarsComponent>
```

**Comment by KingSora** [comment]
@akashlama1998-icloud I see, you need to use the `ClickScrollPlugin` for that feature to work.

**Comment by akashlama1998-icloud** [comment]
@KingSora Indeed.. But how can I install plugins in svelte (I'm using sveltekit)? It seems there isn't any documentation regarding that. Can you help me on that?

**Comment by akashlama1998-icloud** [comment]
I did it like this.. is this the correct way?
```svelte
<script lang="ts">
  import { ClickScrollPlugin, OverlayScrollbars } from 'overlayscrollbars';
  import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte';
</script>

<OverlayScrollbarsComponent
  options={{ scrollbars: { theme: 'scrollbar-theme', clickScroll: true } }}
  on:osInitialized={() => OverlayScrollbars.plugin([ClickScrollPlugin])}
>
  <div class="flex flex-col gap-1.5 self-stretch md:overflow-y-auto md:pr-3 lg:pr-3.5">
    <slot />
  </div>
</OverlayScrollbarsComponent>
```

**Comment by KingSora** [comment]
@akashlama1998-icloud using a plugin works everywhere the same.. in your / sveltes case you first need the Entrypoint of the client. (or a file which runs on startup).. For sveltekit it should be `hooks.client.ts` or whatever name you specified for your client hooks file.

In this file you simply need to paste:
```ts
import { 
  OverlayScrollbars,
  ClickScrollPlugin 
} from 'overlayscrollbars';

OverlayScrollbars.plugin(ClickScrollPlugin);
```
This code should run once and register the plugin on startup. You don't need to do anything else regarding plugins in the component props.

**Comment by akashlama1998-icloud** [comment]
Totally worked 🤯. Thank you.. closing this issue.

**Comment by KingSora** [comment]
@akashlama1998-icloud glad I could help :)
