### ISSUE TITLE
Screen content shifts up and down as the content changes size

### ISSUE THREAD

**Issue by thomasvansenus** [KingSora/OverlayScrollbars#493]
Hello,

I have a popup where I have two grids. Whenever I press on one of the rows in the top grid the content changes in the bottom grid. I expect the content to stay put when the height changes, but instead the screen content shifts up and down to accommodate these changes. 

I have attached a gif to show the issue.

Is there a way to prevent the screen content from shifting when there is less or more to show than before?
I am using:
-overlayscrollbars-vue 0.5.1
-overlayScrollbars 2.0.3

Thanks in advance.

![2023_01_12_162445](https://user-images.githubusercontent.com/35956859/212108071-4dc1412d-b84a-4f74-a1dc-e0d77a7e7303.gif)

**Comment by KingSora** [comment]
Good day @thomasvansenus 

First, please do the exact same example without OverlayScrollbars and confirm that it works as you expect... In case it does, I'll need a minimal reproducable example from you, otherwise I cant help, since your example seems a bit more complex

**Comment by thomasvansenus** [comment]
Hi @KingSora,

Thanks for your reply.

I did some more testing and confirmed that it was an issue with our current setup. I have managed to solve the problem.

I will close this issue.
