### ISSUE TITLE
Scroll to a specific position with a single click

### ISSUE THREAD

**Issue by MarcosRakesh** [KingSora/OverlayScrollbars#50]
Hello,
1. It is possible to scroll on track with one click (tap on mobile) where cursor is?  
It will make the scrollbar more useful to scroll to a specific position in the page without pulling the scrollbar, the current behavior is bad and is not precise. [Saw here](https://jamesflorentino.github.io/nanoScrollerJS/)
2. It is possible to set a page transition speed value while scrolling after click? [Similar here](https://codepen.io/anon/pen/jKWoVE)
Will be nice instead of direct jump.

Something like this:
![scrollbar](https://media.giphy.com/media/2wSJGwVtCB8eGDaZvf/giphy.gif)

**Comment by KingSora** [comment]
Good day!

I'm not quite sure, but I think the plugin is already supporting your feature: https://jsfiddle.net/b9j3ggwf/2/embedded/result/

To enable this behavior you have to set the option:
```javascript
scrollbars : {
	clickScrolling   : true,
}
```
You have a transition by default, but the plugin doesn't offer a option where you can adjust the transition speed. (Tipp: if you press `shift` while clicking on your position, the transition speed gets doubled)

**Comment by MarcosRakesh** [comment]
The feature is same as native, but if you look at gif (or plugin) the scroll precision is better.
The transition is still slow even with shift and better drag the handle than click.

I was hoping we can improve the click scroll by changing transition speed or disable it if possible and make the precision with one single click like in gif. The current behavior is slow and the precision is not good as in the example above. If you test the example on that plugin live you see the precision is better even without transition still look better and faster than native in my opinion.

**Comment by KingSora** [comment]
I can implement the native behavior with the shift click, that should be no problem. I'm still undecided about the transition speed option, I'm not sure if this case isn't too special to be supported. 
But as I said, I'll definitely improve the click scrolling by an instant scroll if you press the shift key while youre clicking (with the same precision as in the gif / nanoScroller).

**Comment by MarcosRakesh** [comment]
No need to change/add the transition speed anymore since there isn't one even in native.
The instant scrolling by shift is the only thing is missing from your plugin from native scrolling.

The instant click behavior is native browser and was enabled by default in nanoScroller (i tought it was a feature). If you only want (optional), make an option for it without any keys if can be activated on all browsers. [scrollbar click options in browser](http://kb.mozillazine.org/Ui.scrollToClick)

Sorry if i bother you for little things, i should've checked more before.
Thank you for you time.

**Comment by KingSora** [comment]
I've published [v1.5.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.5.0) just now, and I've added the instant scrolling feature if you press shift while clicking. (Small note, if you press ctrl + shift a short transition is applied to the instant scrolling).

**Comment by MarcosRakesh** [comment]
When you press ctrl + shift it supposed to be sticky the handler after? How to remove the sticky handler?

**Comment by KingSora** [comment]
@MarcosRakesh yes, it is intended. The native implementation does the same. You can remove the "sticky" feature, you have to release your button.
