### ISSUE TITLE
The scrollbar appears in mobile menu and content is overlapped

### ISSUE THREAD

**Issue by 01Kuzma** [KingSora/OverlayScrollbars#505]
Hello!
I've downloaded the latest 2.1 zip version and copied the jQuery version, but it seems, that it's v1...
The initialization is made like this:

```
$(function() {	
	$("body").overlayScrollbars({
className: "os-theme-light custom-scroll",
        });
});
```

Once the mobile menu is engaged a double bug appears:
![image](https://user-images.githubusercontent.com/569504/221425234-4077fee0-960f-49ac-bfa1-6272e798978f.png)

The scrollbar appears in the mobile menu and the right part with content becomes filled with white.

Is it related to a config?
You can check the [online demo](https://gerbuvio-darbai.eu/)

Need help.

Thank you!

**Comment by KingSora** [comment]
Good day @01Kuzma 

`v2` doesn't have a jQuery version, what js file are you using for your website? I would recommend you to use the standard files which are also available via a cdn. (https://www.jsdelivr.com/package/npm/overlayscrollbars)

**Comment by 01Kuzma** [comment]
Hello, @KingSora 
I've downloaded them from the release `zip` archive, `v1` folder.

Now, I've swapped files with yours provided by `CDN`.
But once I init library with old code:

```
$(function() {	
	$("body").OverlayScrollbars({
className: "os-theme-light custom-scroll",
        });
});

```

I receive this error - `Uncaught TypeError: $(...).OverlayScrollbars is not a function`

**Comment by KingSora** [comment]
@01Kuzma Thats because `v2` has no jquery version.

Try it like this:

```
$(function() {
  var OverlayScrollbars = window.OverlayScrollbarsGlobal.OverlayScrollbars;
  OverlayScrollbars(document.body, { 
    scrollbars: {
      theme: 'os-theme-light custom-scroll',
    },
  });
});
```

**Comment by 01Kuzma** [comment]
@KingSora ,
brilliant, thank you very much!!!

It seems working, also the native "Back To Top" function from `Gantry 5 framework` seems to work as well. For the `v1` earlier you helped me with a custom JS code for a back-to-top functionality.

Just a few questions please:
1. Previously I was able to open a mobile menu and scroll the content from the right side to the bottom. Now the menu hides after a certain amount of scroll. Is it an option in `OverlayScrollbars` ?
2. Is it possible to remove a vertical scrollbar from a mobile menu? It's excessive
3. Trying to customize the color, still no results. I will post this question in another topic

**Comment by KingSora** [comment]
@01Kuzma I dont quite understand your first question. But it sounds like its related to your html markup rather than the plugin. Regarding your second question: Yes thats possible. Your third question should be already answered in the discussion thread.

If you have any further questions, please dont hesitate to open a new issue / discussion :)

**Comment by 01Kuzma** [comment]
@KingSora , thank you for you help!
I will probably record a short screencast to demonstrate the first question in the discussion, if I won't fix it myself.
Regarding the second question, how do you think it could be achieved? Or should I ask it in discussions?
Thank you!
