### ISSUE TITLE
Vue Vite hot reload not working

### ISSUE THREAD

**Issue by filipbekic01** [KingSora/OverlayScrollbars#510]
Editing content wrapped within <OverlayScrollbarsComponent> component does not trigger Vite hot reload.

```
<OverlayScrollbarsComponent defer>
    // Changing content here will not trigger hot reload
</OverlayScrollbarsComponent>
```

Everytime i save the file, I get this error in console:

![image](https://user-images.githubusercontent.com/16108768/224701781-a7ecb9ec-c17e-492e-bbde-03347d2db8e5.png)

**Comment by KingSora** [comment]
@filipbekic01 Good day :)

I'll take a look as soon as I have time

**Comment by KingSora** [comment]
@filipbekic01 I've taken a look now and can't reproduce the issue with `vite v4.2.1` and `vue v3.2.47`. Please confirm this issue still exists and share your versions.

**Comment by KingSora** [comment]
@filipbekic01 I'll close this issue due to inactivity and also due to the fact that I never could reproduce it. In case this issue still persists please don't hesitate to re-open this issue.
