### ISSUE TITLE
Not scrolling onKeyDown

### ISSUE THREAD

**Issue by renzoyyan** [KingSora/OverlayScrollbars#513]
**Describe the bug**
I am trying to implement mention in tiptap and adding overlayscrollbar/react. However, the link below is outdated and the scroll function is seems not available in the latest version.

**To Reproduce**

1. Go to suggestions folder
2. Click on SuggestionDropdown.tsx
3. Scroll down to scrollSelectedItemIntoView inside useEffect

**Expected behavior**
It should be similar behavior in the link below the suggestion part 

**Examples**
https://codesandbox.io/s/tiptap-0sqm3i?file=/src/extensions/suggestions/SuggestionDropdown.tsx:1059-1404

**Environment**

- Used Operating System(s): Windows 11
- Used Browser(s) (with version): Chrome Version 111.0.5563.111

**Additional context**

**Comment by KingSora** [comment]
Good day @renzoyyan 

`v2` of `OverlayScrollbars` currently has no `scroll` function. You can always use the native browser api to scroll though... I'm already working on a replacement but until then you can use the function I've created here: https://codesandbox.io/s/elated-lucy-7igb9n?file=/src/extensions/suggestions/SuggestionDropdown.tsx

**Comment by renzoyyan** [comment]
Thank you very much! It was truly life-saving assistance. @KingSora

**Comment by KingSora** [comment]
@renzoyyan youre welcome :)
