### ISSUE TITLE
Using `scroll-behavior: smooth` breaks UX consistency for scroll-handle dragging in comparison to native behavior

### ISSUE THREAD

**Issue by iolyd** [KingSora/OverlayScrollbars#515]
**Describe the bug**
A scroll element that has its css `scroll-behavior` set to `smooth` will, for the most part, work as expected. But the scrollbar's handle can hardly be dragged as the browser's smooth scrolling behavior appears to be applied in an excessive manner.

**To Reproduce**

1. Create an app / page with the following css:
   ```css
   :root {
     scroll-behavior: smooth;
   }
   ```
2. Initiate os on the document's body:
   ```ts
   const os = OverlayScrollbars(document.body, {
     showNativeOverlaidScrollbars: true,
     paddingAbsolute: false,
     scrollbars: {
       dragScroll: true,
       clickScroll: true,
       pointers: ['mouse', 'touch', 'pen'],
     },
   });
   ```
3. Try to scroll the page by dragging the scrollbar's handle
4. Observe the page barely moving or scrolling with an excessive delay / smoothing

**Expected behavior**
Like native scroll behaves, drag scroll should not be subject to scroll smoothing.

**Examples**
Please create a small example of the bug.
To do this you can use online platforms like [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/). You can also create a separate Github repository which I can clone.

**Environment**

- Used Operating System(s): MacOS Big Sur 11.7.4
- Used Browser(s) (with version): Chrome Version 111.0.5563.110 (Official Build) (x86_64)

**Additional context**
I haven't delved into OverlayScrollbar's code. But I presume this is related to smoothing being applied in excess by the browser following successive calls to `scrollTop` or some other dom method by OS to programmatically apply scroll when users drag a handle. (A somewhat similar case for another package is discussed here: https://github.com/Norserium/react-indiana-drag-scroll/issues/53, maybe the approaches pointed out could give some guidance)

One solution is for people like myself to manually add a class that unsets `scroll-behavior` whenever a drag-scroll occurs. But I feel like this should maybe be handled by the library itself as I don't see any viable cases where one would want smooth scrolling to persist in this situation as it deviates from the native behavior and breaks UX consistency. Moreover, correct me if I'm wrong, but OS doesn't apply a `os-dragging` class anymore, so I understand that I would be required to add my own event handler for the time being?

**Comment by KingSora** [comment]
@iolyd Sorry for the long delay but the fix is already pushed. This will be fixed in the next release :)

**Comment by KingSora** [comment]
@iolyd `v2.2.0` just released which should fix this issue :)

**Comment by KingSora** [comment]
@iolyd I'll close the issue for now. In case I've overlooked something or you have further issues please don't hesitate to open a new issue or to answer in this issue.
