### ISSUE TITLE
OverlayScrollbar does not respond with CSS visibility changes

### ISSUE THREAD

**Issue by Reverier-Xu** [KingSora/OverlayScrollbars#517]
**Describe the bug**

Hi, thank you for your awesome work!

I'm using OverlayScrollbars with tailwindcss and daisy UI now, and i'd like to write a long list which could be collapse using [this css class](https://daisyui.com/components/collapse/), but OverlayScrollbars seems does not respond when I expand the content.

![image](https://user-images.githubusercontent.com/41937333/232549160-101701fd-534c-4678-a8f1-0d06786a43ff.png)

It just acts like `overflow: hidden;`.

**To Reproduce**

I wrote a minimum demo [here](https://github.com/Reverier-Xu/OverlayScrollbars-CollapseBug), just clone it and run

```
npm install && npm dev
```

**Expected behavior**

![image](https://user-images.githubusercontent.com/41937333/232548806-068313c5-a797-4d7b-948d-7c4890dd28df.png)
 
when expand children, the scrollbar will also grows.

**Environment**

- Used Operating System(s): Linux x86_64
- Used Browser(s) (with version): Microsoft Edge 112.0.1722.48, Firefox 112.0, Google Chrome 114.0.5696.0 (could reproduce on all my browsers)

**Comment by Reverier-Xu** [comment]
Hi, I found that it just does not respond any changes that made by CSS selectors.

```
<template>
  <div class="container">
    <OverlayScrollbarsComponent style="height: 100%; width: 100%;" defer>
      <input type="checkbox" class="checkbox" />
      <div class="content">
        <ul>
          <li>Content</li>
          <li> ...... A lot of content ...... </li>
          <li>Content</li>
        </ul>
      </div>
    </OverlayScrollbarsComponent>
  </div>
</template>

<script setup lang="ts">
import { OverlayScrollbarsComponent } from 'overlayscrollbars-vue'
</script>

<style>
html, body, #app {
  margin: 0 0;
  padding: 0 0;
  height: 100%;
  width: 100%;
}

#app {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.container {
  height: 320px;
  width: 320px;
  border: 1px solid black;
}

.content {
  display: none;
}

.checkbox:checked ~ .content {
    display: flex;
}
</style>
```

**Comment by KingSora** [comment]
Good day @Reverier-Xu :)

Thats not a bug and more of a limitation of the `MutationObserver`. You can use the `update.elementEvents` option to include automatic updating in case elements fire certain events. In the case of the `checkbox` example you can use the option like:

```js
{ 
  update: { 
    elementEvents: [
      ["[type='checkbox']", "click"],
    ]
  } 
}
```

This will trigger a update as soon as an element with the selector `[type="checkbox"]` emitted a `click` event. 

For the `daisyUI` problem I'm not 100% certain but I believe you need to add a update to the `transitionend` event. So something like this should fix both issues:

```js
{ 
  update: { 
    elementEvents: [
      ["[type='checkbox']", "click"],
      ["*", "transitionend"],
    ]
  } 
}
```
