### ISSUE TITLE
Is there a way to initialize without layout changed 

### ISSUE THREAD

**Issue by Calvin1121** [KingSora/OverlayScrollbars#521]
Is there a way to initialize without layout changed? I need to customize the scrollbar. And still need keep the layout, cuz some fixed items in the wrapper. I tried the target and viewport mode on version 5.2.1(to support IE ),but it doesn’t work for me. Somebody could help me? Thx!

**Comment by KingSora** [comment]
@Calvin1121 Good day :)

I am not sure if I understand.. What do you mean with "keep the layout"?

**Comment by Calvin1121** [comment]
> 

Good day~
I just hope when I initialization, no change on design layout, and don't want OverlayScrollbars to generate its own elements. 
![image](https://user-images.githubusercontent.com/31435496/233573936-6a77e6f6-a96f-4099-9477-3f31d28baf87.png)
but it didn't work.

**Comment by Calvin1121** [comment]
@KingSora Good day~ as the pics showed;
![image](https://user-images.githubusercontent.com/31435496/233777326-b3b423af-087b-44f2-8b35-deb7b57101f1.png)
![image](https://user-images.githubusercontent.com/31435496/233777509-9f8ab68d-fb1a-4d07-b38a-0c6a36f4452f.png)
the first pic, the layout before initialization， and second one is after initialization, and now, i just hope OverlayScrollbar only generate two scrollbars element. Cuz I used modal component in the 'content-target'. And I use the code as the demo showed, initial it with Object that contains 'target' & 'viewport'. but it didn't work.

**Comment by KingSora** [comment]
I've created an example for which should achieve your desired markup: https://stackblitz.com/edit/vue-gh8sgu?file=src%2Fcomponents%2FHelloWorld.vue 

Note that the elements: `.os-scrollbar` and `.os-size-observer` are always injected and there is no way to don't do it since those are key building blocks of the plugin.

**Comment by KingSora** [comment]
For completeness: There is a possibility to initialize the plugin like this:

```js
OverlayScrollbars({
  target: myTarget,
  elements: {
    viewport: myTarget,
  }
}, {});
```

Which will initialize the plugin in a single element without any additional elements.
