### ISSUE TITLE
Scrollbar not showing on React

### ISSUE THREAD

**Issue by TheReidZhang** [KingSora/OverlayScrollbars#522]
**Describe the bug**
The scrollbar unless I create a parent div and specify its height. (height: 100% is not working though). Any insights will be appreciated. 

**Expected behavior**
The scrollbar shows up

**Examples**
Please create a small example of the bug.
https://codesandbox.io/p/sandbox/vigorous-thunder-q2n0c7

**Comment by KingSora** [comment]
Good day @TheReidZhang 

Thats expected in your example. If you would replace the `OverlayScrollbarsComponent` in your example with a `div` which has `overflow: auto` as its styling you would get the same result.

If you want the whole window / body to be wrapped with `OverlayScrollbars` you have to initialize `OverlayScrollbars` in the `index.js` (in your case) or where you create the react root:

```js
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { OverlayScrollbars } from "overlayscrollbars";
import App from "./App";

const rootElement = document.getElementById("root");
const root = createRoot(rootElement);
const osInstance = OverlayScrollbars(document.body, { scrollbars: { autoHide: "scroll" } });

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);

```

**Comment by TheReidZhang** [comment]
Greatly appreciated. Confirm the approach is working for me now. 

Another question is that is it possible to styling the scrollbar so that it will not show on the header part (essentially padding top the header's height). It seems that `--os-padding-perpendicular` is `padding-y`. 
Is it possible to when load the overlay scrollbar, dynamically calculate the header height and padding such height？

**Comment by KingSora** [comment]
@TheReidZhang You could point the `--os-padding-perpendicular` variable to a different css variable which you control and set via javascript.. That would be the easiest way.

**Comment by KingSora** [comment]
@TheReidZhang I'll close the issue for now. In case you have any other questions please don't hesitate to create a issue / discussion. :)
