### ISSUE TITLE
 I can't hide the ugly scrollbars in the browser. 

### ISSUE THREAD

**Issue by freedomwebcn** [KingSora/OverlayScrollbars#523]
**Describe the bug**
"I'm using overlayscrollbars and a virtual scrolling library vue-virtual-scroller, but I can't hide the ugly scrollbars in the browser. I need to add .scroller::-webkit-scrollbar {display: none;} to hide them. Can you help me see what's wrong? Thank you."

**Examples**
https://codesandbox.io/s/white-night-v3c6h6?file=/src/App.vue

**Comment by KingSora** [comment]
@freedomwebcn good day :)

What was the solution to your problem?

**Comment by freedomwebcn** [comment]
yes,thx u.👍
