### ISSUE TITLE
How about a tampermonkey userscript to make Windows Edge work like a macOS browser

### ISSUE THREAD

**Issue by westwong0622** [KingSora/OverlayScrollbars#524]
In Windows 11, Edge browser no longer provides a minimal overlay scrollbar. Additionally, the scrollbar does not automatically hide. All I want is a clean and distraction-free web page.

**Comment by KingSora** [comment]
@westwong0622 Good day :)

I really don't understand the issue. Just to be clear This is a plugin which developers can apply to their pages, not a plugin for browsers which users can install.

**Comment by westwong0622** [comment]
I know, but Edge really sucks at OverlayScrollbars
I did not find a good solution yet.

**Comment by neoOpus** [comment]
What hinders having this as a userscript, addon, or browser extension that could be installed to replace the scrollbar on websites, except for those with their unique replacements? Implementing this universally could enhance the appearance of various websites across different browsers.
