### ISSUE TITLE
I am using virtual scrolling, but after initializing overlayscrollbars, the virtual scrolling does not work and the complete list data is not displayed.

### ISSUE THREAD

**Issue by freedomwebcn** [KingSora/OverlayScrollbars#530]
You can delete the initialization OverlayScrollbars code to observe the differences，thanks。

https://codesandbox.io/s/pensive-ganguly-8uprjv?file=/src/App.vue

**Comment by KingSora** [comment]
@freedomwebcn This issue has a lot of similarities with https://github.com/KingSora/OverlayScrollbars/issues/526 please just follow the statement at the end of that issue:

> `v2.2.0` just released which should make your initial example work as well. Here is your initial example just with overlayscrollbars `v2.2.0`: https://codesandbox.io/s/nervous-ardinghelli-fgxqbh?file=/src/App.vue

**Comment by freedomwebcn** [comment]
> @freedomwebcn This issue has a lot of similarities with #526 please just follow the statement at the end of that issue.
> 
> Here is your example with small tweaks and `overlayscrollbars` `v2.2.0`: https://codesandbox.io/s/nervous-ardinghelli-fgxqbh?file=/src/App.vue

Thank you, you solved my problem. Have a nice day.
