### ISSUE TITLE
NextJS - extendParams is not a function 

### ISSUE THREAD

**Issue by AmirVahedix** [KingSora/OverlayScrollbars#537]
In the base installation of Next JS 13 (using the app dir, ...), wrapping a component with the **OverlayScrollbarsComponent** or using the **useOverlayScrollbars** hook, Gives me this error:
`Error: extendParams is not a function `

**Comment by KingSora** [comment]
Good day @AmirVahedix 

Unfortunately I can't really help you with this limited amount of information... Is it possible for you to create a reproduction repository or example which I can take a look at?

**Comment by KingSora** [comment]
@AmirVahedix I'm closing this issue beacuse of inactivity. In case you are still interested in a solution please don't hesitate to reply here or to open a new issue
