### ISSUE TITLE
does the project will support react?

### ISSUE THREAD

**Issue by Tindtily** [KingSora/OverlayScrollbars#54]
as subject

**Comment by KingSora** [comment]
I definitely plan to support it, as well as **angular** and **vue**. My problem is, I haven't done much with these frameworks thus I'm not quite ready to write a proper wrapper.

**Comment by mavrick** [comment]
+1

**Comment by KingSora** [comment]
Good day everyone!

I've created a **React** Component prototype. You can test and review it [here](https://codesandbox.io/embed/n0yo3y58ol).
**To all react experts:** Please review my approach and tell me if something should be improved.

**Comment by hamed-ehtesham** [comment]
I've created a [**Vue** Component](https://github.com/parsisolution/os-vue)

**Comment by eos87** [comment]
> Good day everyone!
> 
> I've created a **React** Component prototype. You can test and review it [here](https://codesandbox.io/s/816j8z207j).
> **To all react experts:** Please review my approach and tell me if something should be improved.

Hi @KingSora, perhaps you can put it in a separate branch in order to test it easily with other code. Thanks for you great work!

**Comment by KingSora** [comment]
Good day @eos87!

Yes I've thought of that too and I'll propably do it like this. The `react`, `vue` and `angular` versions are actually quite far and almost finished. I've also done a `ember` and `aurelia` version, but currently I've not enough time to finish everything up. 

Also I haven't made up my mind about the whole TypeScript thing, since I could write every wrapper in TypeScript, so I don't have to write separate typings for each wrapper. But then again... not every framework is supporting TypeScript and it could be weird to use / implement a component which is written in it. - Maybe you (or someone else who reads this) have a opinion / advice about this?

**Comment by multicam** [comment]
Hi there,

here is a hook version on @KingSora react component

```jsx

const ScrollerHook = props => {

    const ref = useRef()
    const [osInstance, setOsInstance] = useState(null)

    useEffect(() => {
        setOsInstance( OverlayScrollbars(ref.current, props.options || {}, props.extensions) );

        return () => {
            if( osInstance && osInstance.destroy ) osInstance.destroy()
        }

    }, []);

    return (
        <div {...props} ref={ref}>
            {props.children}
        </div>
    )
}
```

**Comment by eos87** [comment]
> Also I haven't made up my mind about the whole TypeScript thing, since I could write every wrapper in TypeScript, so I don't have to write separate typings for each wrapper. But then again... not every framework is supporting TypeScript and it could be weird to use / implement a component which is written in it. - Maybe you (or someone else who reads this) have a opinion / advice about this?

Typescript is really widely used these days I think. Writing it on Typescript shouldn't be weird as long as offering the JS version of it, perhaps this could be achieved in the build process? I've seen a few libraries doing this in order to keep the support for projects that don't have Typescript in their stack.

**Comment by KingSora** [comment]
@eos87 Thanks for you opinion! Could you provide the repos of the libraries you mentioned? Perhaps I could use them as guide as I'm not 100% sure how to do it.

**Comment by agusterodin** [comment]
@multicam thanks for posting!!! I completely overlooked the use of hooks. Your example can be tweaked to not even need the useState hook. useRef can also be used to store any mutable value (not just dom node references). You could create an "instance variable" using useRef and set/get the value through the .current property. See: https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables

**Comment by agusterodin** [comment]
@multicam Does your example definitely work? For some reason it causes all sorts of weird issues. I am assuming that react's virtual DOM has no awareness of anything overlay scrollbar related once initialized and as a result goes haywire since the two are out of sync. The virtual DOM only writes patch updates to DOM and never reads from it.

**Comment by KingSora** [comment]
@Tindtily @multicam @eos87 @agusterodin 
I've created a separate branch with the current implementation of `overlayscrollbars-react`: https://github.com/KingSora/OverlayScrollbars/tree/overlayscrollbars-react/wrapper

Please feel free to check it out and give some feedback. The example app can be found in the `example` folder.

Thanks!

**Comment by agusterodin** [comment]
@KingSora

I tried it and it doesn't work. It may be because I'm trying to wrap my whole website in an overlay scrollbar. Scrollbar doesn't appear. Every time a page changes (react router), a mass amount of space gets added to the top of the page.

Let me know if there is any way I can help

**Comment by KingSora** [comment]
@agusterodin The `component` isn't exactly here for wrapping the whole page. In the `example` app I've done this, but without the `component`. You can check it out [here](https://github.com/KingSora/OverlayScrollbars/blob/overlayscrollbars-react/wrapper/overlayscrollbars-react/example/src/index.js#L10).

The component should be working everywhere else.

**Comment by KingSora** [comment]
Alright everyone, I've pushed a `react`, `vue` and `angular` wrapper to the repo. These aren't up on npm right now, as I need to write a `README` for each wrapper first and until this is finished you can give final feedback.

React: https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-react
Vue: https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-vue
Angular: https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-ngx

Each wrapper is written in `TypeScript` and has its own typings. The file structure of each wrapper is the same:
- `dist` folder contains the bundled files
- `dist/types` folder contains the (generated) TypeScript definitions
- `src` folder contains the source TypeScript files
- `example` folder contains a example app in the corresponding framework

All example apps are the same, it's essentially always the same app just rewritten in each framework to show the differences in usage. The example apps are also written in TypeScript.

**NOTE:** You are responsible to import the `OverlayScrollbars.css` file by yourself. The `component` **doesn't** do it for you as the styles are **global styles**! As each framework has different methods of how to do this, I'll link the line in each example app (how I achieved that, you can use your own method if its better):

React: [index.tsx#L1](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-react/example/src/index.tsx#L1)
Vue: [main.ts#L1](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-vue/example/src/main.ts#L1)
Angular: [styles.css#L1](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars-ngx/example/src/styles.css#L1)

Thanks for your future feedback!

**Comment by KingSora** [comment]
The long journey is now over. I've added a corresponding [section](https://github.com/KingSora/OverlayScrollbars#framework-wrapper) to the README. If you have troubles or issues with any of the wrappers, please don't hesitate to open a issue **new issue**.
