### ISSUE TITLE
Native scrollbar is visible on mobile view

### ISSUE THREAD

**Issue by vakers2** [KingSora/OverlayScrollbars#545]
**Describe the bug**
Native scrollbar is visible on mobile view.

**Expected behavior**
Only native or custom visible

**Examples**
I am using this code in my project:

```
    const options = {
        scrollbars: {
            theme: 'os-theme-custom',
            autoHide: 'scroll',
        },
    };
    const [initialize] = useOverlayScrollbars({ options, defer: true });

    useEffect(() => {
        initialize(document.body);
    }, [initialize]);
```

Also this issues exists on [demo page](https://kingsora.github.io/OverlayScrollbars/). 
![image](https://github.com/KingSora/OverlayScrollbars/assets/27016370/9ded4296-6d26-4e21-863c-f58fbe872736)

**Environment**

- Used Operating System(s): Android, IOS
- Used Browser(s) (with version): Chrome, Safari

**Additional context**
Not sure if I need some additional options to fix this issue

**Comment by KingSora** [comment]
@vakers2 Good day :) 

I'm not observing this to be honest.. Are you able make a live example for me so I can inspect the issue in the browser?
Also on mobile please make sure that you are not zoomed in, because otherwise the scrollbars will always appear (its impossible to hide those because those are not normal scrollbar but more of a possibility to move a zoomed in viewport)

**Comment by KingSora** [comment]
@vakers2 OverlayScrollbars evaluates its environment only once when the first instance is created. Every subsequent initialization is using the already evaluated environment. 

So when you change the browsers environment (which is not really possible outside of the browsers dev tools) you need to refresh the page. - This means every time you start emulating a mobile screen or a different device please also refresh the page so the plugin can adapt.

Please try it again with that knowledge and report back if it still happens.

**Comment by vakers2** [comment]
I see, It works correctly on demo page then. Thank you. Do I need to use 
``` cancel: {
   nativeScrollbarsOverlaid: true,
 } ```
for OverlayScrollbars to work the same way in my app?

**Comment by KingSora** [comment]
This option will force the plugin to cancel initialization in case the native system scrollbars are overlaid already. `Android`, `iOS` and `macOS` are systems where the system scrollbars are overlaid 99% of the time.

You can add that if you want this behavior, but you don't have to.

**Comment by vakers2** [comment]
Thank you.

**Comment by dannybeckett** [comment]
Another possible workaround is detailed in #622
