### ISSUE TITLE
The scroll handle appears but doesn't move??

### ISSUE THREAD

**Issue by saeideh-mardan** [KingSora/OverlayScrollbars#56]
Hi,

I have used the following code:

<head>   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    **<link rel="stylesheet" href="./css/OverlayScrollbars.css">**
    **<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>**
</head>

<body>
    <div style="height: 300px;  overflow: hidden;">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod blanditiis commodi maxime, maiores, ipsum ducimus sit, ipsa nisi corporis vero consectetur eligendi iste illo excepturi quibusdam praesentium quis laudantium voluptas!</p>    
    </div>
    
    </body>
    **<script src="./js/jquery.overlayScrollbars.min.js"></script>**
    <script>
$("div").overlayScrollbars({});
</script>
</html>

**Comment by KingSora** [comment]
Good day!

Could you create a small sample on [https://jsfiddle.net/](https://jsfiddle.net/)? I can't reproduce your problem, and your code above desn't really help me. Thanks!

**Comment by KingSora** [comment]
I'll close this issue due to inactivity. Please feel free to post any news, I'll reopen the issue in that case.
