### ISSUE TITLE
Weird Double Tap Behaviour on Mobile IOS Devices

### ISSUE THREAD

**Issue by jeremiaswijaya** [KingSora/OverlayScrollbars#560]
**Describe the bug**
When using iPhone (Chrome and Safari), clicking on `<a>` tag with href, inside the scroll bar wrapper, requires double tap

**To Reproduce**
I've tried in Android and iPhone, and it worked on Android but not on the iPhone. The browser that I'm using is the latest version of Google Chrome (Android and iPhone) and Safari (on iPhone)

- Wrap interactable elements (such as button with click event, or `<a>` tag) with OverlayScrollbars
- Tap once on the element. Your browser wont redirect you to the href element, instead, the scrollbar will appear.
- Tap once again on the element. Your browser should open a new tab that redirects to Google.
- If we unfocus and let the scroll bar disappear, then tap again on the `<a>` tag, it wont trigger the tag. The scroll bar will just appear. When the scroll bar appeared and you tap on the `<a>` element again, your browser should open a new tab and redirects you to Google.

**Expected behavior**
Clicking element once should trigger `<a>` tag

**Examples**
Open this JS Fiddle **on any IOS device** (Safari / Chrome should do the work) https://jsfiddle.net/jeremiasrama/s5oapue4/show

Try using the steps in reproduce section to reproduce the problem.

https://github.com/KingSora/OverlayScrollbars/assets/80539853/a0e7298c-d85b-4ed0-b5b7-8ecd74fbf370

Notice that when the scrollbar appeared, it happened when I tap on the `<a>` element

**Environment**
- Used Operating System(s): IOS
- Used Browser(s) (with version): Safari / Chrome latest version

**Additional context**
Might related to https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by KingSora** [comment]
@jeremiaswijaya Thanks for this issue!

I'll take a look as soon as I have time

**Comment by KingSora** [comment]
@jeremiaswijaya I believe I've fixed the issue. Please test it out yourself with this fiddle: https://jsfiddle.net/7oe6hruk/15/ and report back you findings :)

**Comment by jeremiaswijaya** [comment]
@KingSora Awesome, it's working perfectly 👌, thanks for the help!

**Comment by KingSora** [comment]
I've published [`v2.3.1`](https://www.npmjs.com/package/overlayscrollbars/v/2.3.1) where this issue should be fixed :)

Related: https://github.com/KingSora/OverlayScrollbars/issues/285
