### ISSUE TITLE
t.animate is not a function.

### ISSUE THREAD

**Issue by yuchiXiong** [KingSora/OverlayScrollbars#562]
**Describe the bug**
Now OverlayScrollbars seems to use the HTMLElement.prototype.animate API. 

However, the minimum version requirement of this API on IOS devices is [IOS13.4](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate), when I used OverlayScrollbars on IOS13.3.1 device, OverlayScrollbars tell me "t.animate is not a function". then blocking the subsequent logic of the page.

I found a [github repo](https://github.com/web-animations/web-animations-js) that provides a working solution, and now I want to know if OverlayScrollbars can provide a corresponding solution (……or make this issue more effective to help other people who encounter similar problems? 😂😂😂)

**To Reproduce**

1. find a IOS devices and need IOS version less than 13.4
2. install OverlayScrollbars and init it
3. check the console
4. now you can see a "t.animate is not a function" error.

**Expected behavior**
Is it possible for OverlayScrollbars to be compatible with it?
(Or I hope this issue can effectively help other developers who may face this problem solve this problem😂)

**Comment by KingSora** [comment]
Good day @yuchiXiong 

OverlayScrollbars should only use `element.animate` when the browser also supports the [ScrollTimelineApi](https://developer.mozilla.org/en-US/docs/Web/API/ScrollTimeline). I just forgot to guard the call to `element.animate` in this case.

I'll fix this as fast as possible an release a new patch versin

**Comment by KingSora** [comment]
@yuchiXiong I've published [`v2.3.2`](https://www.npmjs.com/package/overlayscrollbars/v/2.3.2) which should fix this bug. Please try it out and report back to me :)

**Comment by yuchiXiong** [comment]
> @yuchiXiong I've published [`v2.3.2`](https://www.npmjs.com/package/overlayscrollbars/v/2.3.2) which should fix this bug. Please try it out and report back to me :)

It's working great now, that's cool! 🎉🎉🎉

**Comment by ellockie** [comment]
This was breaking a bunch of unit tests, thank you for fixing it, @KingSora !
