### ISSUE TITLE
Scroll functions required !

### ISSUE THREAD

**Issue by sujith-sairam** [KingSora/OverlayScrollbars#567]
I am currently working on scroll functions ,where It requires me to navigate to a specific element . I am currently using js **ScrollTo** method with  **scrollOffsetElement** which is pretty complex to achieve . Is there any way to overcome this issue with built-in methods of os-scrollbar in **version-2**.

**Comment by KingSora** [comment]
Good day @sujith-sairam 

I'm not sure if I understand you correctly... do you have an code example for me? Maybe the [ScrollIntoView}(https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) is also helpful to you

**Comment by sujith-sairam** [comment]
` const scrollIntoView = $("#left_sidebar_nav_menu a.active");`
  `const parentElement = $("#left_sidebar_nav_menu");`
 ` const {scrollOffsetElement} = scrollbar.elements();`
 ` const activeTop = scrollIntoView[0].getBoundingClientRect().top;`
 ` const parentTop = parentElement[0].getBoundingClientRect().top;`
 ` let topPosition =  (activeTop - parentTop) - (scrollOffsetElement.getBoundingClientRect().height / 2);`
       ` scrollOffsetElement.scrollTo({`
          `behavior: 'smooth',`
         ` top: topPosition ,`
       ` });`
    `}`
 ` }`
 
 I need to navigate to active element. The instance of scrollbar is created with the **parentElement** in another file .It would be help full if you provide function like **scroll** method in previous version . The  ScrollIntoView Function does not accept the target element as option @KingSora.

**Comment by sujith-sairam** [comment]
@KingSora Thanks for your reply **ScrollIntoView** worked fine !!.
