### ISSUE TITLE
Extension for chat projects

### ISSUE THREAD

**Issue by fpdrozd** [KingSora/OverlayScrollbars#57]
Hello!

I wrote a simple extension for my own project and I decided to make it public. It makes scrolling box behavior a little more intuitive in terms of using OverlayScrollbars with a chat.

For example the situation when you try to load old messages but you don't want your messages to be "pushed down" by the prepended messages. Or when you want to see the newest message.

You can find it [here](https://github.com/fpdrozd/OverlayScrollbarsChat). Maybe it will be useful to someone :)

**Comment by KingSora** [comment]
Thank you very much for sharing your extension! - I'll review it if I have time and will list it on the official OverlayScrollbars github page.

**Comment by KingSora** [comment]
Good day!

I've reviewed your extension and everything looks fine. - Good job!
One small thing has to be changed though:

Currently you have to register the extension manually with:
```javascript
OverlayScrollbars.extension('osChat', OverlayScrollbarsChat);
```
Please do this in your script so the user doesn't has to do it by himself. - So if somebody uses your script the extension gets registered automatically. (if possible please also match the registered extension name with your repository name)

After this change you would have to import the OverlayScrollbars file first and then your extension file. This is the intended behavior. Don't forget to change your documentation accordingly.

Lastly please add the topic `overlayscrollbars-extension` to your repo. Only with this topic your extension can be listed on the [Extensions page](https://kingsora.github.io/OverlayScrollbars/#!extensions).

**Comment by fpdrozd** [comment]
Thank you for the suggestions :) I have implemented them into the project.

**Comment by KingSora** [comment]
Thank you too! :)
