### ISSUE TITLE
component fails to initialize when using react-window

### ISSUE THREAD

**Issue by s-ras** [KingSora/OverlayScrollbars#573]
I followed the instructions on how to use OverlayScrollbars alongside react-window. However I used plugins that come with react-window, particularly react-virtualized-auto-sizer and react-window-infinite-loader. Problem is, there seems to be a problem with the initialization of OS instance as the outer ref seems to be null upon rendering and once the component (in this case FixedSizeList) is rendered, even though the outer ref is no longer null, OS still doesn't initialize. I tried adding outerRef and rootRef to the list of useEffects dependencies and it still won't work. 

here's the code I'm using:

```typescript
	const rootRef = useRef(null);
	const outerRef = useRef(null);

	const [initialize, osInstance] = useOverlayScrollbars({
		options: {
			scrollbars: {
				theme: "os-theme-dark",
				autoHide: "move",
				dragScroll: true,
				pointers: ["mouse", "touch", "pen"],
			},
		},
	});

	useEffect(() => {
		if (rootRef.current && outerRef.current) {
			initialize({
				target: rootRef.current,
				elements: {
					viewport: outerRef.current,
				},
			});
		}
		return () => osInstance()?.destroy();
	}, [rootRef.current, outerRef.current, osInstance, initialize]);

	//////////////////////////////////////////

	return (
			<div
				data-overlayscrollbars=""
				ref={rootRef}
				style={{
					width: "100%",
					height: "100%",
				}}
			>
				<AutoSizer>
					{(size: Size) => (
						<InfiniteLoader
							itemCount={count}
							loadMoreItems={loadMore}
							isItemLoaded={isLoaded}
						>
							{({ onItemsRendered, ref }) => (
								<FixedSizeList
									width={size.width}
									height={size.height}
									itemCount={count}
									itemSize={70}
									outerRef={outerRef}
									itemData={list}
									onItemsRendered={onItemsRendered}
									ref={ref}
								>
									{renderRow}
								</FixedSizeList>
							)}
						</InfiniteLoader>
					)}
				</AutoSizer>
			</div>
	);

```

**Comment by KingSora** [comment]
@s-ras I've managed to create an example with the mentioned libraries myself:

https://codesandbox.io/s/relaxed-smoke-tdpnyl?file=/index.js

I hope this solves your problem :)

**Comment by KingSora** [comment]
@s-ras I'll close the issue because of inactivity... In case you have any feedback regarding this please don't hesitate to post it here!

**Comment by H4JUN** [comment]
@KingSora, thanks for the amazing library!
I am also having the same issue. I managed to fix it by creating a ref for `<AutoSizer>` using `useRef`  and added that to the `useEffect` dependency.
However, I wanted to see if that's how you meant to solve it but the link to the codesandbox is broken.

Could you please share your solution again?
