### ISSUE TITLE
When navigating between pages using Link the window isnt at the top of the page

### ISSUE THREAD

**Issue by glassesUSA** [KingSora/OverlayScrollbars#576]
**Describe the bug**
When scrolling down and hitting a Link component, the page navigates slightly scrolled down

**To Reproduce**

1. Go to https://optimaxeyewear.gusadev.com/vendors/glassesusa/
2. Click on the button on Discover Our Brands
3. Observe

**Expected behavior**
Window should be at the top of the page

**Examples**
Please create a small example of the bug.
To do this you can use online platforms like [JSFiddle](https://jsfiddle.net/), [CodeSandbox](https://codesandbox.io/) or [StackBlitz](https://stackblitz.com/). You can also create a separate Github repository which I can clone.

**Environment**

- You need to be on a desktop device 

**Additional context**
NextJS latest version

**Comment by glassesUSA** [comment]
Apologies - I sent the wrong link! https://optimaxdev.github.io/optimaxeyewear/vendors/glassesusa - This is the new site that has the issue

**Comment by KingSora** [comment]
@glassesUSA there seems to be an issue with the initialization because the `body` elements initialization is a bit special. Are you able to share your code with me?

**Comment by KingSora** [comment]
At this point I'm fairly certain that you're doing something like this:

```js
<OverlayScrollbarsComponent element="body">
</OverlayScrollbarsComponent>
```

To initialized OverlayScrollbars to / as the `body` element. The problem here is that the `OverlayScrollbarsComponent` wasn't really designed to do that. Its intended usecase is to use it for everything besides the `body` element.

Please use the `useOverlayScrollbars` hook for the initialization instead:

```jsx
const MyComponent = () => {
  const bodyRef = useRef(null);
  const [initialize, osInstance] = useOverlayScrollbars({ options, events, defer });
 
 useEffect(() => {
   const { current: body } = bodyRef;
   if (body) {
     initialize(body);
     
     return () => osInstance()?.destroy();
   }
 }, [initialize, osInstance])
 
  return (<body ref={bodyRef} data-overlayscrollbars-initialize="">
    content
  </body>);
}
```

**Comment by glassesUSA** [comment]
Perfect thank you!
