### ISSUE TITLE
Scroll to top don't work

### ISSUE THREAD

**Issue by bahmansh** [KingSora/OverlayScrollbars#58]
Hi
I have used overlay scroll for some part of my page, such as <body>, <div> and ...
When I use overlay scroll scroll to top not work.
 $('html, body').animate({ scrollTop: 0 }, 800); 

Also your code not work too.

//$ovelayScrollInstance.scroll([0, "100%"], 2500);
//$ovelayScrollInstance.scroll({ el: $('body'), block: { y: "begin", x: "nearest" } });
//$ovelayScrollInstance.scroll({ x: "50%", y: "100%" }, 1000);

**Comment by KingSora** [comment]
@bahmansh any updates on your issue?

**Comment by KingSora** [comment]
I'll close this issued due to inactivity. If I haven't solved your issue with my answer above, please comment it here and I'll reopen the issue immediately.
