### ISSUE TITLE
Invalid keyframe value warning

### ISSUE THREAD

**Issue by Elringus** [KingSora/OverlayScrollbars#581]
After an update to the latest version of the react package I've started getting following warnings:

![110391d71136843ed38fb79c509ffecc](https://github.com/KingSora/OverlayScrollbars/assets/2056864/ced65b7f-61c4-4241-b9b1-c2fe7eba6059)

![af682f818939a5c181096b78bdb22e68](https://github.com/KingSora/OverlayScrollbars/assets/2056864/ddd22717-12bb-42cb-a858-16a3360e491e)

— I guess it should be an easy fix by just guarding against nan, but if you need a repro, I'll try to make one.

**Comment by KingSora** [comment]
@Elringus Thanks for the report!

I'll create an fix, but out of curiosity I would like to know why the `NaN` value is created (probably division by 0) but I can't trigger it in my tests.

**Comment by Elringus** [comment]
Here's how I use the plugin:

```ts
export const Scrollable = (props: Props) => {
    const ref = useRef<HTMLDivElement>(null);
    const { children, scrollX, scrollY, container, className } = props;

    const [initialize, getInstance] = useOverlayScrollbars({
        options: {
            overflow: {
                x: scrollX == null ? "scroll" : scrollX ? "scroll" : "hidden",
                y: scrollY == null ? "scroll" : scrollY ? "scroll" : "hidden"
            },
            scrollbars: { clickScroll: true }
        },
        defer: false
    });

    useEffect(() => {
        if (ref.current != null) {
            if (container == null) initialize(ref.current);
            else initialize({ target: ref.current, elements: { viewport: container } });
        }
        return () => getInstance()?.destroy();
    }, [container, initialize, getInstance]);

    return <div {...props}
                ref={ref}
                children={children}
                className={c(css.scrollable, className)}
                data-overlayscrollbars=""/>;
};
```

I've notices the warning is only triggered when I use the `<Scrollable>` for a virtual list (via [virtuoso](https://github.com/petyosi/react-virtuoso)) and only when `return () => getInstance()?.destroy();` is present. When the destructor is removed, the warning is gone (but also styling breaks, not sure why).

**Comment by Elringus** [comment]
Can confirm https://github.com/KingSora/OverlayScrollbars/commit/edc677f55c618eba2f9331a67b0e320112d02517 fixes the warnings.

I've tried making a minimal repro with just OverlayScrollbars and Virtuoso, but it didn't reproduce. It's probably more complicated.

**Comment by KingSora** [comment]
@Elringus great! I'll publish a new version soon

**Comment by KingSora** [comment]
[`v2.4.4`](https://www.npmjs.com/package/overlayscrollbars/v/2.4.4) is released and should fix this issue :)
