### ISSUE TITLE
Angular app freezes when using ngbDropdown with OverlayScrollbars

### ISSUE THREAD

**Issue by Take-Limeship** [KingSora/OverlayScrollbars#591]
**Describe the bug**
In Angular when using OverlayScrollbars with a target to a component with a ngbDropdown the app freezes.

**To Reproduce**

1. Go to https://stackblitz.com/edit/angular-ivy-vnrqsj?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
2. Click on the Dropdown above 
4. Notice how the whole app is not responsive anymore 
5. The only way I found to try again was to fork the project in StackBlitz

**Expected behavior**
It should be possible to initialize the OverlayScrollbars to a component containing a ngbDropdown without errors.

**Additional context**
We also tried ignoring all mutations and upping the debounce timeout with no avail. Is there something we missed here?
Thanks in advance!

**Comment by KingSora** [comment]
Good day @Take-Limeship :)

I'll take a look as soon as I have time

**Comment by KingSora** [comment]
@Take-Limeship You have to initialize the plugin outside of the `ngZone`:

```ts
// from your example
this.ngZone.runOutsideAngular(() => {
  OverlayScrollbars(
    {
      target: document.querySelector(
        'scrollbartest-nx-welcome'
      ) as HTMLElement,
      // target: document.body,
      elements: {
        // viewport: document.querySelector('#scroll') as HTMLElement,
      },
    },
    this.defaultOptions
  );
});
```

Here is a working example: https://stackblitz.com/edit/angular-ivy-4k2pe6?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by Take-Limeship** [comment]
That solved it, thank you very much! :)
