### ISSUE TITLE
Installing Error on Vue3

### ISSUE THREAD

**Issue by renogies** [KingSora/OverlayScrollbars#592]
Error on Vue3 :

User
While resolving: @intlify/vue-i18n-loader@5.0.0
npm ERR! Found: vue-i18n@9.6.1
npm ERR! node_modules/vue-i18n
npm ERR!   peerOptional vue-i18n@"*" from @intlify/unplugin-vue-i18n@1.4.0
npm ERR!   node_modules/@intlify/unplugin-vue-i18n
npm ERR!     @intlify/unplugin-vue-i18n@"^1.4.0" from the root project
npm ERR!   vue-i18n@"^9.6.1" from the root project

**Comment by KingSora** [comment]
@renogies good day :)

How are you tracing this error back to overlayscrollbars? The error states a completely different library

**Comment by KingSora** [comment]
@renogies I'll close this issue for now.. If you have any updates please don't hesitate to re-open or to write here
