### ISSUE TITLE
Bootstrap tooltip not working when using the plugin for body tag

### ISSUE THREAD

**Issue by TanimMahbub** [KingSora/OverlayScrollbars#601]
First of all, awesome plugin, can't thank you and appreciate you enough, still learning it, but I can feel that it's the best for the purpose so far, because I have tried almost all of them.

Anyway, the issue is, when I added it to the `body` tag, the tooltips of the page stopped showing up, it's not like the markup of the tooltips is not generating, the markup is there generating just fine, but I can't see the tooltips, can't inspect either because the tooltips markup generates only when you're hovering over the trigger.

Add the Bootstrap and the OverlayScrollbars plugin to your page, 
Activate the BS `Tooltip` and activate the OverlayScrollbars plugin for the `body` tag and any other element if you want
Now check if the Tooltip is working, you'll see it's not. 
Now deactivate the OverlayScrollbars plugin for the `body` tag and now the Tooltip is working

**Expected behavior**

**Here is an example**
[Check this PEN](https://codepen.io/Tanim_Mahbub/pen/NWJxYwr) to be more clear.

**Environment**

- OS: Window 10
- Used Browser: Google Chrome 120.0.6099.130

**Comment by KingSora** [comment]
@TanimMahbub I've checked it out and I'm not sure whos "fault" this exactly is, but for some reason popper is caulculating the viewport size incorrectly (might be because of their code, or because of OverlayScrollbars styles).

The fix would be to apply this styles:
```css
html[data-overlayscrollbars] {
	width: auto;
	height: auto;
	min-width: 100%;
	min-height: 100%;
}
```

I've done tests whether this breaks something and it seems that everything is working fine. In case I'll continue to observer this behavior I'll implement those styles in the next release which will be `v2.5.0`.

**Comment by TanimMahbub** [comment]
Thank you so much @KingSora for the fix, it works perfectly now.
I'm working on a suggestion post for the plugin and will write that as soon as possible.

**Comment by KingSora** [comment]
@TanimMahbub Looking forward to that! You're welcome to share the link here when the post is finished :)

**Comment by TanimMahbub** [comment]
I'm gonna make it as a **Feature Request** here, you'll see when post it.

**Comment by KingSora** [comment]
@TanimMahbub This workaround should not be needed anymore if you use `overlayscrollbars` `v2.4.7` or higher :)
