### ISSUE TITLE
OverlayScrollbars.scroll() function from v1 not present in v2

### ISSUE THREAD

**Issue by richard-viney** [KingSora/OverlayScrollbars#603]
The docs say `The scroll function is missing. Planned as a plugin. (WIP)` - is there a workaround for this or alternatives to achieve a similar thing?

This is blocking the upgrade from v1 to v2 for us (though v1 is still working completely fine).

Thanks.

**Comment by KingSora** [comment]
Good day @richard-viney :)

It depends on how you used the old `scroll` function - it provided many "goodies" which you (depending whether you used them) would need to adapt yourself.

Generally you can scroll like this:
```js
const { scrollOffsetElement } = osInstance.elements();
// using the native scrollTo function: https://developer.mozilla.org/en-US/docs/Web/API/Element
scrollOffsetElement.scrollTo({ top: 100, left: 100, behavior: 'smooth' });
```

If you want to scroll to a certain element you can use the [element.scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) function for that.

In case you need more features you currently have to adapt them on your own.

**Comment by KingSora** [comment]
@richard-viney does that solve your question? :)

**Comment by richard-viney** [comment]
Yep it does, thanks!
