### ISSUE TITLE
Jest with Node.js v20.11.0 does not understand overlayscrollbars-react

### ISSUE THREAD

**Issue by krutoo** [KingSora/OverlayScrollbars#604]
Hi, i noticed about "module" field in `package.json` is not standard way to define ESM entry point of package.

According this answer:
https://github.com/jestjs/jest/issues/9430#issuecomment-1905771034

Can we update `package.json` of overlayscrollbars packages for to comply with the standard?

**Comment by KingSora** [comment]
Good day @krutoo 

`overlayscrollbars-react` `package.json` looks like this: https://cdn.jsdelivr.net/npm/overlayscrollbars-react@0.5.3/package.json

It contains the `exports`, `main` and `module` fields.

**Comment by krutoo** [comment]
@KingSora i see different package.json in master branch and in node_modules of my project

**Comment by krutoo** [comment]
@KingSora hmmm, for some reason Jest does not understand that this file must be interpreted as an ESM

**Comment by KingSora** [comment]
@krutoo Could your create an example repository with your jest setuo and a library which works with it? I could take a look what could potentially be wrong there.

**Comment by krutoo** [comment]
@KingSora here is repo with problem
https://github.com/webpack/webpack/discussions/17990

just make `npm install` and `npm run test`

**Comment by krutoo** [comment]
@KingSora sorry, i fix wrong link

**Comment by Smrtnyk** [comment]
Do you need maybe "type": "module"?

**Comment by KingSora** [comment]
@krutoo @lpjune @Smrtnyk I've identified the issue and will publish a fix soon :)

The problem is that even though the package jsons `exports` field looks like this:
```js
"exports": {
  ".": {
    "require": "./overlayscrollbars-react.cjs.js",
    "import": "./overlayscrollbars-react.es.js",
    "types": "./types/overlayscrollbars-react.d.ts"
  }
}
```
Jest or node is reading the `overlayscrollbars-react.es.js` as a commonjs file. The reason being that I have no `"type": "module"` field and the fileextension of that file does not end with `.mjs` thus causing it to be read as a commonjs file.

I'm not 100% sure whether this might be a bug with jest or is intended behavior of node because I thought the `"import"` key should already mark this file as a `module`.

**Comment by krutoo** [comment]
@KingSora Please also note that the order of the keys matters according to the docs

Conditional exports
[#](https://nodejs.org/api/packages.html#conditional-exports)

> Node.js implements the following conditions, listed in order from most specific to least specific as conditions should be defined...

**Comment by Smrtnyk** [comment]
if you set "type": "module" you should not need mjs as extension
node will read .js files as es modules by default

**Comment by KingSora** [comment]
@Smrtnyk Thats true, but it would also read the `commonjs` files as `modules` in that case

**Comment by ChristophP** [comment]
Regaring the extensions
- `.mjs` is always interpreted as ESM (regardless of the type field of the closes package json up the file tree)
- `.cjs` is always interpreted as CJS (regardless of the type field of the closes package json up the file tree)
- `.js` is interpreted as ESM or CJS depending on the `type` field of the closest package json up the file tree.

In that sense if you have `type: module` set, the ESM can be called `.js` for ESM and `.cjs`. If you have no type module set or type: commonjs you can do `.mjs` for ESM and `.js` for CJS. If you wanna be absolutely sure regardsless you can use `.mjs`/`.cjs` for both.

**Comment by nickmccurdy** [comment]
I'd also recommend [linting your package with publint](https://publint.dev/overlayscrollbars-react).

**Comment by KingSora** [comment]
@ChristophP Thank you for the input - really appreciate it!

@nickmccurdy Very useful tool, I'll definitely use it before I publish the fixed versions - Thanks a bunch!

**Comment by KingSora** [comment]
I've published:
- [overlayscrollbars](https://www.npmjs.com/package/overlayscrollbars) `v2.4.7`
- [overlayscrollbars-react](https://www.npmjs.com/package/overlayscrollbars-react) `v0.5.4`
- [overlayscrollbars-vue](https://www.npmjs.com/package/overlayscrollbars-vue) `v0.5.7`
- [overlayscrollbars-solid](https://www.npmjs.com/package/overlayscrollbars-solid) `v0.5.3`
- [overlayscrollbars-svelte](https://www.npmjs.com/package/overlayscrollbars-svelte) `v0.5.3`

Which all address this issue and should hopefully fix it properly.
I've used https://publint.dev and https://arethetypeswrong.github.io/ to identifiy additional issues and fixed them where the error / warning was appropriate.

Please try it out and give feedback :)

**Comment by krutoo** [comment]
@KingSora yes, this is helps in example repo and in my project, thank you so mush

Can you tell me what exactly you did to fix this problem?

Issue can be closed i think

**Comment by KingSora** [comment]
@krutoo I've changed the package.jsons `exports` field.. I've described the problem here: https://github.com/KingSora/OverlayScrollbars/issues/604#issuecomment-1907577254

To see exactly how the I changed the files you can compare the [old](https://cdn.jsdelivr.net/npm/overlayscrollbars-react@0.5.3/package.json) and [new](https://cdn.jsdelivr.net/npm/overlayscrollbars-react@0.5.4/package.json) versions.
