### ISSUE TITLE
The 'blur' event fires when the input element with 'autoFocus' set to 'true' is wrapped with 'OverlayScrollbars'.

### ISSUE THREAD

**Issue by thalaz** [KingSora/OverlayScrollbars#605]
**Describe the bug**

If we take a regular `<input />` element, set its `autoFocus` to `true`, and wrap it with the `OverlayScrollbars` - an additional `blur` event will fire on the first render.

Reproduces in Chrome **only**.

**To Reproduce**

1. Open Chrome browser
2. Go to [With OverlayScrollbarsComponent](https://stackblitz.com/edit/bug-report-9d6408-with-component?devToolsHeight=33&file=src%2FApp.tsx) or [With useOverlayScrollbars](https://stackblitz.com/edit/bug-report-9d6408-with-hook?devToolsHeight=33&file=src%2FApp.tsx)
3. Click the refresh button provided by the StackBlitz
4. Check the **Console** - you should see one `onBlur` message

**Expected behavior**

There is no `blur` event on the initial render. The `blur` event should fire only on the actual `blur` action (clicking outside of the input).

**Examples**

- [With OverlayScrollbarsComponent](https://stackblitz.com/edit/bug-report-9d6408-with-component?devToolsHeight=33&file=src%2FApp.tsx) - with component
- [With useOverlayScrollbars](https://stackblitz.com/edit/bug-report-9d6408-with-hook?devToolsHeight=33&file=src%2FApp.tsx) - with hook
- [Without OverlayScrollbars](https://stackblitz.com/edit/bug-report-9d6408-for-comparison?devToolsHeight=33&file=src%2FApp.tsx) - without `OverlayScrollbars` (for comparison purposes)

**Environment**

- Used Operating System: macOS Sonoma 14.2.1
- Used Browsers: 
  - **Chrome** | Version 121.0.6167.85 (Official Build) (arm64) | Doesn't work
  - **Safari** | Version 17.2.1 (19617.1.17.11.12) | Works
  - **Firefox** | 122.0 (64-bit) | Works

**Additional context**

- tested in Chrome/Safari/Firefox (reproduces in Chrome **only**)
- reproduces with both the `OverlayScrollbarsComponent` component and the `useOverlayScrollbars` hook
- wrapping different parts with `useMemo`/`useCallback`/`memo`, adding `key` doesn't help
- tried with and without `StrictMode` - no difference
- tried in both `React@17.0.2` and `React@18.2.0` - no difference

**Comment by KingSora** [comment]
@thalaz Good day :)

This happens because `OverlayScrollbars` wraps your elements and thus causes the original element to lose focus (because its briefly removed / moved in the DOM). After the wrapping is done it re-focuses the originally focused element so the original behavior is restored.

May I ask what you're trying to achieve that this behavior is unwanted?

**Comment by thalaz** [comment]
@KingSora, good day :)

I'll provide you with an example of the actual case shortly.

**Comment by thalaz** [comment]
@KingSora, here is an [example](https://stackblitz.com/edit/bug-report-9d6408-usage-example?devToolsHeight=33&file=src%2FDialogExample%2Findex.tsx).

On my project, we have a lot of modals.
They differ in content and size, and since users can have different devices with different dimensions, we wanted to add a custom scrollbar to improve the UX.

We use the [MUI](https://mui.com/material-ui/getting-started/) library for styling and [react-hook-form](https://react-hook-form.com/get-started) library to handle forms.

As for the product requirements, we need to have an instant validation on the fields which is achieved with [mode: 'all'](https://react-hook-form.com/docs/useform#mode) in the example provided.
Also, I've extended the `DialogContent` as you may see in [CustomDialogContent](https://stackblitz.com/edit/bug-report-9d6408-usage-example?devToolsHeight=33&file=src%2FDialogExample%2FCustomDialogContent%2Findex.tsx) component - the only scrollable area will be the actual content of the modal.

In the example:
- pressing the "Open modal with OverlayScrollbars" button will show you the actual behaviour that I'm trying to fix
- pressing the "Open modal without OverlayScrollbars" button will show you the desired behaviour

**Comment by thalaz** [comment]
From your words, I also understand that it's the desired behaviour.

Any suggestions on how I can keep both the scrollbar and the auto-focus functionality and get rid of this behaviour?

**Comment by KingSora** [comment]
@thalaz I've created an workaround example: https://stackblitz.com/edit/bug-report-9d6408-usage-example-qtuekb?file=src%2FDialogExample%2FCustomDialogContent%2Findex.tsx

I believe I'll add something like this to the library as well.. But for now please use the workaround until I've decided how this issue should be handled

**Comment by thalaz** [comment]
@KingSora, thanks for a workaround.
It was working only on the first modal open, but I see that you updated the workaround and it seems like everything is fine now.

Waiting for the official fix :)

**Comment by thalaz** [comment]
@KingSora, it doesn't work in the [StrictMode](https://stackblitz.com/edit/bug-report-9d6408-usage-example-strict-mode?devToolsHeight=33&file=src%2FDialogExample%2Findex.tsx) though (I guess it's caused by the additional mount/unmount).

I have used HTML's dialog since MUI's dialog has it's own issue with the `StrictMode` (it loses the focus completely).

It's not a big deal for me, but just FYI.

**Comment by KingSora** [comment]
@thalaz Thanks for the feedback :)

I've revisited the problem and noticed that the functionality is easier and more reliable to implement with a `Plugin`. Here is the code: https://stackblitz.com/edit/bug-report-9d6408-usage-example-strict-mode-7mb27t?devToolsHeight=33&file=src%2Findex.tsx

This should also work with `StrictMode` I believe

**Comment by thalaz** [comment]
Thanks, @KingSora. That's a very good and tidy one. Plus will work for all usages "out of the box".

Tested in my project - works as well.

Should I consider this as a final solution and forget about this?
Or will this become a part of the `overlayscrollbars` package someday?

**Comment by KingSora** [comment]
@thalaz I'll probably add it to the library in the next version.. I'll let you know when its released :)

**Comment by thalaz** [comment]
Thanks a lot, @KingSora!

**Comment by KingSora** [comment]
@thalaz I've published [`overlayscrollbars v2.5.0`](https://www.npmjs.com/package/overlayscrollbars/v/2.5.0) which includes a fix to this issue :) Please check it out and give feedback whether it makes the workaround unnecessary

**Comment by KingSora** [comment]
@thalaz Thanks for the feedback! After revisiting the code which was supposed to fix the issue I've noticed that I'm oly covering the `focus` and `blur` events directly, but forgot the `focusin` and `focusout` events.. 

I'll release a "fixed fixed" version soon-ish... Sorry for the mistake, for the time being please continue to use the workaround

**Comment by thalaz** [comment]
Yes sure @KingSora, no problem at all 🙂

Please let me know when a fixed version is deployed, and I'll double-check it 🙂

**Comment by KingSora** [comment]
@thalaz I've published [overlayscrollbars v2.6.0](https://www.npmjs.com/package/overlayscrollbars/v/2.6.0) which should now hopefully have the correct fix :)
