### ISSUE TITLE
request

### ISSUE THREAD

**Issue by zcTob** [KingSora/OverlayScrollbars#614]
请教下：
按住滚动条拖动时，鼠标hover在按钮上，按钮的hover状态没有触发是怎么做到的。 其他自定义滚动条库，都有这个bug。

**Comment by KingSora** [comment]
Good day @zcTob :)

Please try to describe your request in english.

**Comment by KingSora** [comment]
@zcTob I'm sorry but I'll close the issue for now. Please try to describe your request in english and I'll re-open the issue again.
