### ISSUE TITLE
Problems with sidebar

### ISSUE THREAD

**Issue by hfel** [KingSora/OverlayScrollbars#62]
Hi!

I am trying to add the scrollbar to a sidebar element, however it seems to split the website vertically into two halves: one with the sidebar and the other with the content. The relevant CSS is [here](https://github.com/minicomp/ed/blob/master/_sass/_ed.scss#L326). I dabble in web development as a hobby, so I'm not particularly knowledgeable and I have no experience with JavaScript, but I wonder if it might have something to do with the display property.

Thanks!

**Comment by KingSora** [comment]
Good day!

In which order are you loading your CSS files? - Please load first the plugin CSS file and after that all the other CSS files you want to use.

If this doesn't help or you are already doing it like that, please try to make a small demo on [jsfiddle](https://jsfiddle.net/) or upload a small demo project somewhere. Its really hard for me to identify the issue without any html (the CSS looks alright to me).

I'm sure its just a tiny mistake you are making, and it can be resolved easily.

**Comment by hfel** [comment]
You are correct, loading the plugin's CSS before the other CSS files solved it. Thank you very much for helping out an amateur and have a nice day!

**Comment by KingSora** [comment]
No problem, I'm glad everything is working now!
