### ISSUE TITLE
Native scrollbar is visible on iOS

### ISSUE THREAD

**Issue by dannybeckett** [KingSora/OverlayScrollbars#622]
**Describe the bug**
On a physical iPhone, iOS's native scrollbar is visible when scrolling the page. This bug also affects the [demo page](https://kingsora.github.io/OverlayScrollbars/example/overlayscrollbars).

**To Reproduce**
1. Launch Safari
2. Open the [demo page](https://kingsora.github.io/OverlayScrollbars/example/overlayscrollbars)
3. Observe that the scrollbars look correct - the native scrollbars are not visible:
![IMG_5116](https://github.com/KingSora/OverlayScrollbars/assets/3579714/50aa8f52-d62c-4042-ade8-6c3a46be3981)
4. Tap and drag somewhere on the page to natively scroll
5. Observe that the native scrollbars now overlap the OverlayScrollbars:
![IMG_5117](https://github.com/KingSora/OverlayScrollbars/assets/3579714/686d4607-2d9d-4e8d-b87d-9952d343ade6)

**Expected behavior**
Native scrollbars should not be visible

**Examples**
[Demo page](https://kingsora.github.io/OverlayScrollbars/example/overlayscrollbars)

**Environment**
- Physical iPhone 15
- iOS v17.3.1
- Safari

**Additional context**
- This bug does **not** affect the inner square box with the logo in it, when you scroll that
- I am also observing native scrollbars overlapping the OverlayScrollbars on a website of ours

**Related**
https://github.com/KingSora/OverlayScrollbars/issues/545

**Comment by KingSora** [comment]
Good day @dannybeckett 

Unfortunately this is a limitation of Safari. Technically the scrollbars are hidden (thats why the scrollbars are not visible in the inner square box), but the "viewport indicators" which also are shown when you just zoom in into the page are not. This also affected chrome and other browsers on mobile until they supported the `scrollbar-width` css property. Safari doesn't support the css property even in version 17. (https://caniuse.com/?search=scrollbar-width)

The workaround here is to cancel the initialization of the plugin in this case:
```js
OverlayScrollbars({
  target: document.body,
  cancel: {
    nativeScrollbarsOverlaid: true,
  },  
});
```

**Comment by dannybeckett** [comment]
Ah I see @KingSora

If I cancel the init then the custom scrollbars won't show, right?

In which case it's probably still preferable to keep it showing both native scrollbars + custom scrollbars, since Safari hides the native scrollbar except on scroll (thus making it unclear that there is more content beneath).

**Comment by dannybeckett** [comment]
Thanks for your help @KingSora - I'll leave it alone; hopefully Apple might eventually add support - one can hope xD

**Comment by KingSora** [comment]
We all hope :D

**Comment by dannybeckett** [comment]
Just to state the obvious, wrapping the contents of `<body>` in a container `<div>` is another workaround:

``` lang-html
<html><body><div class="body-content data-overlayscrollbars-initialize">Your actual content here</div></body>
```

For me I also needed the following styles:

``` lang-css
div.body-content {
        height: 100%;
        left: 0;
        position: absolute;
        top: 0;
        width: 100%;
}
```

Now the `<body>` has a scrollbar without iOS' native scrollbars overlapping :)

**Comment by dannybeckett** [comment]
> @dannybeckett THanks for this suggestion!
> 
> Thats also a valid workaround but has other drawbacks to be aware of:
> 
> * on mobile this will prevent the url bar to hide / show depending on your scrolling
> * on mobile pull to refresh will not work anymore
> * will alter the functionality of `window.scrollTo` and other scroll apis related to the `window` global

I have just tested on mobile and thankfully I'm not observing any of these 3 issues on our site.

I'm very happy to have found a nice workaround, thank you so much for creating such an awesome piece of kit!

**Comment by dannybeckett** [comment]
So after posting that, I've spent several hours trying to fix a "gotcha" that I've found when using my workaround above. On Chrome for Windows the arrow up/down keyboard keys do not work unless you click somewhere in the middle of the page first. On an iPad with an [Apple Magic Keyboard](https://www.apple.com/uk/shop/product/MJQJ3B/A/magic-keyboard-for-ipad-pro-11-inch-4th-generation-and-ipad-air-5th-generation-british-english-white) attached, no amount of clicking the middle of the page will enable the up/down arrow keyboard keys.

The workaround for this is to add `tabindex="-1"` to a div **within** `.body-content` but **not** on `.body-content` itself (`tabindex` denotes that this element is focusable, and `-1` denotes that it can only be focused on programmatically and not by the user). You then need to focus this inner `<div>` on page load:

``` lang-js
window.addEventListener('load', function() { document.getElementsByClassName('some-inner-div')[0].focus(); });
```

**Comment by KingSora** [comment]
@dannybeckett I didn't mention it before because I thought you didn't have any issues, but OverlayScrollbars is able to do the initialization you did out of the box (with all the focus management etc.):

```js
OverlayScrollbars({
  target: document.body,
  elements: {
    viewport: false,
  },
  cancel: {
    body: false,
  },
});
```

**Comment by dannybeckett** [comment]
@KingSora Sorry to bother you again! I tried your code above (after undoing the things I did before, I.E. adding the container `<div>`, JS focus + CSS).

The custom scrollbars are visible, and the iOS-native scrollbars no longer overlap, but unfortunately it isn't focusing.

On Chrome for Windows: I have to click somewhere in the middle of the page to get the arrow up/down keyboard keys to work.

On Safari for iPad with a physical keyboard attached: interestingly I don't have to tap the screen, but I can only press the arrow down key once. After that you are unable to press either the up or down arrow keys.

Any ideas please? Sorry for being a pain!

Thanks a lot!

**Comment by KingSora** [comment]
@dannybeckett OverlayScrollbars will automatically focus its viewport element, not your custom element... can you please post an small example on StackBlitz with your setup? I then can take a look what could be done

**Comment by KingSora** [comment]
@dannybeckett I've just published `v2.7.1` which includes fixes to your issue... please try it out and give feedback :)

**Comment by dannybeckett** [comment]
Wow @KingSora I am incredibly impressed with the speed of your response - thank you for being so dedicated!

Needless to say that 2.7.1 is perfect in every way, it has truly hit the nail right on the head! No more of my yucky workarounds! 🥳😆

Seriously, great job! Thank you so much once again!!

All the best

**Comment by KingSora** [comment]
@dannybeckett glad I could help you :)
