### ISSUE TITLE
Can you provide the. scss format for the style

### ISSUE THREAD

**Issue by ajiho** [KingSora/OverlayScrollbars#623]
**As the title suggests, thank you again for this great library**

**Comment by KingSora** [comment]
Good day @ajiho :)

What benefit would that bring to you? - I believe I'm not really using any scss feature which could be useful for consumers

**Comment by KingSora** [comment]
@ajiho I see.. if you just want to import the styles, the file doesn't have to be a scss or sass file - css should work as well. (Found this in the [sass docs](https://sass-lang.com/documentation/at-rules/import/#finding-the-file)

**Comment by KingSora** [comment]
@ajiho did my previous reply solve the issue or do you still need the `.scss` file? If yes, please explain why :)

**Comment by ajiho** [comment]
> @ajiho did my previous reply solve the issue or do you still need the `.scss` file? If yes, please explain why :)

I only started reviewing this issue today. Yes, your answer has already solved the problem. Sass can directly process. css files. Lastly, your library is really great
