### ISSUE TITLE
Error caused when routing

### ISSUE THREAD

**Issue by LynithDev** [KingSora/OverlayScrollbars#627]
**Describe the bug**
Whenever I switch pages using [solid-router](https://github.com/solidjs/solid-router), I start getting errors with OverlayScrollbars, 

```js
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'S.top')
	(anonymous function) (overlayscrollbars.mjs:2367)
```

The source file and location it occurs at is in `structureSetup.elements.ts:276`

**To Reproduce**

1. Switch to a different page
2. Switch to the previous page
3. Scrollbar doesn't show up and throws an error

**Expected behavior**
No errors get thrown and the scrollbar displays and handles user interaction properly.

**Environment**

- Used Operating System(s): Fedora Linux 39 x86_64
- Used Browser(s) (with version): WebKitGTK (webkit2gtk4.1-devel.x86_64 2.44.0-2.fc39) in a Tauri App

**Comment by KingSora** [comment]
Good day @LynithDev :)

I've found the issue - [document.defaultView](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView) can be `null` and I'm not accounting for this. I'm not sure when this happens and solid is actually the first environment where I can observe this.

I'll publish a fix soon - sorry for the inconvenience

**Comment by LynithDev** [comment]
No worries, the library is fairly simple to use and *mostly* just works. I appreciate the work :+1:

**Comment by KingSora** [comment]
@LynithDev I've published OverlayScrollbars `v2.7.2` which should fix your issue :)

**Comment by LynithDev** [comment]
I'll try it later today, thanks :+1:

**Comment by LynithDev** [comment]
Can confirm that it has fixed the issue.
