### ISSUE TITLE
How to hide scrollbars on print?

### ISSUE THREAD

**Issue by dannybeckett** [KingSora/OverlayScrollbars#628]
**Describe the bug**
I am trying to hide the scrollbars from my print stylesheet like so:

    @media print {
        div.os-scrollbar,
        ::-webkit-scrollbar
        {
            display: none !important;
        }
    }

**To Reproduce**
This works the first time you hit Print, but the 2nd time you hit Print it shows the scrollbar slightly, and by the 3rd time you hit Print the scrollbar is fully showing again.

**Expected behavior**
Scrollbar should not show when the page is printed, no matter how many times you press Print

**Environment**
- Windows 11 22H2 - build 22621.3155
- Google Chrome - 124.0.6367.60 (Official Build) (64-bit) (cohort: M124 Rollout) 

**Additional context**
- I am using the scrollbar on `<body>` as detailed in #622
- This could be an issue with Chrome, but if you have any tips I'd really appreciate it please!

Thanks a lot! 😃

**Comment by KingSora** [comment]
Good day @dannybeckett 

I've published `v2.7.3` which should hide the scrollbars when printing. I hope it works :)

**Comment by dannybeckett** [comment]
@KingSora Beautiful work!! I am once again very impressed - thank you so much! 🎉

**Comment by KingSora** [comment]
Glad I could help! :)
