### ISSUE TITLE
Unexpected scrolling when scrolling container is focused

### ISSUE THREAD

**Issue by luin** [KingSora/OverlayScrollbars#629]
**Describe the bug**

If I have a element that is:
1. Out of the viewport
2. Focused

The page would scroll unexpectedly if I make the element an instance of OverlayScrollbars.

**To Reproduce**

1. Go to https://overlayscrollers-abortive-pocket.surge.sh/ (Inspect the source code for how it's implemented)
2. Wait for 2 seconds

**Expected behavior**

The page should not be scrolled. The editor is focused with `preventScroll: true`. It's unexpected that creating a `OverlayScrollbars` would scroll the page.

**Environment**

- Used Operating System(s): macOS
- Used Browser(s) (with version): Chrome 123

**Additional context**

I believe to fix the issue, we should pass `preventScroll: true` in `focusElm` because we only want to focus instead of scrolling.

**Comment by KingSora** [comment]
Good day @luin :)

Nice catch! I've published `v2.7.3` which uses `{ preventScroll: true }` when focusing the viewport.

**Comment by luin** [comment]
@KingSora Thanks a lot! That's the fastest response and fix I've ever experienced on GitHub in the past 10 years 😄
