### ISSUE TITLE
Using gsap triggers persistent updates to the data-overlayscrollbars-viewport attribute on the HTML element

### ISSUE THREAD

**Issue by PolinaTcaciuc** [KingSora/OverlayScrollbars#637]
**Describe the bug**
Using gsap triggers persistent updates to the data-overlayscrollbars-viewport attribute on the HTML element, potentially impacting performance.

**To Reproduce**

1. Open the code in a browser window.
2. Launch developer tools.
3. Observe the data-overlayscrollbars-viewport attribute on the HTML element undergoing continuous updates.

**Expected behavior**
The data-overlayscrollbars-viewport attribute on the HTML element should not update incessantly.

**Examples**
Please create a small example of the bug.
https://codesandbox.io/p/devbox/overlayscrollbars-gsap-q6h336?file=%2Fapp.vue%3A43%2C22

**Environment**

- Used Operating System(s): Windows 11
- Used Browser(s) (with version): Google Chrome 125.0.6422.61 64bit

**Additional context**
None

**Comment by KingSora** [comment]
Good day @PolinaTcaciuc :)

Per default `OverlayScrollbars` updates as soon as a child changes in a certain way. If you want to optimize this behavior you can use the `update.ignoreMutation` option for this.

To optimize your example I've used the option like this:
```js
update: {
  ignoreMutation(mutation) {
    const { target } = mutation;
    if (target instanceof HTMLElement) {
      if (target.classList.contains("marquee-list__item")) {
        return true;
      }
    }
  },
}
```
You can find a demo here: https://codesandbox.io/p/devbox/overlayscrollbars-gsap-forked-9ql7w4?file=%2Fapp.vue%3A16%2C7

For your usecase you can obviously use any condition to optimize animations, you could e.g. ignore every update to css properties like `transform` to make something more generic.

**Comment by KingSora** [comment]
Glad I could help :)
