### ISSUE TITLE
Scroll to a specific position with a single click and no need to hold down the shift key

### ISSUE THREAD

**Issue by ZSThai** [KingSora/OverlayScrollbars#645]
Hello,
I see in issue #50,  you answered about moving to any location immediately through pressing the shift key and clicking the mouse. But is there a way to do the same thing without pressing the shift key?
Can you give me ideas to solve this problem?

**Comment by KingSora** [comment]
@ZSThai @AlanFnz I've published overlayscrollbars `v2.10.0` which now supports the value `'instant'` for the `scrollbar.clickScroll` option which makes your desired behavior possible without much custom code.
