### ISSUE TITLE
ClickScrollPlugin seems not support trackpad tap

### ISSUE THREAD

**Issue by 1isten** [KingSora/OverlayScrollbars#650]
**Describe the bug**
clickScroll not working when using macbook trackpad

**To Reproduce**

1. registered plugin `OverlayScrollbars.plugin(ClickScrollPlugin)`
2. enabled clickScroll config `{ scrollbars: clickScroll: true }`
3. click (press down) the macbook trackpad, scroll working fine
4. tap (do not press down) the macbook trackpad, scroll not happening

**Expected behavior**
tap on trackpad should behaved like press (click)

**Environment**

- Used Operating System(s): macOS 14.0
- Used Browser(s) (with version): both Chrome and Safari

**Comment by KingSora** [comment]
Good day @1isten :)

I'm not a mac user so please help me to understand the issue. What is the actual difference between a tap and click? Currently the click scroll is written in a way where it is executed when the user clicks (and holds) the primary (left) mouse button on the scrollbar track.

Is a trackpad tap the same as a "left button mouse click"?

**Comment by 1isten** [comment]
Hi @KingSora , for MacBook trackpad we have two ways to trigger "click":

1. The default way: put the finger on the trackpad and press down hardly, which means you can feel the touchpad being pressed and hear a sound, just like a left button mouse click.
2. Tap (touch) the trackpad lightly without press down, just like a tap on mobile phone screen.
<img width="827" alt="Screenshot 2024-06-16 at 11 40 11 PM" src="https://github.com/KingSora/OverlayScrollbars/assets/11518941/867c7c32-eb34-4075-b344-ffd44736f091">

**Comment by 1isten** [comment]
> Edit: On my windows laptop tap as well as clicking the trackpad is working fine

I suppose the macbook trackpad tap is the same as windows laptop tap, but the `clickScroll` just not working

**Comment by KingSora** [comment]
@1isten I'll see if I can get my hands on a mac computer in the next days to investigate this issue a bit more

**Comment by KingSora** [comment]
@1isten I've deployed a possibly fixed version to https://kingsora.github.io/OverlayScrollbars/ please try to click-scroll the **body scrollbar** with your trackpad tap.

**Comment by 1isten** [comment]
@KingSora Thanks for your quick reply! I tried on an old MacBook (2015) with macOS 11, it works great now!

Will try on my new MacBook (which I encountered the issues originally) tomorrow, should be no problem ;D  Thank you

**Comment by 1isten** [comment]
@KingSora I just tried on my new MacBook (m2 chip with macOS 14) and it works too, thank you!

May I know when will you release new version with this fix?

**Comment by KingSora** [comment]
@1isten I've just released `v2.9.0` which includes the fix :)
