### ISSUE TITLE
jQuery.fn.hover() is deprecated

### ISSUE THREAD

**Issue by guestisp** [KingSora/OverlayScrollbars#66]
jQuery-version of OverlayScrollbars is using `hover` method that is deprecated in jQuery.
https://github.com/KingSora/OverlayScrollbars/blob/45fe5b96a35af0bf28f2ee2cc377fedf4c9b2d41/js/jquery.overlayScrollbars.js#L3316

This should be replaced with
```
}).on('mouseenter', function() { //make sure both scrollbars will stay visible if one scrollbar is hovered if autoHide is "scroll".
   if (_scrollbarsAutoHideScroll || _scrollbarsAutoHideMove) {
       _scrollbarsAutoHideFlagScrollAndHovered = true;
       refreshScrollbarsAutoHide(true);
   }
}).on('mouseleave', function() {
   if (_scrollbarsAutoHideScroll || _scrollbarsAutoHideMove) {
       _scrollbarsAutoHideFlagScrollAndHovered = false;
       refreshScrollbarsAutoHide(false);
   }
});
```

**Comment by KingSora** [comment]
I didn't know that the `hover` method is deprecated. I also can't find it in the official [documentation](https://api.jquery.com/category/deprecated/). 
Am I overlooking something?

**Comment by guestisp** [comment]
I think they are still undocumented, but jquery-migrate is already triggering a warning
https://github.com/jquery/api.jquery.com/issues/972

**Comment by KingSora** [comment]
You are right, I've found [this](https://github.com/jquery/jquery/issues/3214#issuecomment-398663964) regarding the documentation. Thanks for this issue! :)

**Comment by guestisp** [comment]
Could you please release a new version with this fix ?

**Comment by KingSora** [comment]
Yes, the new version is coming next week with a few other fixes.

**Comment by KingSora** [comment]
@guestisp I apologize, but I couldn't manage it to release it earlier. Anyway, the new version is out: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.5.3
