### ISSUE TITLE
Can see two scrollbars in ios both native and custom

### ISSUE THREAD

**Issue by Eswar-Oruganti** [KingSora/OverlayScrollbars#666]
I am experiencing an issue on iOS where both native and custom scrollbars are visible when using OverlayScrollbars in my Next.js project. I have attempted to resolve this issue by following similar issues , but it did not fix it.

![image](https://github.com/user-attachments/assets/8eea5e15-7919-4d80-a1c6-d20dd1e93f97)

**Comment by KingSora** [comment]
Good day @Eswar-Oruganti :)

Are you able to provide a minimal example on StackBlitz or CodeSandbox? Then I can take a closer look on what the problem could be.

**Comment by KingSora** [comment]
@Eswar-Oruganti Also to me it looks like you're initializing the Plugin twice. Once with the `useEffect` hook and the second time with the `OverlayScrollbarsComponent`. Please try to use only one or the other for the same element.

**Comment by KingSora** [comment]
@Eswar-Oruganti I've created for you an example of how I would do it: https://stackblitz.com/edit/stackblitz-starters-fahjja?description=The%20React%20framework%20for%20production&file=app%2Flayout.tsx,components%2FOverlayScrollbarsBodyComponent.tsx,components%2FOverlayScrollbarsBodyHook.tsx&title=Next.js%20Starter

There are two components in the example:
- `OverlayScrollbarsBodyComponent` thats how you can use the `OverlayScrollbarsComponent` on the body element
- `OverlayScrollbarsBodyHook` thats how you can use the `useOverlayScrollbars` hook to initialize `overlayscrollbars` with additional control (e.g. being able to cancel the initialization etc.)

**Comment by Eswar-Oruganti** [comment]
@KingSora Thanks a lot, that solved the problem. I couldn't find the cancel option in the component.

Regarding your point about using the same instance, I have a couple of modals. When they are open, I would like to disable body scroll. Would I need to use the same instance for this as well?

**Comment by KingSora** [comment]
@Eswar-Oruganti Its actually not really possible to initialize `OverlayScrollbars` twice to a single element. The second initialization will effectively just change the options of the previously created instance. I just phrased it that way to simplify the problem.

You can get the overlayscrollbars instance of any element like this:

```js
const osInstance = OverlayScrollbars(myElement);
```

This will return `undefined` if the given element has no overlayscrollbars instance or the instance if the element has one.
So in case of disabling the body scroll you can do something like this:

```js
const onModalOpen = () => {
  const osInstance = OverlayScrollbars(document.body);
  
  if (!osInstance) {
    return;
  }
  
  osInstance.options({ overflow: { x: 'hidden', y: 'hidden' }  });
};
const onModalClosed = () => {
  const osInstance = OverlayScrollbars(document.body);
  
  if (!osInstance) {
    return;
  }
    
  osInstance.options({ overflow: { x: 'scroll', y: 'scroll' }  });
}
```

**Comment by Eswar-Oruganti** [comment]
const onModalOpen = () => {
  const osInstance = OverlayScrollbars(document.body);
  
  if (!osInstance) {
    return;
  }
  
  osInstance.options({ overflow: { x: 'hidden', y: 'hidden' }  });
};


**Will this work in ios browsers with the nativescrollbarsoverlaid option set to true**

  initialize({
        target: body,
        cancel: {
          nativeScrollbarsOverlaid: true,
        },
      });

**Comment by Eswar-Oruganti** [comment]
@KingSora 

   initialize({
        target: body,
        cancel: {
          nativeScrollbarsOverlaid: true,
        },
      });
      
      
     **With the nativeScrollbarOverlaid option set to true**
     
     body scroll lock you suggested above is not working in ios , is there any workaround

**Comment by KingSora** [comment]
@Eswar-Oruganti that option is not for the body scroll lock, its for not initializing overlayscrollbars in case the native scrollbars are overlaid already.

If overlayscrollbars is not initialized you have to disable the body scroll by yourself with the style `overflow: hidden`.

**Comment by PedroGuo** [comment]
Using the online demo address you provided, two scrollbars will also appear on ios 16.1

online demo :   https://kingsora.github.io/OverlayScrollbars/example/overlayscrollbars/

**Comment by KingSora** [comment]
@PedroGuo this is an limitaion of iOS at the moment, because the scrollbar styling rules are not applying to the root scroller element.. In the past Chrome mobile had the same limitation as well, but since the support of `scrollbar-width` (https://caniuse.com/?search=scrollbar-width) the limitation is no longer present.

To work around this issue you have multiple possibilities:
1. Initialize OverlayScrollbars on the body with `{ cancel: { nativeScrollbarsOverlaid: true } }` to cancel the initialization if needed
2. Initialize OverlayScrollbars on the body with the option `{ showNativeOverlaidScrollbars: true }` to only show the native scrollbars but keep the initialized instance
3. Check for the support of the `scrollbar-width` property before initializing OverlayScrollbars to the body

I'm not using any of those in the example because I want to keep it simple. On the [documentation page](https://kingsora.github.io/OverlayScrollbars/) I'm using OverlayScrollbars on the body element but cancel the initialization when I would run into this limitation.
