### ISSUE TITLE
a bug 

### ISSUE THREAD

**Issue by planework** [KingSora/OverlayScrollbars#673]
<div id="app">
        <div class="d-flex flex-column bg-dark vh-100 p-3">
            <div class="bg-warning p-3 text-center text-white">

            </div>
            <div class="row g-0 vh-100 bg-white">
                <div class="row g-0 ">
                    <div class="col-3 h-100 bg-danger">
                        <div class="h-100 overflow-auto" data-overlay>
                            <div v-for="item in 100">{{item}}</div>
                        </div>
                    </div>
                    <div class="col-9 bg-danger">
                        <div class="h-100 overflow-auto" data-overlay>
                            <div v-for="item in 100">{{item}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/overlayscrollbars@1.13.1/css/OverlayScrollbars.min.css">
    <script src="https://unpkg.com/overlayscrollbars@1.13.1/js/OverlayScrollbars.min.js"></script>
    const App = Vue.createApp({
        data() {
            return {
                range: {
                    hostname1: '0.0.0.0',
                    hostname2: '255.255.255.255',
                },
                devices: [

                ],
                logs: [
  
                ],
                command: '',
            };
        },

        mounted() {
           setTimeout(() =>{
            OverlayScrollbars(document.querySelectorAll('[data-overlay]'), {
                scrollbars: {
                    autohide: 'never',
                },
            });
           },0)
        },
        methods: {
            toggleAll() {
                const allChecked = this.devices.every(device => device.checked);
                this.devices.forEach(device => device.checked = !allChecked);
            },
        }
    });

    App.mount('#app');

**Comment by planework** [comment]
OverlayScrollbars(document.querySelectorAll('[data-overlay]'), {
                    scrollbars: {
                        autohide: 'never',
                    },
                });

**Comment by planework** [comment]
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js"></script>
    
    <link rel="stylesheet" href="https://unpkg.com/overlayscrollbars@1.13.1/css/OverlayScrollbars.min.css">
    <script src="https://unpkg.com/overlayscrollbars@1.13.1/js/OverlayScrollbars.min.js"></script>

**Comment by planework** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IP Scanner</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js"></script>

</head>

<body>
    <div id="app">
        <div class="d-flex flex-column bg-dark vh-100 p-3">
            <div class="bg-warning p-3 text-center text-white">

            </div>
            <div class="row g-0 vh-100 bg-white">
                <div class="row g-0 ">
                    <div class="col-3 h-100 bg-danger">
                        <div class="h-100 overflow-auto" data-overlay>
                            <div v-for="item in 100">{{item}}</div>
                        </div>
                    </div>
                    <div class="col-9 bg-danger">
                        <div class="h-100 overflow-auto" data-overlay>
                            <div v-for="item in 100">{{item}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <link rel="stylesheet" href="https://unpkg.com/overlayscrollbars@1.13.1/css/OverlayScrollbars.min.css">
    <script src="https://unpkg.com/overlayscrollbars@1.13.1/js/OverlayScrollbars.min.js"></script>
    <script type="text/javascript">
        const App = Vue.createApp({
            data() {
                return {
                    range: {
                        hostname1: '0.0.0.0',
                        hostname2: '255.255.255.255',
                    },
                    devices: [

                    ],
                    logs: [
      
                    ],
                    command: '',
                };
            },

            mounted() {
               setTimeout(() =>{
                OverlayScrollbars(document.querySelectorAll('[data-overlay]'), {
                    scrollbars: {
                        autohide: 'never',
                    },
                });
               },0)
            },
            methods: {
                toggleAll() {
                    const allChecked = this.devices.every(device => device.checked);
                    this.devices.forEach(device => device.checked = !allChecked);
                },
            }
        });

        App.mount('#app');
    </script>
</body>

</html>

**Comment by planework** [comment]
<script type="text/javascript">
    const App = Vue.createApp({
        data() {
            return {
                range: {
                    hostname1: '0.0.0.0',
                    hostname2: '255.255.255.255',
                },
                devices: [

                ],
                logs: [
  
                ],
                command: '',
            };
        },

        mounted() {
           setTimeout(() =>{
            OverlayScrollbars(document.querySelectorAll('[data-overlay]'), {
                scrollbars: {
                    autohide: 'never',
                },
            });
           },0)
        },
        methods: {
            toggleAll() {
                const allChecked = this.devices.every(device => device.checked);
                this.devices.forEach(device => device.checked = !allChecked);
            },
        }
    });

    App.mount('#app');
</script>

**Comment by KingSora** [comment]
@planework Good day :) 

Thanks for the code, but I don't really know how to use that.. Please create a working minimal example on `jsfiddle`, `stackblitz` or `codesandbox`.
