### ISSUE TITLE
Document RTL - scrollbar on "html" element still at the right

### ISSUE THREAD

**Issue by abyasoft** [KingSora/OverlayScrollbars#679]
**Description of the bug**
Document RTL - scrollbar on "html" element still at the right.
On the other hand on the other elements the scrollbar is well positioned on the left

**Test Environement**
Firefox 130.0.1 (64 bits)
Windows 11 Pro 64 bits

**Comment by KingSora** [comment]
Good day @abyasoft :)

This was implemented because of https://github.com/KingSora/OverlayScrollbars/issues/226 which describes this behavior also the "correct" one, because the native scrollbars behave in the same way.

**Comment by KingSora** [comment]
@abyasoft any thoughts on this, or can I consider this issue as resolved?

**Comment by abyasoft** [comment]
I ended up giving up on the idea of ​​custom scrollbars since my app is now mobile oriented loaded in a webview, on android or IOS the scrollbars are magnificent. Thank you for the work you do and good luck.
Yes, you can consider this issue as resolved
