### ISSUE TITLE
Scroll bars do not appear on wacom tablet

### ISSUE THREAD

**Issue by gurievvlad** [KingSora/OverlayScrollbars#690]
**Describe the bug**
I'm using the library with `autoHide: 'leave'`. When I hover my mouse over the content area, scroll bars appear. However, if I move the cursor with the wacom tablet pen, the scrollbars don't appear. It's worth noting that I'm aware of the pointers parameter, but adding/modifying/removing it doesn't solve the problem.

**To Reproduce**

1. Create any template with `autoHide: 'leave'`
2. Place the mouse pointer over the scroll area using the tablet pen
3. Scrollbars will not be displayed

**Expected behavior**
Scrollbars are expected to be displayed

**Example**
https://stackblitz.com/edit/overlayscrollbars-3gjxhu?file=src%2Factions.ts
https://github.com/user-attachments/assets/5957a021-5e32-428d-92d3-8dc3ec9209b9

**Environment**
- OverlayScrollbars version: 2.10.0
- Used Operating System: macOS
- Used Browser(s) (with version): chrome 131.0.6778.69 / firefox 132.0.2

**Comment by KingSora** [comment]
Good day @gurievvlad :)

Since I don't have a wacom tablet or any other pen-device at the moment its a bit hard for me to reliably fix the issue myself. I've tried to implement a fix here: https://stackblitz.com/edit/overlayscrollbars-f31xee please try it out and give feedback

**Comment by gurievvlad** [comment]
Yeah, it really works. Thank you so much! Can I expect a release of the fix soon?

**Comment by KingSora** [comment]
@gurievvlad I'll release the new version asap :)

**Comment by gurievvlad** [comment]
@KingSora Thank you so much, will be looking forward to the release. You've been a great help to me

**Comment by KingSora** [comment]
@gurievvlad I've release [`v2.10.1`](https://www.npmjs.com/package/overlayscrollbars/v/2.10.1) which includes the fix to your issue :)

**Comment by gurievvlad** [comment]
Thanks, the fix worked in my project
