### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'ownerDocument')

### ISSUE THREAD

**Issue by dannybeckett** [KingSora/OverlayScrollbars#695]
Hi Rene,

I've been using OverlayScrollbars successfully for a little while on two elements - `body` + a `div`. I'm now trying to apply it to multiple elements, with the class `.highlight`

I'm using this:

``` js
var scrollbars = {
	autoHide: 'never',
	clickScroll: true,
	visibility: 'visible'
};

var optionsNormal = {
	scrollbars: scrollbars
};

window.scrollbar_codeblocks = OverlayScrollbars(document.querySelectorAll('.highlight'), optionsNormal);
```

But it's throwing an error in the console:

> Uncaught TypeError: Cannot read properties of undefined (reading 'ownerDocument')

On this line of code:

![2024-12-03 00_30_22-Install Docker on Debian 12 + containers E G  Sphinx Docs — Incredible IT Docs a](https://github.com/user-attachments/assets/047275cd-95d5-4d79-a473-dbd84075abd0)

The HTML definitely has some `<div class="highlight">` in there.

I'm running the latest version - v2.10.1

Is there anything I can check please?

I'm sorry to bother you!

Thanks a lot

**Comment by KingSora** [comment]
Good day @dannybeckett :)

The problem here is that the `OverlayScrollbars` function expects only a single element as its first argument. Please try something like this:

```js
var scrollbars = {
	autoHide: 'never',
	clickScroll: true,
	visibility: 'visible'
};

var optionsNormal = {
	scrollbars: scrollbars
};

window.scrollbar_codeblocks = Array.from(document.querySelectorAll('.highlight')).map((element) => {
    return OverlayScrollbars(element, optionsNormal);
});
```

Now `window.scrollbar_codeblocks` is an array of `OverlayScrollbars` instances.

**Comment by KingSora** [comment]
The documentation link you posted is only for `v1` of the library.. The docs for `v2` can be found here https://kingsora.github.io/OverlayScrollbars where I'm mentioning this behavior but don't point it out specifically..

I'll improve the section, thanks for the feedback! :)
