### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by asparkam** [KingSora/OverlayScrollbars#7]
I try to use version without jQuery but it still wants jQuery,
![image](https://user-images.githubusercontent.com/30487905/35274712-b6411dbe-006f-11e8-9831-623a2bc29114.png)

**Comment by KingSora** [comment]
Thank you!
It should be fixed now: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.2.2

**Comment by jsieler** [comment]
You should probably add notice that this update only affect non-jQuery version.

**Comment by KingSora** [comment]
@jsieler Alright, I've updated the release description.

**Comment by asparkam** [comment]
@KingSora when I try to use non min version without jQuery, I get this error: 
![image](https://user-images.githubusercontent.com/30487905/35340127-e958f376-0154-11e8-906a-ca4ff9fb9c4d.png)
Min version without jQuery - works.
