### ISSUE TITLE
Cannot read property 'PI' of undefined

### ISSUE THREAD

**Issue by poldixd** [KingSora/OverlayScrollbars#70]
Since 1.5.3 I'm getting these error, when I use OverlayScrollbars with [Nuxt.js](https://nuxtjs.org/). Nuxt.js runs on a NodeJS server on my Windows 10 machine with NodeJS 11.1.0.

`Cannot read property 'PI' of undefined`

<img width="1065" alt="nuxterror" src="https://user-images.githubusercontent.com/695449/48281807-09f36080-e458-11e8-8252-a594bac2e2c5.png">

**Comment by KingSora** [comment]
Alritght, thanks for this report, I'll fix this as fast as possible!

**Comment by KingSora** [comment]
Please try out [this](https://raw.githubusercontent.com/KingSora/KingSora.github.io/master/_framework/js/OverlayScrollbars.js) version of the plugin, and tell me if the bug is fixed. Unfortunately I'm currently not able to test it myself with your enviroment.

Thank you in advance!

**Comment by poldixd** [comment]
Yes! The bug is fixed with these file. There are no more errors. Thank you very much!

**Comment by KingSora** [comment]
Alright, the fix is out in [v1.6.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.6.0)!
