### ISSUE TITLE
OverlayScrollbars.min is not correct and doesn't validate

### ISSUE THREAD

**Issue by ScrappyCocco** [KingSora/OverlayScrollbars#73]
` .os-resize-observer-host - error: CSS: "border": Too many values or values`

In OverlayScrollbars.css there's
`.os-resize-observer-host` that has `border: inherit;`
In OverlayScrollbars.min.css that become
`border:solid inherit;`
That's not correct and make the css file not valid.
Please correct your .min.css file to make it validate from [the css validator](https://jigsaw.w3.org/css-validator/)

Thank you ^^

**Comment by KingSora** [comment]
Thanks a lot - I would've never found this bug.
Of course I'll fix it as fast as possible.

**Comment by KingSora** [comment]
Alright, its fixed in [v1.6.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.6.0).
Thanks again!
