### ISSUE TITLE
How to get textarea to start with a single line when using the dynamic option

### ISSUE THREAD

**Issue by hyeony** [KingSora/OverlayScrollbars#77]
![textarea](https://user-images.githubusercontent.com/21697133/49635057-de0cd000-fa41-11e8-9863-714e7f6f42d0.jpg)

With the dynamic option, textarea start with a double line.
The textarea design that I have to work on must be one line.😭
Why is the height being measured at twice the value? ( not 24px - > 48px... )
How to get textarea to start with a single line when using the dynamic option .. plz....

**Comment by hyeony** [comment]
![height](https://user-images.githubusercontent.com/21697133/49634924-722a6780-fa41-11e8-9513-28309ebe6bcb.jpg)
Tell me how to set the height and max-height.
I want to start from 24px..

**Comment by KingSora** [comment]
Good day!

A `textarea` has two attributes which decides which min-height and min-width the textarea has if you haven't specified anything else, these two attributes are called `cols` and `rows`. In your case only the `rows` attribute is interesting. Here is the [W3C documentation](https://www.w3schools.com/tags/att_textarea_rows.asp) which says:

> Specifies the height of the text area (in lines). Default value is 2

So the only thing you have to do is to set the correct number in this attribute in your textarea element:
```html
<textarea rows="1"></textarea>
```
And then the textarea min-height will be exact one line (if you use the dynamic option).
I hope this makes the functionality a bit more clear.

**Comment by hyeony** [comment]
got it! appreciate it ! u saved my life❗❗❗

**Comment by KingSora** [comment]
Glad I could help you!

**Comment by AleshaOleg** [comment]
Is it possible to somehow do an auto-expandable text-area with a custom scrollbar? Are any examples of this?

Something like that: https://medium.com/@lucasalgus/creating-a-custom-auto-resize-textarea-component-for-your-react-web-application-6959c0ad68bc

**Comment by KingSora** [comment]
@AleshaOleg do you mean something like that: https://kingsora.github.io/OverlayScrollbars/#!demos/textarea (you have to click on the "Full Dynamic Height" button first)

**Comment by AleshaOleg** [comment]
@KingSora yes, exactly. How I can implement this with React?

**Comment by AleshaOleg** [comment]
@KingSora sorry, might be that example not too good. Let's say I have `textarea` with `rows` value 5. And after text takes I need to show a scrollbar. Or at least I can do it manually by multiplying rows to my row height, as I have `rows` as React property and not for `textarea`. Is it possible?

**Comment by KingSora** [comment]
@AleshaOleg I'm too lazy to create an example, but I'm pretty sure its possbile
