### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by asparkam** [KingSora/OverlayScrollbars#8]
When I try to use it in my React app, I get this error:
![image](https://user-images.githubusercontent.com/30487905/35341204-aada3ddc-0157-11e8-8b0e-e0808c4ff590.png)

I made 
`import {OverlayScrollbars} from 'overlayscrollbars/js/OverlayScrollbars';`
and after mounting all page try this: `OverlayScrollbars(document.querySelectorAll('body'), { });`
body element is available in this moment and logging into console:
![image](https://user-images.githubusercontent.com/30487905/35341490-6662a7c4-0158-11e8-8104-0ade7660658e.png)

**Comment by KingSora** [comment]
After this error occurs, can you initialize a instance of the plugin manually via the console, or will this error show up again?

My knowledge with react isn't that good, so I can only guess the error.
I'll investigate on this and I'll send tomorrow possible fixes. Please test them and give me feedback if these fixes are working properly or not.

I am sorry, that your experience with my plugin wasn't as good as it should be.

**Comment by asparkam** [comment]
Similar problem in another plugins:
https://github.com/wallabyjs/public/issues/808
https://github.com/akiran/react-highlight/issues/39

I think it is context problem and when I used in your code `global.document` instead of `window,document` then error was missing.
May be this plugin will be useful: https://www.npmjs.com/package/global

**Comment by KingSora** [comment]
Please try out this fix, maybe it will work: https://raw.githubusercontent.com/KingSora/KingSora.github.io/master/%238fix.js

**Comment by asparkam** [comment]
This fix is working when I do import like this `import 'overlayscrollbars/js/OverlayScrollbars';`
When I try import by this way `import OverlayScrollbars from 'overlayscrollbars/js/OverlayScrollbars';` I get empty importing object: 
![image](https://user-images.githubusercontent.com/30487905/35621708-ef0c2b18-06b7-11e8-8089-4e11eceee169.png)
On this way: `import {OverlayScrollbars} from 'overlayscrollbars/js/OverlayScrollbars';` I get undefined object: 
![image](https://user-images.githubusercontent.com/30487905/35621771-256f192c-06b8-11e8-9414-f1adb427b0db.png)

**Comment by KingSora** [comment]
Alright, we're getting closer... please try this:
https://raw.githubusercontent.com/KingSora/KingSora.github.io/master/%238fix.js

**Comment by asparkam** [comment]
This way is working now: `import OverlayScrollbars from 'overlayscrollbars/js/OverlayScrollbars';`. Thank you!

**Comment by KingSora** [comment]
Yes! I am glad this bug is fixed now.
I'll update the Github repo and the NPM repo later today. The version which will contain this (and some other fixes) will have the **version 1.2.3**.

Thank you for your cooperation! :)

**Comment by KingSora** [comment]
Here you go: https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.2.3
NPM is also updated: https://www.npmjs.com/package/overlayscrollbars

**Comment by oyeanuj** [comment]
@asparkam Could you share your React integration? Also using React, and wondering how well this plugin works with React?
