### ISSUE TITLE
autoHide: "scroll" let scrollbar appear on hover

### ISSUE THREAD

**Issue by AlexSHoffman** [KingSora/OverlayScrollbars#84]
Property `autoHide: "scroll"` should work for both **scroll** and **hover over scrollbar** events. 
As you can see on the gif below, it only works with the `scroll` event. When you hover over a scrollbar it doesn't show up. 

![2](https://user-images.githubusercontent.com/13764106/51640246-07db7100-1f74-11e9-9b18-e78eedad9bf6.gif)

**Comment by KingSora** [comment]
Good day!

This behavior is actually intended. Imagine if you try selecting some text and you accidentally hover over a invisible scrollbar area. Generally I think it's wrong to let you hover over something which is (in most cases) invisible, don't you agree?

There is one thing I want to let you know though, if your scrollbars shows up and you hover over them, they'll stay visible until you trigger the hide mode:
https://i.imgur.com/zMdkeH9.gif

In your case I think the options `autoHide: "move"` or `autoHide: "leave"` would more suited for your needs.

**Comment by AlexSHoffman** [comment]
@KingSora I agree that it's not always good idea to let you trigger something which is invisible, but since most people would expect them to show up on hover, would it be a good option to have? The way [simplebar](https://github.com/Grsmto/simplebar) does it

--- 

By the way, I assumed that's how it works because it says so in the description:

![image](https://user-images.githubusercontent.com/13764106/51641906-a10c8680-1f78-11e9-9918-462e1fbfb8ac.png)

It implies that the scrollbar would appear not only when you scroll but also when you hover over the scrollbars.

**Comment by AlexSHoffman** [comment]
@KingSora I agree that it's not always good idea to let you trigger something which is invisible, but since most people would expect them to show up on hover, wouldn't it be a good option to have? It would provide the minimal look and the expected functionality. The way [simplebar](http://grsmto.github.io/simplebar/) does it

--- 

I thought that's how it works in the "OverlayScrollbars" as well. I misunderstood the description, which kind of implies that the scrollbar would appear not only when you scroll but also when you hover over it (I now understand that it only prevents it from hiding)

![image](https://user-images.githubusercontent.com/13764106/51641906-a10c8680-1f78-11e9-9918-462e1fbfb8ac.png)

**Comment by KingSora** [comment]
Now I understand, you're correct, this description is a bit misleading.
I agree with your point 

> wouldn't it be a good option to have

But I won't change the behavior `scroll` has, as it is the most minimal case the plugin shall have. It would be possible to add another value for this option. - Any Ideas for how to name it? 

I'm still not quite sure if I'll implement it, as this option has already so many values to choose from.

**Comment by AlexSHoffman** [comment]
@KingSora I think `scrollOrHover` would be a nice descriptive name for it. It's quite late, I cannot think of a more creative name right now :)

But yeah, it will probably take several hours of work to implement this option. Please feel free to close the issue if you decide that it's not worth it.

By the way, did you create this whole project by yourself? It's quite impressive you implemented so many things without much help.

**Comment by KingSora** [comment]
Yes, I am a "one man team", but I'm quite dedicated (most of the time). 

In terms of the documentation page, I like to learn and try out new things, so the site was and is more like a playground for me.

**Comment by AlexSHoffman** [comment]
@KingSora I can imagine how much time you spent learning how to do all that. I'm also building a feature-rich open-source "file manager" app by myself, and although I agree that it feels like a playground and it's super fun, but it takes soooo much time to learn how to make a big feature-full project.

By the way, just wanted to ask, may I use OverlayScrollbars in my file manager app? It will be open-source as well (MIT license)

**Comment by AlexSHoffman** [comment]
@KingSora I can imagine how much time you spent learning how to do all that. I'm also building a feature-rich open-source project (a "file manager" app) by myself, and although I agree that it feels like a playground and it's super fun, but man does it take a lot of time to learn how to make all the features to work together.

By the way, just wanted to ask, may I use OverlayScrollbars in my file manager app? It will be open-source as well (MIT license)

**Comment by KingSora** [comment]
@AlexSHoffman Yes! The development time before the 1.0.0 release was actually over one whole year.
I'd be honored if you'd use my plugin for your app. If you have any questions or if you find bugs, feel free to open a issue here!

**Comment by AlexSHoffman** [comment]
@KingSora great, thanks! 
Can I add you in Discord or some other messenger app? Maybe we could cooperate on some projects?

**Comment by KingSora** [comment]
@AlexSHoffman Yes, just write me a E-Mail with your Discord Username and I'll add you. You can find my E-Mail Address on my Profile. But to be honest I'm not very often online in Discord. The best way to contact me would be my E-Mail.

**Comment by KingSora** [comment]
Alright, I've decided that this feature is a bit too special considering the fact that the plugin already offers the `move` and `leave` autoHide options. 

Especially the `move` option is ment to fulfil this rquirement but in a more suited way, because both scrollbars will appear if you move your cursor which leads to a more expected user experience. (Nothing will appear if you hover over a hidden element, instead it appears if you move over the whole element generally) It's a bit hard to describe for me, but after testing this feature I've come to this conculsion.

Nevertheless I want to provide a workaround for anyone who wants to use this. Luckily it's very simple! 
You have to add only one new CSS rule at the bottom of the plugins CSS file:
```CSS
.os-scrollbar {
    pointer-events: auto;
    visibility: visible;
}
```
I think this is a fair compromise for everyone. 
If someone has a very good argument and can convince me why this should be added in some way to the options pool (not necessarily as a autoHide possibility but generally as a option) regardless of my argumentation, feel free to comment and we can discuss it together.
