### ISSUE TITLE
Using OverlayScrollbars with Awesomplete

### ISSUE THREAD

**Issue by bohdanafanasyev** [KingSora/OverlayScrollbars#86]
Greetings, KingSora 

First of all let me thank you for the great job done with this magical plugin, functionality and documentation are indeed on high point 👍 

Currently the OverlayScrollbars works perfectly fine for the most cases, but I've encountered a small challenge while integrating it with [Awesomplete](https://leaverou.github.io/awesomplete/#events).

[Here](https://codepen.io/anon/pen/ErNEde?editors=0010) is the small demonstration of the challenge, where when navigating with the arrow keys will not scroll the container, but still will trigger `aria-selected=true` on the `li`.

I will appreciate a lot if you could have a look on the demonstrated implementation and hopefully explain what could be the possible solution 😄 🙇

**Comment by KingSora** [comment]
Good day!
Thank you for the demo, it really helped me to understand the problem.

At first I thought it might be a bug of the plugin, but then I realized that `Awesomplete` might is doing the scrolling manually. I've checked their code and indeed, I was correct: [https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L264](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L264)

I've solved this isse with a `MutationObserver` which observes the attribute `aria-selected` of the childs of the `ul` element. If the attribute `aria-selected` changes from `false` to `true` its the indicator for the following code which is scrolling to that particular element:

```javascript
//...
let marginTop = parseFloat(window.getComputedStyle(awesomplete).getPropertyValue('margin-top'));
if(isNaN(marginTop))
    marginTop = 0;
const osState = osInstance.getState();
const scrollTop = listElm.offsetTop - osState.viewportSize.height + listElm.clientHeight + marginTop;
osInstance.scroll({ y : scrollTop });
//...
```
As you can see it's pretty much the same as the line of the in the plugin, except of the marginTop part.
I've created a full demo for you here: [https://codepen.io/anon/pen/ErZEqp](https://codepen.io/anon/pen/ErZEqp)

I hope the code is clear and is solving your issue!
