### ISSUE TITLE
Use OverlayScrollbar on select element

### ISSUE THREAD

**Issue by dayvydnascimento** [KingSora/OverlayScrollbars#93]
document.addEventListener("DOMContentLoaded", function() {
	OverlayScrollbars(document.getElementById('tiposPermissoes'), { });
});

Does not work, select.

select id="tiposPermissoes" class="over-perm"

**Comment by KingSora** [comment]
Good day!

I'm sorry but OverlayScrollbars doesn't support `select` elements. 
You can read more about this topic in the [documentation](https://kingsora.github.io/OverlayScrollbars/#!documentation/supportedelements).

I'm also not quite sure how I would implement this (if I would add support). 
Because a select can be `dropdown` or `listbox` depending on the `size` attribute. Everything greater than `1` will be a listbox, everything else will be a dropdown. (as seen [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_size).)

I'm also not sure how many people would need such a feature and if this is "worth" implementing.
Let's do a poll, everyone who needs the `select` element to be supported, please leave a reacton on this message.

**Comment by boukenka** [comment]
Good evening,

Here is an implementation for the select2 with OverlayScrollbar.
I hope it helps even I guess, there is surely a better way.

```javascript
// special drop down coming from: 
// https://select2.org/ and https://select2.github.io/select2-bootstrap-theme/
// the select bootstrap css coding has been modified manually to get 
// a consistent style with the web interface
$('#id_search_box_id').select2(
{
	// the placeholder value will be displayed until a selection is made.
	placeholder: 'Choose a box',
	// define custom themes.
	theme: "bootstrap",
	// this decorator implements clearable selections.
	allowClear: true,
	// determines the minimum number of results required in 
	// the initial population of the dropdown to display the search box.
	minimumResultsForSearch: 3,
	// limit the maximum length of search terms.
	maximumInputLength: 10,
	// automatically close the dropdown when an element is selected.
	closeOnSelect: true
});

// add a custom scrollbar to the drop down when there is an input
var instance;
$(document).on('keyup', '.select2-search__field', function () 
{
     customizeDropdownScrollbar();
});

// add a custom scrollbar to the drop down when the drop down is opened
$('select').on('select2:open', function () 
{
     customizeDropdownScrollbar();
});

// the customized scrollbar is added when the drop down is opened or 
// there is an input
function customizeDropdownScrollbar()
{
    setTimeout(function () 
    {
	// count the number of elements which can be used for selection in the drop down
	var count = $('#select2-id_search_box_id-results').find("li").length;

	// check if a previous instance of the customized scrollbar already exists
	if (typeof instance !== 'undefined' && count >  1)
	{
		// destrop the previous instance
		instance.destroy();
	}

	// assign a scrollbar to a different element according to the number 
        // of available elements
	// trick to fix the customization of the scrollbar when there is one 
        // or zero element to select
	if (count >  1)
	{
		// create and store the instance reference for future destruction
		instance = $('#select2-id_search_box_id-results').overlayScrollbars(
		{
			className: overlayScrollbarsTheme,
			resize: "none",
			scrollbars : 
			{
				visibility: "visible",
				autoHide: "never",
			},
		}).overlayScrollbars();
	}
	else
	{
		// assign the scrollbar to an higher level in the hierarchy of the drop down
		$('.select2-dropdown select2-dropdown--below').overlayScrollbars(
		{
			className: overlayScrollbarsTheme,
			resize: "none",
			scrollbars : 
			{
				visibility: "visible",
				autoHide: "never",
			},
		}).overlayScrollbars();
	}
   }, 0);
}
```

**Comment by dayvydnascimento** [comment]
> ```js
> https://select2.org
> ```

it works with size in select?

example: select id="test" class="example" size="4"

**Comment by boukenka** [comment]
Good evenining,

Please find in attachment an example for the implementation of the overlay scrollbar 
in the Select2 element (dark/light theme). I hope it will help to solve your issue.
[Select2-Scrollbar.zip](https://github.com/KingSora/OverlayScrollbars/files/2920730/Select2-Scrollbar.zip)

**Comment by krystyna93** [comment]
@KingSora 
does this work for selects specifically with the bootstrap-selects?
I cant seem to get it to work on them

**Comment by KingSora** [comment]
@krystyna93 Yes it does.
I've created two examples for you:
- A Bootstrap Dropdown with a native Scrollbar: https://jsfiddle.net/qwx7co14/
- A Bootstrap Dropdown with OverlayScrollbars: https://jsfiddle.net/qwx7co14/1/

**Comment by krystyna93** [comment]
@KingSora I think you misunderstood me. I meant using the overlayScrollbar with the [Bootstrap-select ](https://developer.snapappointments.com/bootstrap-select/) not a Bootstrap dropdown. 
I know it would work with a dropdown.

Does it work with a select from the Bootstrap-select??

**Comment by KingSora** [comment]
Just to clarify: `bootstrap-select` is basically the same as the `bootstrap dropdown`, just with more options and the benefit to keep the native `select` element in the DOM for usage on mobile. `Bootstrap-select` builds a similar structure as `bootstrap dropdown` so OverlayScrollbars can also be used with it. 

But because of the programming choices the author of this plugin did, OverlayScrollbars has to be initialized in the events of `bootstrap-select`, because he is selecting the list container rather than stroing it's instance in a variable. This could be fixed though if you open a issue there.

Once again a example here: [https://jsfiddle.net/0bp6ew31/](https://jsfiddle.net/0bp6ew31/)

**Comment by krystyna93** [comment]
@KingSora Ahh, I understand now. My apologies. 
So, I have to initialize it in the events of bootstrap-select. 
I am such a novice when trying to understand these things, but I really appreciate your provided examples to clarify the solution for me.

Thank you, Rene! :)

**Comment by KingSora** [comment]
@krystyna93 glad I could help! :)

**Comment by krystyna93** [comment]
@KingSora for all the other users implementing OverlayScrollbar with Bootstrap-select.

I implemented the example for the Bootstrap-select, however I have found that if there are more then one Bootstraps-select, only the first select seems to be adding in the OverlayScrollbar, while the rest just display the default browser scrollbar.

I also adjusted the jsfiddle example you provided with another selectpicker and it is displaying the same behavior too.

Should the js be amended somehow to include all selects? Its weird why it wont work for more the one... :/

Thanks.

**Comment by KingSora** [comment]
@krystyna93 Sorry for my late response but I've creaed a example where I use two dropdown-selects: https://jsfiddle.net/jgmrd4c7/

Hope it helps!

**Comment by krystyna93** [comment]
@KingSora thank you! Your a lifesaver 👍

**Comment by shamilkurbonov** [comment]
// Scrollbar
            let GklObj = {instance: false}
            $('.select2.select2-container.select2-container--default').on('click', () => {
                // OverlayScrollbars.extension("myExtension", function() { return { }; });
                GklObj.instance = OverlayScrollbars($('.select2-results ul'), { });
                if($(this).hasClass('select2-container--open'))
                    GklObj.instance.destroy()
            })
            $(document).mouseup(function (e) {
                let div = $(".select2.select2-container.select2-container--default")
                let scroll = $(".os-scrollbar.os-scrollbar-vertical")
                let search = $(".select2-search__field")
                if (!div.is(e.target) && div.has(e.target).length === 0
                    && !search.is(e.target) && !scroll.is(e.target)
                    && scroll.has(e.target).length === 0 && GklObj.instance)
                    GklObj.instance.destroy()   //remove overScrollbar
            });
