### ISSUE TITLE
OverlayScrollbars requires unsafe "Content Security Policy"

### ISSUE THREAD

**Issue by vobruba-martin** [KingSora/OverlayScrollbars#94]
The current version uses `eval` and cannot be used with default Content-Security-Policy (http://www.w3.org/TR/CSP/, https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) headers.

Sample code:
```javascript
instance.scroll("+=500px");
```
Browser interrupts execution [here](https://github.com/KingSora/OverlayScrollbars/blob/master/js/OverlayScrollbars.js#L5559).

Known workarounds:
 - Use number values (`instance.scroll(500)`).
 - Set policy to `unsafe-eval` which defeats the purpose of CSP.

**Comment by KingSora** [comment]
Good day!

Could you please explain how this is exactly affecting your website? Unfortunately I don't really know much about content-security-policies (and I don't have enough time to read trough your links), but isn't this something you have to set by yourself before you load a script?

**Comment by nuthinking** [comment]
With a regex (or even simpler logic) you can probably avoid the `eval()`?

**Comment by KingSora** [comment]
@nuthinking Thats not possible, since the eval has its purpose.
You can pass simple values such as `"+=100px"`, but you can also use units such as `+=50%`, and you can even pass complex calculations such as `+=(50% - 15px) / 2`. It's possible to avoid the `eval()` call if you pass simple values without units (except `px`, so `+=100px` is still possible) but the eval is critical if you pass numbers with units or complex calculations. - The next version will work this way.

**Comment by vobruba-martin** [comment]
@KingSora I will create a demo page with CSP as soon as I have some time.

**Comment by KingSora** [comment]
As mentioned above I've changed the behavior of the `scroll()` method in the new [version 1.7.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.7.0). Please take a look and provide some feedback!

**Comment by KingSora** [comment]
@vobruba-martin any update? Did the `1.7.0` update improve the situation?

**Comment by KingSora** [comment]
Since there wasn't any activity since a few months, I'll close this issue for now. In case this problem isn't solved like [above described](https://github.com/KingSora/OverlayScrollbars/issues/94#issuecomment-470529658) or the plugin isn't usable at all, please don't hesitate to reopen the issue.
