### ISSUE TITLE
Vertical overflow calculation impacting horizontal overflow, vice versa

### ISSUE THREAD

**Issue by devendran** [KingSora/OverlayScrollbars#98]
We noticed an issue when the vertical overflow calculation impacting horizontal overflow.

The issue is narrowed down to force rounding code below, where in overflowAmount.x check makes overflowAmount.y as zero even in valid cases

```
var hideOverflowForceRounding = (_viewportElement[0].scrollLeftMax === 0 && overflowAmount.x > 0 && overflowAmount.x < 1) || (_viewportElement[0].scrollTopMax === 0 && overflowAmount.y > 0 && overflowAmount.y < 1);
if (hideOverflowForceTextarea || hideOverflowForceRounding)
	overflowAmount.x = overflowAmount.y = 0;
```

We have fixed by making 2 different variables each for x and y calculations like below

```
var hideOverflowForceRoundingX = (_viewportElement[0].scrollLeftMax === 0 && overflowAmount.x > 0 && overflowAmount.x < 1);
var hideOverflowForceRoundingY = (_viewportElement[0].scrollTopMax === 0 && overflowAmount.y > 0 && overflowAmount.y < 1);
                        
if (hideOverflowForceTextarea || hideOverflowForceRoundingX)
	overflowAmount.x =  0;
if (hideOverflowForceTextarea || hideOverflowForceRoundingY)
    overflowAmount.y =  0;
```

**Comment by KingSora** [comment]
Good day!

Thanks for your contribution! I'll implement it as soon as I've time, but at the earliest in 2 weeks, because I'm on vacation right now.

**Comment by KingSora** [comment]
Small update here, because its been a while. 
I've fixed this issue and it will definitely be included in the next version!

**Comment by KingSora** [comment]
[Version 1.7.0](https://github.com/KingSora/OverlayScrollbars/releases/tag/v1.7.0) is now out!
