### ISSUE TITLE
OverlayScrollbars prevents SmoothScroll from working

### ISSUE THREAD

**Issue by w3althambition** [KingSora/OverlayScrollbars#99]
Hey guys, I just made this test page and I added both SmoothScroll and OverlayScrollbars. I have one issue, I can't use both of them at the same time. I am not sure how to fix this. There is no option/method in OverlayScrollbars to enable smooth scrolling but it somehow stops SmoothScroll package from working. Can I make OverlayScrollbars just visually change the scroll bar and have SmoothScroll the smooth scrolling, especially for nav links?

**Comment by KingSora** [comment]
Good day! 

Since you closed this issue, I guess you figured it out by yourself. If this is the case, could you please share your fix with everyone, in case someone has a similar problem?
If you still have no Idea how to implement this, I'll be happy to help you!
